// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +zifencei \
// RUN:  -target-feature +m -target-feature +a               \
// RUN:  -target-feature +f -target-feature +d               \
// RUN:  -emit-llvm %s -o - | FileCheck %s                   \
// RUN:  --check-prefix=CHECK-IR

__attribute__((target("arch=+v"))) void test1(void) {}
__attribute__((target("arch=+v,+zbb"))) void test1(void) {}
__attribute__((target("arch=+v,+zbb,+zicond1p0"))) void test1(void) {}
__attribute__((target("arch=rv64gc"))) void test1(void) {}
__attribute__((target("default"))) void test1(void) {}

__attribute__((target("default"))) void test2(void) {}

void test3() { test1(); test2(); }




// CHECK-IR-LABEL: define dso_local void @test1.v
// CHECK-IR-SAME: () #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test1.v_zbb
// CHECK-IR-SAME: () #[[ATTR1:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test1.v_zbb_experimental-zicond
// CHECK-IR-SAME: () #[[ATTR2:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test1.__RISCV_TargetAttrNeedOverride_m_a_f_d_c_zicsr_zifencei
// CHECK-IR-SAME: () #[[ATTR3:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test1
// CHECK-IR-SAME: () #[[ATTR4:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test2
// CHECK-IR-SAME: () #[[ATTR4]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define dso_local void @test3
// CHECK-IR-SAME: () #[[ATTR4]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    call void @test1.resolver()
// CHECK-IR-NEXT:    call void @test2.resolver()
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define weak_odr void @test1.resolver() comdat {
// CHECK-IR-NEXT:  resolver_entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = call i1 @__riscv_ifunc_select(ptr @[[GLOB0:[0-9]+]])
// CHECK-IR-NEXT:    br i1 [[TMP0]], label [[RESOLVER_RETURN:%.*]], label [[RESOLVER_ELSE:%.*]]
// CHECK-IR:       resolver_return:
// CHECK-IR-NEXT:    musttail call void @test1.v()
// CHECK-IR-NEXT:    ret void
// CHECK-IR:       resolver_else:
// CHECK-IR-NEXT:    [[TMP1:%.*]] = call i1 @__riscv_ifunc_select(ptr @[[GLOB1:[0-9]+]])
// CHECK-IR-NEXT:    br i1 [[TMP1]], label [[RESOLVER_RETURN1:%.*]], label [[RESOLVER_ELSE2:%.*]]
// CHECK-IR:       resolver_return1:
// CHECK-IR-NEXT:    musttail call void @test1.v_zbb()
// CHECK-IR-NEXT:    ret void
// CHECK-IR:       resolver_else2:
// CHECK-IR-NEXT:    [[TMP2:%.*]] = call i1 @__riscv_ifunc_select(ptr @[[GLOB2:[0-9]+]])
// CHECK-IR-NEXT:    br i1 [[TMP2]], label [[RESOLVER_RETURN3:%.*]], label [[RESOLVER_ELSE4:%.*]]
// CHECK-IR:       resolver_return3:
// CHECK-IR-NEXT:    musttail call void @test1.v_zbb_experimental-zicond()
// CHECK-IR-NEXT:    ret void
// CHECK-IR:       resolver_else4:
// CHECK-IR-NEXT:    [[TMP3:%.*]] = call i1 @__riscv_ifunc_select(ptr @[[GLOB3:[0-9]+]])
// CHECK-IR-NEXT:    br i1 [[TMP3]], label [[RESOLVER_RETURN5:%.*]], label [[RESOLVER_ELSE6:%.*]]
// CHECK-IR:       resolver_return5:
// CHECK-IR-NEXT:    musttail call void @test1.__RISCV_TargetAttrNeedOverride_m_a_f_d_c_zicsr_zifencei()
// CHECK-IR-NEXT:    ret void
// CHECK-IR:       resolver_else6:
// CHECK-IR-NEXT:    musttail call void @test1()
// CHECK-IR-NEXT:    ret void
//
//
// CHECK-IR-LABEL: define weak_odr void @test2.resolver() comdat {
// CHECK-IR-NEXT:  resolver_entry:
// CHECK-IR-NEXT:    musttail call void @test2()
// CHECK-IR-NEXT:    ret void
//
