; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -O3 -riscv-sched-exclude-csrs=false < %s \
; RUN:   | FileCheck %s --check-prefix=INCLUDE
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -O3 < %s | FileCheck %s --check-prefix=EXCLUDE

; flips from ntest (SPEC 707.ntest_r): a leaf function without loops. The
; original order needs 14 GPRs. With the callee-saved registers in the pressure
; limit (-riscv-sched-exclude-csrs=false), the pre-RA scheduler groups the
; loads and multiplies and needs CSRs. By default, the limit is the 15
; caller-saved GPRs, the schedule goes over it, and the scheduler restores the
; original order.

%struct.magicFlip = type { i64, i64, i64, i64, i64, i64, i32, i32, i64 }

@neighbors = external dso_local local_unnamed_addr global [64 x i64], align 8
@flipArray = external dso_local local_unnamed_addr global [64 x %struct.magicFlip], align 8
@rowFlips = external dso_local local_unnamed_addr global [8 x [256 x i64]], align 8
@d9Flips = external dso_local local_unnamed_addr global [12 x [256 x i64]], align 8
@colFlips = external dso_local local_unnamed_addr global [8 x [256 x i64]], align 8
@d7Flips = external dso_local local_unnamed_addr global [12 x [256 x i64]], align 8
@outsides = external dso_local local_unnamed_addr global [8 x [256 x i8]], align 1
@insides = external dso_local local_unnamed_addr global [8 x [256 x i8]], align 1

define dso_local noundef i64 @flips(i32 noundef signext %sq, i64 noundef %mover, i64 noundef %enemy) local_unnamed_addr {
;
; INCLUDE-LABEL: flips:
; INCLUDE:       # %bb.0: # %entry
; INCLUDE-NEXT:    lui a3, %hi(neighbors)
; INCLUDE-NEXT:    addi a3, a3, %lo(neighbors)
; INCLUDE-NEXT:    sh3add a3, a0, a3
; INCLUDE-NEXT:    ld a3, 0(a3)
; INCLUDE-NEXT:    and a3, a3, a2
; INCLUDE-NEXT:    beqz a3, .LBB0_2
; INCLUDE-NEXT:  # %bb.1: # %if.then
; INCLUDE-NEXT:    addi sp, sp, -32
; INCLUDE-NEXT:    .cfi_def_cfa_offset 32
; INCLUDE-NEXT:    sd s0, 24(sp) # 8-byte Folded Spill
; INCLUDE-NEXT:    sd s1, 16(sp) # 8-byte Folded Spill
; INCLUDE-NEXT:    sd s2, 8(sp) # 8-byte Folded Spill
; INCLUDE-NEXT:    sd s3, 0(sp) # 8-byte Folded Spill
; INCLUDE-NEXT:    .cfi_offset s0, -8
; INCLUDE-NEXT:    .cfi_offset s1, -16
; INCLUDE-NEXT:    .cfi_offset s2, -24
; INCLUDE-NEXT:    .cfi_offset s3, -32
; INCLUDE-NEXT:    slli a5, a0, 6
; INCLUDE-NEXT:    lui a3, %hi(flipArray)
; INCLUDE-NEXT:    addi a3, a3, %lo(flipArray)
; INCLUDE-NEXT:    srai t6, a0, 3
; INCLUDE-NEXT:    add a5, a5, a3
; INCLUDE-NEXT:    lui s1, %hi(outsides)
; INCLUDE-NEXT:    addi s1, s1, %lo(outsides)
; INCLUDE-NEXT:    slli s2, t6, 8
; INCLUDE-NEXT:    ld a4, 0(a5)
; INCLUDE-NEXT:    ld a3, 8(a5)
; INCLUDE-NEXT:    ld t0, 16(a5)
; INCLUDE-NEXT:    ld a7, 24(a5)
; INCLUDE-NEXT:    ld t1, 32(a5)
; INCLUDE-NEXT:    ld t2, 40(a5)
; INCLUDE-NEXT:    lwu a6, 48(a5)
; INCLUDE-NEXT:    andi s0, a0, -8
; INCLUDE-NEXT:    andi a0, a0, 7
; INCLUDE-NEXT:    add s3, s1, s2
; INCLUDE-NEXT:    slli t6, t6, 11
; INCLUDE-NEXT:    lwu a5, 52(a5)
; INCLUDE-NEXT:    and t4, t0, a2
; INCLUDE-NEXT:    and t3, a4, a2
; INCLUDE-NEXT:    and t5, t1, a2
; INCLUDE-NEXT:    srl a2, a2, s0
; INCLUDE-NEXT:    and a4, a4, a1
; INCLUDE-NEXT:    and t0, t0, a1
; INCLUDE-NEXT:    srl s0, a1, s0
; INCLUDE-NEXT:    and a1, t1, a1
; INCLUDE-NEXT:    mul t4, t4, a7
; INCLUDE-NEXT:    mul t3, t3, a3
; INCLUDE-NEXT:    zext.b a2, a2
; INCLUDE-NEXT:    mul t5, t5, t2
; INCLUDE-NEXT:    mul a3, a4, a3
; INCLUDE-NEXT:    mul a4, t0, a7
; INCLUDE-NEXT:    mul a1, a1, t2
; INCLUDE-NEXT:    slli a6, a6, 11
; INCLUDE-NEXT:    srli t4, t4, 56
; INCLUDE-NEXT:    srli t3, t3, 56
; INCLUDE-NEXT:    srli t5, t5, 56
; INCLUDE-NEXT:    srli a3, a3, 56
; INCLUDE-NEXT:    add t4, t4, s3
; INCLUDE-NEXT:    slli s3, a0, 8
; INCLUDE-NEXT:    srli a4, a4, 56
; INCLUDE-NEXT:    srli a1, a1, 56
; INCLUDE-NEXT:    add s1, s1, s3
; INCLUDE-NEXT:    slli a0, a0, 11
; INCLUDE-NEXT:    slli a5, a5, 11
; INCLUDE-NEXT:    add a2, a2, s1
; INCLUDE-NEXT:    add t3, t3, s1
; INCLUDE-NEXT:    add t5, t5, s1
; INCLUDE-NEXT:    lui s1, %hi(insides)
; INCLUDE-NEXT:    addi s1, s1, %lo(insides)
; INCLUDE-NEXT:    lbu a2, 0(a2)
; INCLUDE-NEXT:    lbu a7, 0(t3)
; INCLUDE-NEXT:    lbu t0, 0(t4)
; INCLUDE-NEXT:    lbu t1, 0(t5)
; INCLUDE-NEXT:    add s3, s3, s1
; INCLUDE-NEXT:    add s1, s1, s2
; INCLUDE-NEXT:    and a2, a2, s0
; INCLUDE-NEXT:    and a3, a3, a7
; INCLUDE-NEXT:    and a4, a4, t0
; INCLUDE-NEXT:    lui a7, %hi(rowFlips)
; INCLUDE-NEXT:    addi a7, a7, %lo(rowFlips)
; INCLUDE-NEXT:    lui t0, %hi(d9Flips)
; INCLUDE-NEXT:    addi t0, t0, %lo(d9Flips)
; INCLUDE-NEXT:    and a1, a1, t1
; INCLUDE-NEXT:    lui t1, %hi(colFlips)
; INCLUDE-NEXT:    addi t1, t1, %lo(colFlips)
; INCLUDE-NEXT:    add a2, a2, s3
; INCLUDE-NEXT:    add a3, a3, s3
; INCLUDE-NEXT:    add a4, a4, s1
; INCLUDE-NEXT:    add a7, a7, t6
; INCLUDE-NEXT:    add a6, a6, t0
; INCLUDE-NEXT:    add a1, a1, s3
; INCLUDE-NEXT:    add a0, a0, t1
; INCLUDE-NEXT:    ld s0, 24(sp) # 8-byte Folded Reload
; INCLUDE-NEXT:    ld s1, 16(sp) # 8-byte Folded Reload
; INCLUDE-NEXT:    ld s2, 8(sp) # 8-byte Folded Reload
; INCLUDE-NEXT:    ld s3, 0(sp) # 8-byte Folded Reload
; INCLUDE-NEXT:    lbu a2, 0(a2)
; INCLUDE-NEXT:    lbu a3, 0(a3)
; INCLUDE-NEXT:    lbu a4, 0(a4)
; INCLUDE-NEXT:    lbu a1, 0(a1)
; INCLUDE-NEXT:    sh3add a2, a2, a7
; INCLUDE-NEXT:    sh3add a3, a3, a6
; INCLUDE-NEXT:    sh3add a0, a4, a0
; INCLUDE-NEXT:    ld a2, 0(a2)
; INCLUDE-NEXT:    ld a3, 0(a3)
; INCLUDE-NEXT:    ld a0, 0(a0)
; INCLUDE-NEXT:    or a2, a2, a3
; INCLUDE-NEXT:    lui a3, %hi(d7Flips)
; INCLUDE-NEXT:    addi a3, a3, %lo(d7Flips)
; INCLUDE-NEXT:    add a3, a3, a5
; INCLUDE-NEXT:    sh3add a1, a1, a3
; INCLUDE-NEXT:    ld a1, 0(a1)
; INCLUDE-NEXT:    or a0, a0, a1
; INCLUDE-NEXT:    or a0, a0, a2
; INCLUDE-NEXT:    .cfi_restore s0
; INCLUDE-NEXT:    .cfi_restore s1
; INCLUDE-NEXT:    .cfi_restore s2
; INCLUDE-NEXT:    .cfi_restore s3
; INCLUDE-NEXT:    addi sp, sp, 32
; INCLUDE-NEXT:    .cfi_def_cfa_offset 0
; INCLUDE-NEXT:    ret
; INCLUDE-NEXT:  .LBB0_2:
; INCLUDE-NEXT:    li a0, 0
; INCLUDE-NEXT:    ret
;
; EXCLUDE-LABEL: flips:
; EXCLUDE:       # %bb.0: # %entry
; EXCLUDE-NEXT:    lui a3, %hi(neighbors)
; EXCLUDE-NEXT:    addi a3, a3, %lo(neighbors)
; EXCLUDE-NEXT:    sh3add a3, a0, a3
; EXCLUDE-NEXT:    ld a3, 0(a3)
; EXCLUDE-NEXT:    and a3, a3, a2
; EXCLUDE-NEXT:    beqz a3, .LBB0_2
; EXCLUDE-NEXT:  # %bb.1: # %if.then
; EXCLUDE-NEXT:    slli a4, a0, 6
; EXCLUDE-NEXT:    lui a3, %hi(flipArray)
; EXCLUDE-NEXT:    addi a3, a3, %lo(flipArray)
; EXCLUDE-NEXT:    srai a6, a0, 3
; EXCLUDE-NEXT:    add a4, a4, a3
; EXCLUDE-NEXT:    slli a3, a6, 11
; EXCLUDE-NEXT:    lui a5, %hi(rowFlips)
; EXCLUDE-NEXT:    addi a5, a5, %lo(rowFlips)
; EXCLUDE-NEXT:    andi t2, a0, -8
; EXCLUDE-NEXT:    andi t3, a0, 7
; EXCLUDE-NEXT:    add t1, a5, a3
; EXCLUDE-NEXT:    srl a3, a2, t2
; EXCLUDE-NEXT:    slli a0, t3, 8
; EXCLUDE-NEXT:    lui t0, %hi(outsides)
; EXCLUDE-NEXT:    addi t0, t0, %lo(outsides)
; EXCLUDE-NEXT:    zext.b a3, a3
; EXCLUDE-NEXT:    add a5, t0, a0
; EXCLUDE-NEXT:    add a3, a3, a5
; EXCLUDE-NEXT:    lui a7, %hi(insides)
; EXCLUDE-NEXT:    addi a7, a7, %lo(insides)
; EXCLUDE-NEXT:    lbu t4, 0(a3)
; EXCLUDE-NEXT:    add a3, a7, a0
; EXCLUDE-NEXT:    srl a0, a1, t2
; EXCLUDE-NEXT:    lui t2, %hi(d9Flips)
; EXCLUDE-NEXT:    addi t2, t2, %lo(d9Flips)
; EXCLUDE-NEXT:    slli a6, a6, 8
; EXCLUDE-NEXT:    add t0, t0, a6
; EXCLUDE-NEXT:    add a6, a6, a7
; EXCLUDE-NEXT:    and a0, a0, t4
; EXCLUDE-NEXT:    add a0, a0, a3
; EXCLUDE-NEXT:    lbu a0, 0(a0)
; EXCLUDE-NEXT:    sh3add a0, a0, t1
; EXCLUDE-NEXT:    lwu t1, 48(a4)
; EXCLUDE-NEXT:    ld a0, 0(a0)
; EXCLUDE-NEXT:    slli t1, t1, 11
; EXCLUDE-NEXT:    add t1, t1, t2
; EXCLUDE-NEXT:    ld t2, 0(a4)
; EXCLUDE-NEXT:    ld t4, 8(a4)
; EXCLUDE-NEXT:    and t5, t2, a2
; EXCLUDE-NEXT:    and t2, t2, a1
; EXCLUDE-NEXT:    mul t5, t5, t4
; EXCLUDE-NEXT:    mul t2, t2, t4
; EXCLUDE-NEXT:    srli t5, t5, 56
; EXCLUDE-NEXT:    srli t2, t2, 56
; EXCLUDE-NEXT:    add t5, t5, a5
; EXCLUDE-NEXT:    lbu t5, 0(t5)
; EXCLUDE-NEXT:    and t2, t2, t5
; EXCLUDE-NEXT:    add t2, t2, a3
; EXCLUDE-NEXT:    lbu t2, 0(t2)
; EXCLUDE-NEXT:    sh3add t1, t2, t1
; EXCLUDE-NEXT:    lui t2, %hi(colFlips)
; EXCLUDE-NEXT:    addi t2, t2, %lo(colFlips)
; EXCLUDE-NEXT:    ld t1, 0(t1)
; EXCLUDE-NEXT:    or a0, t1, a0
; EXCLUDE-NEXT:    slli t1, t3, 11
; EXCLUDE-NEXT:    add t1, t1, t2
; EXCLUDE-NEXT:    ld t2, 16(a4)
; EXCLUDE-NEXT:    ld t3, 24(a4)
; EXCLUDE-NEXT:    and t4, t2, a2
; EXCLUDE-NEXT:    and t2, t2, a1
; EXCLUDE-NEXT:    mul t4, t4, t3
; EXCLUDE-NEXT:    mul t2, t2, t3
; EXCLUDE-NEXT:    srli t4, t4, 56
; EXCLUDE-NEXT:    srli t2, t2, 56
; EXCLUDE-NEXT:    add t0, t0, t4
; EXCLUDE-NEXT:    lbu t0, 0(t0)
; EXCLUDE-NEXT:    and a7, t2, t0
; EXCLUDE-NEXT:    lui t0, %hi(d7Flips)
; EXCLUDE-NEXT:    addi t0, t0, %lo(d7Flips)
; EXCLUDE-NEXT:    add a6, a6, a7
; EXCLUDE-NEXT:    lwu a7, 52(a4)
; EXCLUDE-NEXT:    slli a7, a7, 11
; EXCLUDE-NEXT:    add a7, a7, t0
; EXCLUDE-NEXT:    ld t0, 32(a4)
; EXCLUDE-NEXT:    ld a4, 40(a4)
; EXCLUDE-NEXT:    and a2, t0, a2
; EXCLUDE-NEXT:    and a1, t0, a1
; EXCLUDE-NEXT:    mul a2, a2, a4
; EXCLUDE-NEXT:    mul a1, a1, a4
; EXCLUDE-NEXT:    srli a2, a2, 56
; EXCLUDE-NEXT:    srli a1, a1, 56
; EXCLUDE-NEXT:    add a2, a2, a5
; EXCLUDE-NEXT:    lbu a2, 0(a2)
; EXCLUDE-NEXT:    and a1, a1, a2
; EXCLUDE-NEXT:    add a1, a1, a3
; EXCLUDE-NEXT:    lbu a6, 0(a6)
; EXCLUDE-NEXT:    lbu a1, 0(a1)
; EXCLUDE-NEXT:    sh3add a6, a6, t1
; EXCLUDE-NEXT:    sh3add a1, a1, a7
; EXCLUDE-NEXT:    ld a6, 0(a6)
; EXCLUDE-NEXT:    ld a1, 0(a1)
; EXCLUDE-NEXT:    or a1, a6, a1
; EXCLUDE-NEXT:    or a0, a0, a1
; EXCLUDE-NEXT:    ret
; EXCLUDE-NEXT:  .LBB0_2:
; EXCLUDE-NEXT:    li a0, 0
; EXCLUDE-NEXT:    ret
entry:
  %idxprom = sext i32 %sq to i64
  %arrayidx = getelementptr inbounds [8 x i8], ptr @neighbors, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  %and = and i64 %0, %enemy
  %tobool.not = icmp eq i64 %and, 0
  br i1 %tobool.not, label %return, label %if.then

if.then:                                          ; preds = %entry
  %arrayidx2 = getelementptr inbounds [64 x i8], ptr @flipArray, i64 %idxprom
  %shr = ashr i32 %sq, 3
  %and3 = and i32 %sq, 7
  %idxprom4 = sext i32 %shr to i64
  %arrayidx5 = getelementptr inbounds [2048 x i8], ptr @rowFlips, i64 %idxprom4
  %shl.i = and i32 %sq, -8
  %sh_prom.i = zext i32 %shl.i to i64
  %shr.i = lshr i64 %enemy, %sh_prom.i
  %and.i = and i64 %shr.i, 255
  %idxprom.i = zext nneg i32 %and3 to i64
  %arrayidx.i = getelementptr inbounds nuw [256 x i8], ptr @outsides, i64 %idxprom.i
  %arrayidx1.i = getelementptr inbounds nuw i8, ptr %arrayidx.i, i64 %and.i
  %1 = load i8, ptr %arrayidx1.i, align 1
  %arrayidx3.i = getelementptr inbounds nuw [256 x i8], ptr @insides, i64 %idxprom.i
  %shr5.i = lshr i64 %mover, %sh_prom.i
  %conv6.i = zext i8 %1 to i64
  %and7.i = and i64 %shr5.i, %conv6.i
  %arrayidx8.i = getelementptr inbounds nuw i8, ptr %arrayidx3.i, i64 %and7.i
  %2 = load i8, ptr %arrayidx8.i, align 1
  %idxprom6 = zext i8 %2 to i64
  %arrayidx7 = getelementptr inbounds nuw [8 x i8], ptr %arrayidx5, i64 %idxprom6
  %3 = load i64, ptr %arrayidx7, align 8
  %d9b = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 48
  %4 = load i32, ptr %d9b, align 8
  %idxprom8 = zext i32 %4 to i64
  %arrayidx9 = getelementptr inbounds nuw [2048 x i8], ptr @d9Flips, i64 %idxprom8
  %5 = load i64, ptr %arrayidx2, align 8
  %d9mult = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 8
  %6 = load i64, ptr %d9mult, align 8
  %and.i52 = and i64 %5, %enemy
  %mul.i = mul i64 %and.i52, %6
  %shr.i53 = lshr i64 %mul.i, 56
  %arrayidx1.i56 = getelementptr inbounds nuw i8, ptr %arrayidx.i, i64 %shr.i53
  %7 = load i8, ptr %arrayidx1.i56, align 1
  %and2.i = and i64 %5, %mover
  %mul3.i = mul i64 %and2.i, %6
  %shr4.i = lshr i64 %mul3.i, 56
  %conv7.i = zext i8 %7 to i64
  %and8.i = and i64 %shr4.i, %conv7.i
  %arrayidx9.i = getelementptr inbounds nuw i8, ptr %arrayidx3.i, i64 %and8.i
  %8 = load i8, ptr %arrayidx9.i, align 1
  %idxprom11 = zext i8 %8 to i64
  %arrayidx12 = getelementptr inbounds nuw [8 x i8], ptr %arrayidx9, i64 %idxprom11
  %9 = load i64, ptr %arrayidx12, align 8
  %or13 = or i64 %9, %3
  %arrayidx15 = getelementptr inbounds nuw [2048 x i8], ptr @colFlips, i64 %idxprom.i
  %colmask = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 16
  %10 = load i64, ptr %colmask, align 8
  %colmult = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 24
  %11 = load i64, ptr %colmult, align 8
  %and.i57 = and i64 %10, %enemy
  %mul.i58 = mul i64 %and.i57, %11
  %shr.i59 = lshr i64 %mul.i58, 56
  %arrayidx.i61 = getelementptr inbounds [256 x i8], ptr @outsides, i64 %idxprom4
  %arrayidx1.i62 = getelementptr inbounds nuw i8, ptr %arrayidx.i61, i64 %shr.i59
  %12 = load i8, ptr %arrayidx1.i62, align 1
  %and2.i63 = and i64 %10, %mover
  %mul3.i64 = mul i64 %and2.i63, %11
  %shr4.i65 = lshr i64 %mul3.i64, 56
  %arrayidx6.i66 = getelementptr inbounds [256 x i8], ptr @insides, i64 %idxprom4
  %conv7.i67 = zext i8 %12 to i64
  %and8.i68 = and i64 %shr4.i65, %conv7.i67
  %arrayidx9.i69 = getelementptr inbounds nuw i8, ptr %arrayidx6.i66, i64 %and8.i68
  %13 = load i8, ptr %arrayidx9.i69, align 1
  %idxprom17 = zext i8 %13 to i64
  %arrayidx18 = getelementptr inbounds nuw [8 x i8], ptr %arrayidx15, i64 %idxprom17
  %14 = load i64, ptr %arrayidx18, align 8
  %or19 = or i64 %or13, %14
  %d7b = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 52
  %15 = load i32, ptr %d7b, align 4
  %idxprom20 = zext i32 %15 to i64
  %arrayidx21 = getelementptr inbounds nuw [2048 x i8], ptr @d7Flips, i64 %idxprom20
  %d7mask = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 32
  %16 = load i64, ptr %d7mask, align 8
  %d7mult = getelementptr inbounds nuw i8, ptr %arrayidx2, i64 40
  %17 = load i64, ptr %d7mult, align 8
  %and.i71 = and i64 %16, %enemy
  %mul.i72 = mul i64 %and.i71, %17
  %shr.i73 = lshr i64 %mul.i72, 56
  %arrayidx1.i76 = getelementptr inbounds nuw i8, ptr %arrayidx.i, i64 %shr.i73
  %18 = load i8, ptr %arrayidx1.i76, align 1
  %and2.i77 = and i64 %16, %mover
  %mul3.i78 = mul i64 %and2.i77, %17
  %shr4.i79 = lshr i64 %mul3.i78, 56
  %conv7.i81 = zext i8 %18 to i64
  %and8.i82 = and i64 %shr4.i79, %conv7.i81
  %arrayidx9.i83 = getelementptr inbounds nuw i8, ptr %arrayidx3.i, i64 %and8.i82
  %19 = load i8, ptr %arrayidx9.i83, align 1
  %idxprom23 = zext i8 %19 to i64
  %arrayidx24 = getelementptr inbounds nuw [8 x i8], ptr %arrayidx21, i64 %idxprom23
  %20 = load i64, ptr %arrayidx24, align 8
  %or25 = or i64 %or19, %20
  br label %return

return:                                           ; preds = %if.then, %entry
  %retval.0 = phi i64 [ %or25, %if.then ], [ 0, %entry ]
  ret i64 %retval.0
}
