; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=OLD
; RUN: llc -mtriple=riscv64 -enable-new-shrink-wrap -verify-machineinstrs \
; RUN:   -verify-cfiinstrs < %s | FileCheck %s --check-prefix=NEW

; Tests for the GCC-style NewShrinkWrap pass, compared to ShrinkWrap.

declare i32 @f(i32)
declare void @g()
declare void @abort() noreturn nounwind

; Early exit: both passes shrink-wrap.
define i32 @early_exit(i32 %x) {
; OLD-LABEL: early_exit:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB0_2
; OLD-NEXT:  # %bb.1: # %work
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    call f
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB0_2:
; OLD-NEXT:    li a0, 0
; OLD-NEXT:    ret
;
; NEW-LABEL: early_exit:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB0_2
; NEW-NEXT:  # %bb.1: # %work
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB0_2:
; NEW-NEXT:    li a0, 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %ret, label %work
work:
  %r = call i32 @f(i32 %x)
  br label %ret
ret:
  %p = phi i32 [0, %entry], [%r, %work]
  ret i32 %p
}

; GCC's loop example: the loop header needs no frame and has an exit. The new
; pass duplicates the header and the exit block, so that the path leaving the
; loop on the first iteration runs without the frame.
define void @loop_exit() {
; OLD-LABEL: loop_exit:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    lw a0, 16(zero)
; OLD-NEXT:    beqz a0, .LBB1_2
; OLD-NEXT:  .LBB1_1: # %body
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    call g
; OLD-NEXT:    lw a0, 16(zero)
; OLD-NEXT:    bnez a0, .LBB1_1
; OLD-NEXT:  .LBB1_2: # %exit
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: loop_exit:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    beqz a0, .LBB1_4
; NEW-NEXT:  # %bb.1: # %body
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call g
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    beqz a0, .LBB1_3
; NEW-NEXT:  .LBB1_2: # %body
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    call g
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    bnez a0, .LBB1_2
; NEW-NEXT:  .LBB1_3: # %exit
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:  .LBB1_4: # %exit
; NEW-NEXT:    ret
entry:
  br label %header
header:
  %v = load volatile i32, ptr inttoptr (i64 16 to ptr)
  %c = icmp eq i32 %v, 0
  br i1 %c, label %exit, label %body
body:
  call void @g()
  br label %header
exit:
  ret void
}

; All paths need the frame, but s0/s1/s2 are only used on one path. Separate
; shrink-wrapping saves and restores them only there.
define i32 @separate(i32 %x, i32 %y) {
; OLD-LABEL: separate:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB2_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call f
; OLD-NEXT:    add s0, s2, s0
; OLD-NEXT:    addw a0, s0, a0
; OLD-NEXT:    j .LBB2_3
; OLD-NEXT:  .LBB2_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB2_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB2_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call f
; NEW-NEXT:    add s0, s2, s0
; NEW-NEXT:    addw a0, s0, a0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    j .LBB2_3
; NEW-NEXT:  .LBB2_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:  .LBB2_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %r4 = call i32 @f(i32 %r2)
  %s = add i32 %r3, %r4
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; The registers used in the loop are saved before it, not in it.
define i32 @separate_loop(i32 %n, i32 %x) {
; OLD-LABEL: separate_loop:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    sext.w a1, a1
; OLD-NEXT:    beqz a1, .LBB3_4
; OLD-NEXT:  # %bb.1: # %preheader
; OLD-NEXT:    li s1, 0
; OLD-NEXT:    li s0, 0
; OLD-NEXT:    sext.w s2, a0
; OLD-NEXT:  .LBB3_2: # %loop
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call f
; OLD-NEXT:    addiw s1, s1, 1
; OLD-NEXT:    addw s0, s0, a0
; OLD-NEXT:    bne s2, s1, .LBB3_2
; OLD-NEXT:  # %bb.3: # %exit
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    j .LBB3_5
; OLD-NEXT:  .LBB3_4: # %fast
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB3_5: # %exit
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_loop:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a1, a1
; NEW-NEXT:    beqz a1, .LBB3_4
; NEW-NEXT:  # %bb.1: # %preheader
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    li s1, 0
; NEW-NEXT:    li s0, 0
; NEW-NEXT:    sext.w s2, a0
; NEW-NEXT:  .LBB3_2: # %loop
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call f
; NEW-NEXT:    addiw s1, s1, 1
; NEW-NEXT:    addw s0, s0, a0
; NEW-NEXT:    bne s2, s1, .LBB3_2
; NEW-NEXT:  # %bb.3: # %exit
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB3_4: # %fast
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %fast, label %preheader
fast:
  %r0 = call i32 @f(i32 %n)
  ret i32 %r0
preheader:
  br label %loop
loop:
  %i = phi i32 [0, %preheader], [%inc, %loop]
  %acc = phi i32 [0, %preheader], [%acc2, %loop]
  %r = call i32 @f(i32 %i)
  %acc2 = add i32 %acc, %r
  %inc = add i32 %i, 1
  %done = icmp eq i32 %inc, %n
  br i1 %done, label %exit, label %loop
exit:
  ret i32 %acc2
}

; Blocks without successors that are not returns need all registers saved.
define i32 @separate_noreturn(i32 %x, i32 %y) {
; OLD-LABEL: separate_noreturn:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_remember_state
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB4_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    add a0, s1, a0
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB4_3
; OLD-NEXT:  .LBB4_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB4_4
; OLD-NEXT:  .LBB4_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB4_4: # %fail
; OLD-NEXT:    .cfi_restore_state
; OLD-NEXT:    call abort
;
; NEW-LABEL: separate_noreturn:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB4_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    add a0, s1, a0
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    j .LBB4_3
; NEW-NEXT:  .LBB4_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB4_4
; NEW-NEXT:  .LBB4_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB4_4: # %fail
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    call abort
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  %c2 = icmp eq i32 %r1, 0
  br i1 %c2, label %fail, label %ret
fail:
  call void @abort()
  unreachable
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %s = add i32 %r2, %r3
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; s0 is restored on the edge p -> s1, which is split: s1 is also reached
; without s0 saved, and s2 needs s0.
define i32 @separate_split_edge(i32 %x, i32 %y) {
; OLD-LABEL: separate_split_edge:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    beqz a2, .LBB5_3
; OLD-NEXT:  # %bb.1: # %p
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    call f
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB5_3
; OLD-NEXT:  # %bb.2: # %s2
; OLD-NEXT:    call f
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB5_4
; OLD-NEXT:  .LBB5_3: # %s1
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB5_4: # %s1
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_split_edge:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    beqz a2, .LBB5_4
; NEW-NEXT:  # %bb.1: # %p
; NEW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    call f
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB5_3
; NEW-NEXT:  # %bb.2: # %s2
; NEW-NEXT:    call f
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB5_3:
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:  .LBB5_4: # %s1
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %s1, label %p
p:
  %r = call i32 @f(i32 %x)
  %c2 = icmp eq i32 %r, 0
  br i1 %c2, label %s1, label %s2
s1:
  %v = phi i32 [%x, %entry], [%r, %p]
  %r1 = call i32 @f(i32 %v)
  ret i32 %r1
s2:
  %r2 = call i32 @f(i32 %r)
  %s = add i32 %r2, %y
  ret i32 %s
}

; Floating-point callee-saved registers are wrapped separately too.
declare double @fd(double)
define double @separate_fpr(i32 %x, double %y) "target-features"="+d" {
; OLD-LABEL: separate_fpr:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    fsd fs0, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset fs0, -16
; OLD-NEXT:    sext.w a0, a0
; OLD-NEXT:    beqz a0, .LBB6_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    fmv.d fs0, fa0
; OLD-NEXT:    call fd
; OLD-NEXT:    call fd
; OLD-NEXT:    fadd.d fa0, fa0, fs0
; OLD-NEXT:    j .LBB6_3
; OLD-NEXT:  .LBB6_2: # %a
; OLD-NEXT:    call fd
; OLD-NEXT:  .LBB6_3: # %a
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    fld fs0, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore fs0
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_fpr:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a0, a0
; NEW-NEXT:    beqz a0, .LBB6_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    fsd fs0, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset fs0, -16
; NEW-NEXT:    fmv.d fs0, fa0
; NEW-NEXT:    call fd
; NEW-NEXT:    call fd
; NEW-NEXT:    fadd.d fa0, fa0, fs0
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    fld fs0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore fs0
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB6_2: # %a
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call fd
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call double @fd(double %y)
  ret double %r1
b:
  %r2 = call double @fd(double %y)
  %r3 = call double @fd(double %r2)
  %s = fadd double %r3, %y
  ret double %s
}

; No separate shrink-wrapping when optimizing for size.
define i32 @separate_optsize(i32 %x, i32 %y) optsize {
; OLD-LABEL: separate_optsize:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB7_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    add a0, s1, a0
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB7_3
; OLD-NEXT:  .LBB7_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB7_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_optsize:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB7_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    add a0, s1, a0
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    j .LBB7_3
; NEW-NEXT:  .LBB7_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:  .LBB7_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %s = add i32 %r2, %r3
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}
