; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=OLD
; RUN: llc -mtriple=riscv64 -mattr=+m -enable-new-shrink-wrap \
; RUN:   -verify-machineinstrs -verify-cfiinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=NEW
; RUN: llc -mtriple=riscv64 -mattr=+m -enable-new-shrink-wrap \
; RUN:   -regalloc-csr-first-time-cost=32768 -verify-machineinstrs \
; RUN:   -verify-cfiinstrs < %s | FileCheck %s --check-prefix=NEW-RA

; Shrink-wrapping patterns that GCC handles and the ShrinkWrap pass does not,
; extracted from instruction profiles of RISC-V workloads (omnetpp, CPython,
; gem5, SEAL, Stockfish, cppcheck) built with GCC 15 and clang 22. Each
; function reproduces the shape of a hot function of these workloads (named
; below); the C/C++ sources were compiled with "clang -O2".
;
; Check prefixes:
; - OLD is ShrinkWrap.
; - NEW is NewShrinkWrap (-enable-new-shrink-wrap).
; - NEW-RA is NewShrinkWrap with a cost for the first use of a callee-saved
;   register in the register allocator (RISC-V uses 0; this is about
;   AArch64's), so that values live across cold calls are not put in
;   callee-saved registers in the entry block.
;
; Callee-saved saves+restores executed per call, measured with a driver that
; takes the cold paths once every 100 calls. The last column is what GCC 15
; executes per call in the hot function of the workload this pattern comes
; from, with/without shrink-wrapping:
;
;   function                   OLD    NEW   NEW-RA   GCC 15 in the workload
;   drop (C)                   0.04   0.04  0.04     -
;   _ZN7cObject4drop... (C++)  9.95   9.95  9.95     0 / 8 (frame on throw only)
;   new_reference              4.00   4.00  0.02     0 / 2
;   is_ready                   6.00   4.67  0.20     0 / 2
;   dot                        20.0   6.12  5.14     8 / 26
;   legal                      16.0   6.10  4.12     2.3 / 12
;   multi_compare              16.0   10.0  0.01     0.5 / 8
;   pool_get                   10.0   6.67  6.00     0 / 6 (no frame on early exits)

; ModuleID = 'ir/clean.ll'
source_filename = "ir/clean.ll"

%"class.std::__cxx11::basic_string" = type { %"struct.std::__cxx11::basic_string<char>::_Alloc_hider", i64, %union.anon }
%"struct.std::__cxx11::basic_string<char>::_Alloc_hider" = type { ptr }
%union.anon = type { i64, [8 x i8] }

$_ZTI13cRuntimeError = comdat any

$_ZTS13cRuntimeError = comdat any

@.str = private unnamed_addr constant [24 x i8] c"(%s)%s: not owner of %s\00", align 1
@default_owner = external dso_local local_unnamed_addr global ptr, align 8
@.str.1 = private unnamed_addr constant [35 x i8] c"drop(): not owner of object (%s)%s\00", align 1
@_ZTI13cRuntimeError = linkonce_odr dso_local constant { ptr, ptr } { ptr getelementptr inbounds (i8, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 16), ptr @_ZTS13cRuntimeError }, comdat, align 8
@_ZTVN10__cxxabiv117__class_type_infoE = external dso_local global [0 x ptr]
@_ZTS13cRuntimeError = linkonce_odr dso_local constant [16 x i8] c"13cRuntimeError\00", comdat, align 1
@defaultOwner = external dso_local local_unnamed_addr global ptr, align 8
@tracing = external dso_local local_unnamed_addr global i32, align 4
@.str.2 = private unnamed_addr constant [1 x i8] zeroinitializer, align 1

; Function Attrs: noinline nounwind
; Pattern A (C): the hot path is a check and a tail call, the cold path calls
; a noreturn function. ShrinkWrap already handles it: the restore point is the
; single noreturn block, which needs no epilogue.
define dso_local void @drop(ptr noundef %self, ptr noundef %o) local_unnamed_addr #0 {
; OLD-LABEL: drop:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    ld a2, 0(a1)
; OLD-NEXT:    bne a2, a0, .LBB0_2
; OLD-NEXT:  # %bb.1: # %if.end
; OLD-NEXT:    lui a0, %hi(default_owner)
; OLD-NEXT:    ld a0, %lo(default_owner)(a0)
; OLD-NEXT:    tail do_insert
; OLD-NEXT:  .LBB0_2: # %if.then
; OLD-NEXT:    addi sp, sp, -96
; OLD-NEXT:    sd ra, 88(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 80(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 72(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 64(sp) # 8-byte Folded Spill
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    mv s1, a1
; OLD-NEXT:    call class_name
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a1, sp
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call describe
; OLD-NEXT:    ld a3, 8(s1)
; OLD-NEXT:    lui a1, %hi(.L.str)
; OLD-NEXT:    addi a1, a1, %lo(.L.str)
; OLD-NEXT:    mv a4, sp
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    mv a2, s2
; OLD-NEXT:    call runtime_error
;
; NEW-LABEL: drop:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    ld a2, 0(a1)
; NEW-NEXT:    bne a2, a0, .LBB0_2
; NEW-NEXT:  # %bb.1: # %if.end
; NEW-NEXT:    lui a0, %hi(default_owner)
; NEW-NEXT:    ld a0, %lo(default_owner)(a0)
; NEW-NEXT:    tail do_insert
; NEW-NEXT:  .LBB0_2: # %if.then
; NEW-NEXT:    addi sp, sp, -96
; NEW-NEXT:    sd ra, 88(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 80(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 72(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 64(sp) # 8-byte Folded Spill
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    mv s1, a1
; NEW-NEXT:    call class_name
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a1, sp
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call describe
; NEW-NEXT:    ld a3, 8(s1)
; NEW-NEXT:    lui a1, %hi(.L.str)
; NEW-NEXT:    addi a1, a1, %lo(.L.str)
; NEW-NEXT:    mv a4, sp
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    mv a2, s2
; NEW-NEXT:    call runtime_error
;
; NEW-RA-LABEL: drop:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    ld a2, 0(a1)
; NEW-RA-NEXT:    bne a2, a0, .LBB0_2
; NEW-RA-NEXT:  # %bb.1: # %if.end
; NEW-RA-NEXT:    lui a0, %hi(default_owner)
; NEW-RA-NEXT:    ld a0, %lo(default_owner)(a0)
; NEW-RA-NEXT:    tail do_insert
; NEW-RA-NEXT:  .LBB0_2: # %if.then
; NEW-RA-NEXT:    addi sp, sp, -96
; NEW-RA-NEXT:    sd ra, 88(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s0, 80(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s1, 72(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s2, 64(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    mv a0, a1
; NEW-RA-NEXT:    mv s1, a1
; NEW-RA-NEXT:    call class_name
; NEW-RA-NEXT:    mv s2, a0
; NEW-RA-NEXT:    mv a1, sp
; NEW-RA-NEXT:    mv a0, s1
; NEW-RA-NEXT:    call describe
; NEW-RA-NEXT:    ld a3, 8(s1)
; NEW-RA-NEXT:    lui a1, %hi(.L.str)
; NEW-RA-NEXT:    addi a1, a1, %lo(.L.str)
; NEW-RA-NEXT:    mv a4, sp
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    mv a2, s2
; NEW-RA-NEXT:    call runtime_error
entry:
  %buf = alloca [64 x i8], align 1
  %0 = load ptr, ptr %o, align 8
  %cmp.not = icmp eq ptr %0, %self
  br i1 %cmp.not, label %if.end, label %if.then, !prof !0

if.then:                                          ; preds = %entry
  call void @llvm.lifetime.start.p0(ptr nonnull %buf) #7
  %call = tail call ptr @class_name(ptr noundef nonnull %o) #7
  call void @describe(ptr noundef nonnull %o, ptr noundef nonnull %buf) #7
  %name = getelementptr inbounds nuw i8, ptr %o, i64 8
  %1 = load ptr, ptr %name, align 8
  call void (ptr, ptr, ...) @runtime_error(ptr noundef %self, ptr noundef nonnull @.str, ptr noundef %call, ptr noundef %1, ptr noundef nonnull %buf) #8
  unreachable

if.end:                                           ; preds = %entry
  %2 = load ptr, ptr @default_owner, align 8
  tail call void @do_insert(ptr noundef %2, ptr noundef nonnull %o) #7
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(ptr captures(none)) #1

declare dso_local ptr @class_name(ptr noundef) local_unnamed_addr

declare dso_local void @describe(ptr noundef, ptr noundef) local_unnamed_addr

; Function Attrs: noreturn
declare dso_local void @runtime_error(ptr noundef, ptr noundef, ...) local_unnamed_addr #2

declare dso_local void @do_insert(ptr noundef, ptr noundef) local_unnamed_addr

; Function Attrs: mustprogress noinline
; Pattern A (C++), from omnetpp::cObject::drop: the cold path builds a
; std::string and throws, so it has landing pads and several blocks without
; successors. GCC sets up the frame on the throw path only.
; FIXME: Neither pass shrink-wraps it: there is no common post-dominator of the
; blocks needing the frame to place the (never executed) epilogue in.
define dso_local void @_ZN7cObject4dropEP12cOwnedObject(ptr noundef nonnull align 1 dereferenceable(1) %this, ptr noundef %obj) local_unnamed_addr #3 align 2 personality ptr @__gxx_personality_v0 {
; OLD-LABEL: _ZN7cObject4dropEP12cOwnedObject:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -80
; OLD-NEXT:    .cfi_def_cfa_offset 80
; OLD-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    .cfi_offset s3, -40
; OLD-NEXT:    .cfi_remember_state
; OLD-NEXT:    ld a2, 8(a1)
; OLD-NEXT:    bne a2, a0, .LBB1_2
; OLD-NEXT:  # %bb.1: # %if.end
; OLD-NEXT:    lui a0, %hi(defaultOwner)
; OLD-NEXT:    ld a0, %lo(defaultOwner)(a0)
; OLD-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    .cfi_restore s3
; OLD-NEXT:    addi sp, sp, 80
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    tail _ZN10cSoftOwner8doInsertEP12cOwnedObject
; OLD-NEXT:  .LBB1_2: # %if.then
; OLD-NEXT:    .cfi_restore_state
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    li a0, 200
; OLD-NEXT:    mv s2, a1
; OLD-NEXT:    call __cxa_allocate_exception
; OLD-NEXT:    ld a1, 0(s2)
; OLD-NEXT:    ld a1, 16(a1)
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:  .Ltmp0: # EH_LABEL
; OLD-NEXT:    mv s3, s2
; OLD-NEXT:    mv a0, s2
; OLD-NEXT:    jalr a1
; OLD-NEXT:  .Ltmp1: # EH_LABEL
; OLD-NEXT:  # %bb.3: # %invoke.cont
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a1, s3
; OLD-NEXT:    ld a0, 0(s3)
; OLD-NEXT:    ld a2, 24(a0)
; OLD-NEXT:  .Ltmp3: # EH_LABEL
; OLD-NEXT:    addi a0, sp, 8
; OLD-NEXT:    jalr a2
; OLD-NEXT:  .Ltmp4: # EH_LABEL
; OLD-NEXT:  # %bb.4: # %invoke.cont5
; OLD-NEXT:    ld a4, 8(sp)
; OLD-NEXT:    li s3, 1
; OLD-NEXT:  .Ltmp6: # EH_LABEL
; OLD-NEXT:    lui a2, %hi(.L.str.1)
; OLD-NEXT:    addi a2, a2, %lo(.L.str.1)
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    mv a1, s1
; OLD-NEXT:    mv a3, s2
; OLD-NEXT:    call _ZN13cRuntimeErrorC1EPKvPKcz
; OLD-NEXT:  .Ltmp7: # EH_LABEL
; OLD-NEXT:  # %bb.5: # %invoke.cont8
; OLD-NEXT:  .Ltmp8: # EH_LABEL
; OLD-NEXT:    lui a1, %hi(_ZTI13cRuntimeError)
; OLD-NEXT:    addi a1, a1, %lo(_ZTI13cRuntimeError)
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    li a2, 0
; OLD-NEXT:    li s3, 0
; OLD-NEXT:    call __cxa_throw
; OLD-NEXT:  .Ltmp9: # EH_LABEL
; OLD-NEXT:  # %bb.6: # %unreachable
; OLD-NEXT:  .LBB1_7: # %lpad7
; OLD-NEXT:  .Ltmp10: # EH_LABEL
; OLD-NEXT:    ld a2, 8(sp)
; OLD-NEXT:    addi a1, sp, 24
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    bne a2, a1, .LBB1_9
; OLD-NEXT:  # %bb.8: # %ehcleanup9
; OLD-NEXT:    bnez s3, .LBB1_14
; OLD-NEXT:    j .LBB1_10
; OLD-NEXT:  .LBB1_9: # %if.then.i.i
; OLD-NEXT:    ld a1, 24(sp)
; OLD-NEXT:    addi a1, a1, 1
; OLD-NEXT:    mv a0, a2
; OLD-NEXT:    call _ZdlPvm
; OLD-NEXT:    bnez s3, .LBB1_14
; OLD-NEXT:  .LBB1_10: # %eh.resume
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call _Unwind_Resume
; OLD-NEXT:  .LBB1_11: # %ehcleanup9.thread20
; OLD-NEXT:  .Ltmp5: # EH_LABEL
; OLD-NEXT:    j .LBB1_13
; OLD-NEXT:  .LBB1_12: # %ehcleanup9.thread
; OLD-NEXT:  .Ltmp2: # EH_LABEL
; OLD-NEXT:  .LBB1_13: # %cleanup.action
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:  .LBB1_14: # %cleanup.action
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call __cxa_free_exception
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call _Unwind_Resume
;
; NEW-LABEL: _ZN7cObject4dropEP12cOwnedObject:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -80
; NEW-NEXT:    .cfi_def_cfa_offset 80
; NEW-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    .cfi_offset s3, -40
; NEW-NEXT:    .cfi_remember_state
; NEW-NEXT:    ld a2, 8(a1)
; NEW-NEXT:    bne a2, a0, .LBB1_2
; NEW-NEXT:  # %bb.1: # %if.end
; NEW-NEXT:    lui a0, %hi(defaultOwner)
; NEW-NEXT:    ld a0, %lo(defaultOwner)(a0)
; NEW-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    .cfi_restore s3
; NEW-NEXT:    addi sp, sp, 80
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    tail _ZN10cSoftOwner8doInsertEP12cOwnedObject
; NEW-NEXT:  .LBB1_2: # %if.then
; NEW-NEXT:    .cfi_restore_state
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    li a0, 200
; NEW-NEXT:    mv s2, a1
; NEW-NEXT:    call __cxa_allocate_exception
; NEW-NEXT:    ld a1, 0(s2)
; NEW-NEXT:    ld a1, 16(a1)
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:  .Ltmp0: # EH_LABEL
; NEW-NEXT:    mv s3, s2
; NEW-NEXT:    mv a0, s2
; NEW-NEXT:    jalr a1
; NEW-NEXT:  .Ltmp1: # EH_LABEL
; NEW-NEXT:  # %bb.3: # %invoke.cont
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a1, s3
; NEW-NEXT:    ld a0, 0(s3)
; NEW-NEXT:    ld a2, 24(a0)
; NEW-NEXT:  .Ltmp3: # EH_LABEL
; NEW-NEXT:    addi a0, sp, 8
; NEW-NEXT:    jalr a2
; NEW-NEXT:  .Ltmp4: # EH_LABEL
; NEW-NEXT:  # %bb.4: # %invoke.cont5
; NEW-NEXT:    ld a4, 8(sp)
; NEW-NEXT:    li s3, 1
; NEW-NEXT:  .Ltmp6: # EH_LABEL
; NEW-NEXT:    lui a2, %hi(.L.str.1)
; NEW-NEXT:    addi a2, a2, %lo(.L.str.1)
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    mv a1, s1
; NEW-NEXT:    mv a3, s2
; NEW-NEXT:    call _ZN13cRuntimeErrorC1EPKvPKcz
; NEW-NEXT:  .Ltmp7: # EH_LABEL
; NEW-NEXT:  # %bb.5: # %invoke.cont8
; NEW-NEXT:  .Ltmp8: # EH_LABEL
; NEW-NEXT:    lui a1, %hi(_ZTI13cRuntimeError)
; NEW-NEXT:    addi a1, a1, %lo(_ZTI13cRuntimeError)
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    li a2, 0
; NEW-NEXT:    li s3, 0
; NEW-NEXT:    call __cxa_throw
; NEW-NEXT:  .Ltmp9: # EH_LABEL
; NEW-NEXT:  # %bb.6: # %unreachable
; NEW-NEXT:  .LBB1_7: # %lpad7
; NEW-NEXT:  .Ltmp10: # EH_LABEL
; NEW-NEXT:    ld a2, 8(sp)
; NEW-NEXT:    addi a1, sp, 24
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    bne a2, a1, .LBB1_9
; NEW-NEXT:  # %bb.8: # %ehcleanup9
; NEW-NEXT:    bnez s3, .LBB1_14
; NEW-NEXT:    j .LBB1_10
; NEW-NEXT:  .LBB1_9: # %if.then.i.i
; NEW-NEXT:    ld a1, 24(sp)
; NEW-NEXT:    addi a1, a1, 1
; NEW-NEXT:    mv a0, a2
; NEW-NEXT:    call _ZdlPvm
; NEW-NEXT:    bnez s3, .LBB1_14
; NEW-NEXT:  .LBB1_10: # %eh.resume
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call _Unwind_Resume
; NEW-NEXT:  .LBB1_11: # %ehcleanup9.thread20
; NEW-NEXT:  .Ltmp5: # EH_LABEL
; NEW-NEXT:    j .LBB1_13
; NEW-NEXT:  .LBB1_12: # %ehcleanup9.thread
; NEW-NEXT:  .Ltmp2: # EH_LABEL
; NEW-NEXT:  .LBB1_13: # %cleanup.action
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:  .LBB1_14: # %cleanup.action
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call __cxa_free_exception
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call _Unwind_Resume
;
; NEW-RA-LABEL: _ZN7cObject4dropEP12cOwnedObject:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    addi sp, sp, -80
; NEW-RA-NEXT:    .cfi_def_cfa_offset 80
; NEW-RA-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    .cfi_offset ra, -8
; NEW-RA-NEXT:    .cfi_offset s0, -16
; NEW-RA-NEXT:    .cfi_offset s1, -24
; NEW-RA-NEXT:    .cfi_offset s2, -32
; NEW-RA-NEXT:    .cfi_offset s3, -40
; NEW-RA-NEXT:    .cfi_remember_state
; NEW-RA-NEXT:    ld a2, 8(a1)
; NEW-RA-NEXT:    bne a2, a0, .LBB1_2
; NEW-RA-NEXT:  # %bb.1: # %if.end
; NEW-RA-NEXT:    lui a0, %hi(defaultOwner)
; NEW-RA-NEXT:    ld a0, %lo(defaultOwner)(a0)
; NEW-RA-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    .cfi_restore ra
; NEW-RA-NEXT:    .cfi_restore s0
; NEW-RA-NEXT:    .cfi_restore s1
; NEW-RA-NEXT:    .cfi_restore s2
; NEW-RA-NEXT:    .cfi_restore s3
; NEW-RA-NEXT:    addi sp, sp, 80
; NEW-RA-NEXT:    .cfi_def_cfa_offset 0
; NEW-RA-NEXT:    tail _ZN10cSoftOwner8doInsertEP12cOwnedObject
; NEW-RA-NEXT:  .LBB1_2: # %if.then
; NEW-RA-NEXT:    .cfi_restore_state
; NEW-RA-NEXT:    mv s1, a0
; NEW-RA-NEXT:    li a0, 200
; NEW-RA-NEXT:    mv s2, a1
; NEW-RA-NEXT:    call __cxa_allocate_exception
; NEW-RA-NEXT:    ld a1, 0(s2)
; NEW-RA-NEXT:    ld a1, 16(a1)
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:  .Ltmp0: # EH_LABEL
; NEW-RA-NEXT:    mv s3, s2
; NEW-RA-NEXT:    mv a0, s2
; NEW-RA-NEXT:    jalr a1
; NEW-RA-NEXT:  .Ltmp1: # EH_LABEL
; NEW-RA-NEXT:  # %bb.3: # %invoke.cont
; NEW-RA-NEXT:    mv s2, a0
; NEW-RA-NEXT:    mv a1, s3
; NEW-RA-NEXT:    ld a0, 0(s3)
; NEW-RA-NEXT:    ld a2, 24(a0)
; NEW-RA-NEXT:  .Ltmp3: # EH_LABEL
; NEW-RA-NEXT:    addi a0, sp, 8
; NEW-RA-NEXT:    jalr a2
; NEW-RA-NEXT:  .Ltmp4: # EH_LABEL
; NEW-RA-NEXT:  # %bb.4: # %invoke.cont5
; NEW-RA-NEXT:    ld a4, 8(sp)
; NEW-RA-NEXT:    li s3, 1
; NEW-RA-NEXT:  .Ltmp6: # EH_LABEL
; NEW-RA-NEXT:    lui a2, %hi(.L.str.1)
; NEW-RA-NEXT:    addi a2, a2, %lo(.L.str.1)
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    mv a1, s1
; NEW-RA-NEXT:    mv a3, s2
; NEW-RA-NEXT:    call _ZN13cRuntimeErrorC1EPKvPKcz
; NEW-RA-NEXT:  .Ltmp7: # EH_LABEL
; NEW-RA-NEXT:  # %bb.5: # %invoke.cont8
; NEW-RA-NEXT:  .Ltmp8: # EH_LABEL
; NEW-RA-NEXT:    lui a1, %hi(_ZTI13cRuntimeError)
; NEW-RA-NEXT:    addi a1, a1, %lo(_ZTI13cRuntimeError)
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    li a2, 0
; NEW-RA-NEXT:    li s3, 0
; NEW-RA-NEXT:    call __cxa_throw
; NEW-RA-NEXT:  .Ltmp9: # EH_LABEL
; NEW-RA-NEXT:  # %bb.6: # %unreachable
; NEW-RA-NEXT:  .LBB1_7: # %lpad7
; NEW-RA-NEXT:  .Ltmp10: # EH_LABEL
; NEW-RA-NEXT:    ld a2, 8(sp)
; NEW-RA-NEXT:    addi a1, sp, 24
; NEW-RA-NEXT:    mv s1, a0
; NEW-RA-NEXT:    bne a2, a1, .LBB1_9
; NEW-RA-NEXT:  # %bb.8: # %ehcleanup9
; NEW-RA-NEXT:    bnez s3, .LBB1_14
; NEW-RA-NEXT:    j .LBB1_10
; NEW-RA-NEXT:  .LBB1_9: # %if.then.i.i
; NEW-RA-NEXT:    ld a1, 24(sp)
; NEW-RA-NEXT:    addi a1, a1, 1
; NEW-RA-NEXT:    mv a0, a2
; NEW-RA-NEXT:    call _ZdlPvm
; NEW-RA-NEXT:    bnez s3, .LBB1_14
; NEW-RA-NEXT:  .LBB1_10: # %eh.resume
; NEW-RA-NEXT:    mv a0, s1
; NEW-RA-NEXT:    call _Unwind_Resume
; NEW-RA-NEXT:  .LBB1_11: # %ehcleanup9.thread20
; NEW-RA-NEXT:  .Ltmp5: # EH_LABEL
; NEW-RA-NEXT:    j .LBB1_13
; NEW-RA-NEXT:  .LBB1_12: # %ehcleanup9.thread
; NEW-RA-NEXT:  .Ltmp2: # EH_LABEL
; NEW-RA-NEXT:  .LBB1_13: # %cleanup.action
; NEW-RA-NEXT:    mv s1, a0
; NEW-RA-NEXT:  .LBB1_14: # %cleanup.action
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    call __cxa_free_exception
; NEW-RA-NEXT:    mv a0, s1
; NEW-RA-NEXT:    call _Unwind_Resume
entry:
  %ref.tmp = alloca %"class.std::__cxx11::basic_string", align 8
  %owner = getelementptr inbounds nuw i8, ptr %obj, i64 8
  %0 = load ptr, ptr %owner, align 8
  %cmp.not = icmp eq ptr %0, %this
  br i1 %cmp.not, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  %exception = tail call ptr @__cxa_allocate_exception(i64 200) #7
  %vtable = load ptr, ptr %obj, align 8
  %vfn = getelementptr inbounds nuw i8, ptr %vtable, i64 16
  %1 = load ptr, ptr %vfn, align 8
  %call = invoke noundef ptr %1(ptr noundef nonnull align 8 dereferenceable(16) %obj)
          to label %invoke.cont unwind label %ehcleanup9.thread

invoke.cont:                                      ; preds = %if.then
  call void @llvm.lifetime.start.p0(ptr nonnull %ref.tmp) #7
  %vtable2 = load ptr, ptr %obj, align 8
  %vfn3 = getelementptr inbounds nuw i8, ptr %vtable2, i64 24
  %2 = load ptr, ptr %vfn3, align 8
  invoke void %2(ptr dead_on_unwind nonnull writable sret(%"class.std::__cxx11::basic_string") align 8 %ref.tmp, ptr noundef nonnull align 8 dereferenceable(16) %obj)
          to label %invoke.cont5 unwind label %ehcleanup9.thread20

invoke.cont5:                                     ; preds = %invoke.cont
  %3 = load ptr, ptr %ref.tmp, align 8
  invoke void (ptr, ptr, ptr, ...) @_ZN13cRuntimeErrorC1EPKvPKcz(ptr noundef nonnull align 1 dereferenceable(200) %exception, ptr noundef nonnull %this, ptr noundef nonnull @.str.1, ptr noundef %call, ptr noundef %3)
          to label %invoke.cont8 unwind label %lpad7

invoke.cont8:                                     ; preds = %invoke.cont5
  invoke void @__cxa_throw(ptr nonnull %exception, ptr nonnull @_ZTI13cRuntimeError, ptr null) #2
          to label %unreachable unwind label %lpad7

ehcleanup9.thread:                                ; preds = %if.then
  %4 = landingpad { ptr, i32 }
          cleanup
  br label %cleanup.action

ehcleanup9.thread20:                              ; preds = %invoke.cont
  %5 = landingpad { ptr, i32 }
          cleanup
  call void @llvm.lifetime.end.p0(ptr nonnull %ref.tmp) #7
  br label %cleanup.action

lpad7:                                            ; preds = %invoke.cont8, %invoke.cont5
  %cleanup.isactive.0 = phi i1 [ false, %invoke.cont8 ], [ true, %invoke.cont5 ]
  %6 = landingpad { ptr, i32 }
          cleanup
  %7 = load ptr, ptr %ref.tmp, align 8
  %8 = getelementptr inbounds nuw i8, ptr %ref.tmp, i64 16
  %cmp.i.i.i = icmp eq ptr %7, %8
  br i1 %cmp.i.i.i, label %ehcleanup9, label %if.then.i.i

if.then.i.i:                                      ; preds = %lpad7
  %9 = load i64, ptr %8, align 8
  %add.i.i.i = add i64 %9, 1
  call void @_ZdlPvm(ptr noundef %7, i64 noundef %add.i.i.i) #7
  call void @llvm.lifetime.end.p0(ptr nonnull %ref.tmp) #7
  br i1 %cleanup.isactive.0, label %cleanup.action, label %eh.resume

ehcleanup9:                                       ; preds = %lpad7
  call void @llvm.lifetime.end.p0(ptr nonnull %ref.tmp) #7
  br i1 %cleanup.isactive.0, label %cleanup.action, label %eh.resume

cleanup.action:                                   ; preds = %ehcleanup9, %if.then.i.i, %ehcleanup9.thread20, %ehcleanup9.thread
  %.pn.pn19 = phi { ptr, i32 } [ %4, %ehcleanup9.thread ], [ %6, %ehcleanup9 ], [ %5, %ehcleanup9.thread20 ], [ %6, %if.then.i.i ]
  call void @__cxa_free_exception(ptr %exception) #7
  br label %eh.resume

if.end:                                           ; preds = %entry
  %10 = load ptr, ptr @defaultOwner, align 8
  tail call void @_ZN10cSoftOwner8doInsertEP12cOwnedObject(ptr noundef nonnull align 1 dereferenceable(1) %10, ptr noundef nonnull %obj)
  ret void

eh.resume:                                        ; preds = %cleanup.action, %ehcleanup9, %if.then.i.i
  %.pn.pn18 = phi { ptr, i32 } [ %6, %ehcleanup9 ], [ %.pn.pn19, %cleanup.action ], [ %6, %if.then.i.i ]
  resume { ptr, i32 } %.pn.pn18

unreachable:                                      ; preds = %invoke.cont8
  unreachable
}

declare dso_local i32 @__gxx_personality_v0(...)

declare dso_local ptr @__cxa_allocate_exception(i64) local_unnamed_addr

declare dso_local void @_ZN13cRuntimeErrorC1EPKvPKcz(ptr noundef nonnull align 1 dereferenceable(200), ptr noundef, ptr noundef, ...) unnamed_addr

; Function Attrs: cold noreturn
declare dso_local void @__cxa_throw(ptr, ptr, ptr) local_unnamed_addr #4

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(ptr captures(none)) #1

; Function Attrs: nobuiltin nounwind
declare dso_local void @_ZdlPvm(ptr noundef, i64 noundef) local_unnamed_addr #5

declare dso_local void @__cxa_free_exception(ptr) local_unnamed_addr

declare dso_local void @_ZN10cSoftOwner8doInsertEP12cOwnedObject(ptr noundef nonnull align 1 dereferenceable(1), ptr noundef) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern B, from CPython _Py_NewReference: the argument is live across a
; conditional, cold call. Without a cost for using callee-saved registers, the
; register allocator copies it to s0 in the entry block, which then needs the
; frame. With the cost (NEW-RA), it is kept in a0 and spilled around the call,
; and the prologue moves to the cold block.
define dso_local void @new_reference(ptr noundef %op) local_unnamed_addr #0 {
; OLD-LABEL: new_reference:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    lui a1, %hi(tracing)
; OLD-NEXT:    lw a1, %lo(tracing)(a1)
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    beqz a1, .LBB2_2
; OLD-NEXT:  # %bb.1: # %if.then
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call trace_new_reference
; OLD-NEXT:  .LBB2_2: # %if.end
; OLD-NEXT:    li a0, 1
; OLD-NEXT:    sd a0, 0(s0)
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    ret
;
; NEW-LABEL: new_reference:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    lui a1, %hi(tracing)
; NEW-NEXT:    lw a1, %lo(tracing)(a1)
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    beqz a1, .LBB2_2
; NEW-NEXT:  # %bb.1: # %if.then
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call trace_new_reference
; NEW-NEXT:  .LBB2_2: # %if.end
; NEW-NEXT:    li a0, 1
; NEW-NEXT:    sd a0, 0(s0)
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    ret
;
; NEW-RA-LABEL: new_reference:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    lui a1, %hi(tracing)
; NEW-RA-NEXT:    lw a1, %lo(tracing)(a1)
; NEW-RA-NEXT:    beqz a1, .LBB2_2
; NEW-RA-NEXT:  # %bb.1: # %if.then
; NEW-RA-NEXT:    addi sp, sp, -16
; NEW-RA-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd a0, 0(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a0, 0(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    call trace_new_reference
; NEW-RA-NEXT:    ld a0, 0(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 16
; NEW-RA-NEXT:  .LBB2_2: # %if.end
; NEW-RA-NEXT:    li a1, 1
; NEW-RA-NEXT:    sd a1, 0(a0)
; NEW-RA-NEXT:    ret
entry:
  %0 = load i32, ptr @tracing, align 4
  %tobool.not = icmp eq i32 %0, 0
  br i1 %tobool.not, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @trace_new_reference(ptr noundef %op) #7
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  store i64 1, ptr %op, align 8
  ret void
}

declare dso_local void @trace_new_reference(ptr noundef) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern B, from gem5 MessageBuffer::isReady: a value computed in the entry
; block is live across a cold call. Same as above.
define dso_local signext range(i32 0, 2) i32 @is_ready(ptr nofree noundef readonly captures(none) %b, i64 noundef %now) local_unnamed_addr #0 {
; OLD-LABEL: is_ready:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    lw a2, 232(a0)
; OLD-NEXT:    li s0, 1
; OLD-NEXT:    beqz a2, .LBB3_3
; OLD-NEXT:  # %bb.1: # %lor.lhs.false
; OLD-NEXT:    lw a3, 236(a0)
; OLD-NEXT:    bltu a3, a2, .LBB3_3
; OLD-NEXT:  # %bb.2: # %lor.rhs
; OLD-NEXT:    ld a2, 240(a0)
; OLD-NEXT:    sltu s0, a2, a1
; OLD-NEXT:  .LBB3_3: # %lor.end
; OLD-NEXT:    ld a2, 216(a0)
; OLD-NEXT:    ld a3, 224(a0)
; OLD-NEXT:    beq a2, a3, .LBB3_7
; OLD-NEXT:  # %bb.4: # %if.end
; OLD-NEXT:    ld a2, 16(a2)
; OLD-NEXT:    sltu s1, a1, a2
; OLD-NEXT:    or a1, s1, s0
; OLD-NEXT:    andi a1, a1, 1
; OLD-NEXT:    bnez a1, .LBB3_6
; OLD-NEXT:  # %bb.5: # %if.then9
; OLD-NEXT:    ld a0, 208(a0)
; OLD-NEXT:    li a1, 1
; OLD-NEXT:    call schedule_event
; OLD-NEXT:  .LBB3_6: # %if.end10
; OLD-NEXT:    xori a0, s1, 1
; OLD-NEXT:    and a0, s0, a0
; OLD-NEXT:    j .LBB3_8
; OLD-NEXT:  .LBB3_7:
; OLD-NEXT:    li a0, 0
; OLD-NEXT:  .LBB3_8: # %cleanup
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    ret
;
; NEW-LABEL: is_ready:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    lw a2, 232(a0)
; NEW-NEXT:    li s0, 1
; NEW-NEXT:    beqz a2, .LBB3_3
; NEW-NEXT:  # %bb.1: # %lor.lhs.false
; NEW-NEXT:    lw a3, 236(a0)
; NEW-NEXT:    bltu a3, a2, .LBB3_3
; NEW-NEXT:  # %bb.2: # %lor.rhs
; NEW-NEXT:    ld a2, 240(a0)
; NEW-NEXT:    sltu s0, a2, a1
; NEW-NEXT:  .LBB3_3: # %lor.end
; NEW-NEXT:    ld a2, 216(a0)
; NEW-NEXT:    ld a3, 224(a0)
; NEW-NEXT:    beq a2, a3, .LBB3_7
; NEW-NEXT:  # %bb.4: # %if.end
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld a2, 16(a2)
; NEW-NEXT:    sltu s1, a1, a2
; NEW-NEXT:    or a1, s1, s0
; NEW-NEXT:    andi a1, a1, 1
; NEW-NEXT:    bnez a1, .LBB3_6
; NEW-NEXT:  # %bb.5: # %if.then9
; NEW-NEXT:    ld a0, 208(a0)
; NEW-NEXT:    li a1, 1
; NEW-NEXT:    call schedule_event
; NEW-NEXT:  .LBB3_6: # %if.end10
; NEW-NEXT:    xori a0, s1, 1
; NEW-NEXT:    and a0, s0, a0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    j .LBB3_8
; NEW-NEXT:  .LBB3_7:
; NEW-NEXT:    li a0, 0
; NEW-NEXT:  .LBB3_8: # %cleanup
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    ret
;
; NEW-RA-LABEL: is_ready:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    lw a3, 232(a0)
; NEW-RA-NEXT:    li a2, 1
; NEW-RA-NEXT:    beqz a3, .LBB3_3
; NEW-RA-NEXT:  # %bb.1: # %lor.lhs.false
; NEW-RA-NEXT:    lw a4, 236(a0)
; NEW-RA-NEXT:    bltu a4, a3, .LBB3_3
; NEW-RA-NEXT:  # %bb.2: # %lor.rhs
; NEW-RA-NEXT:    ld a2, 240(a0)
; NEW-RA-NEXT:    sltu a2, a2, a1
; NEW-RA-NEXT:  .LBB3_3: # %lor.end
; NEW-RA-NEXT:    ld a3, 216(a0)
; NEW-RA-NEXT:    ld a4, 224(a0)
; NEW-RA-NEXT:    beq a3, a4, .LBB3_7
; NEW-RA-NEXT:  # %bb.4: # %if.end
; NEW-RA-NEXT:    ld a3, 16(a3)
; NEW-RA-NEXT:    sltu a1, a1, a3
; NEW-RA-NEXT:    or a3, a1, a2
; NEW-RA-NEXT:    andi a3, a3, 1
; NEW-RA-NEXT:    bnez a3, .LBB3_6
; NEW-RA-NEXT:  # %bb.5: # %if.then9
; NEW-RA-NEXT:    addi sp, sp, -32
; NEW-RA-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a0, 208(a0)
; NEW-RA-NEXT:    sd a1, 16(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    li a1, 1
; NEW-RA-NEXT:    sd a2, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    call schedule_event
; NEW-RA-NEXT:    ld a1, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld a2, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 32
; NEW-RA-NEXT:  .LBB3_6: # %if.end10
; NEW-RA-NEXT:    xori a0, a1, 1
; NEW-RA-NEXT:    and a0, a2, a0
; NEW-RA-NEXT:    ret
; NEW-RA-NEXT:  .LBB3_7:
; NEW-RA-NEXT:    li a0, 0
; NEW-RA-NEXT:    ret
entry:
  %a = getelementptr inbounds nuw i8, ptr %b, i64 232
  %0 = load i32, ptr %a, align 8
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %lor.end, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %entry
  %b1 = getelementptr inbounds nuw i8, ptr %b, i64 236
  %1 = load i32, ptr %b1, align 4
  %cmp3 = icmp ult i32 %1, %0
  br i1 %cmp3, label %lor.end, label %lor.rhs

lor.rhs:                                          ; preds = %lor.lhs.false
  %t = getelementptr inbounds nuw i8, ptr %b, i64 240
  %2 = load i64, ptr %t, align 8
  %cmp4 = icmp ult i64 %2, %now
  br label %lor.end

lor.end:                                          ; preds = %lor.rhs, %lor.lhs.false, %entry
  %3 = phi i1 [ true, %lor.lhs.false ], [ true, %entry ], [ %cmp4, %lor.rhs ]
  %head = getelementptr inbounds nuw i8, ptr %b, i64 216
  %4 = load ptr, ptr %head, align 8
  %tail = getelementptr inbounds nuw i8, ptr %b, i64 224
  %5 = load ptr, ptr %tail, align 8
  %cmp5 = icmp eq ptr %4, %5
  br i1 %cmp5, label %cleanup, label %if.end

if.end:                                           ; preds = %lor.end
  %arrayidx = getelementptr inbounds nuw i8, ptr %4, i64 16
  %6 = load i64, ptr %arrayidx, align 8
  %cmp7 = icmp ule i64 %6, %now
  %tobool = xor i1 %cmp7, true
  %or.cond = select i1 %tobool, i1 true, i1 %3
  br i1 %or.cond, label %if.end10, label %if.then9

if.then9:                                         ; preds = %if.end
  %consumer = getelementptr inbounds nuw i8, ptr %b, i64 208
  %7 = load ptr, ptr %consumer, align 8
  tail call void @schedule_event(ptr noundef %7, i32 noundef signext 1) #7
  br label %if.end10

if.end10:                                         ; preds = %if.then9, %if.end
  %and22 = and i1 %3, %cmp7
  %and = zext i1 %and22 to i32
  br label %cleanup

cleanup:                                          ; preds = %if.end10, %lor.end
  %retval.0 = phi i32 [ %and, %if.end10 ], [ 0, %lor.end ]
  ret i32 %retval.0
}

declare dso_local void @schedule_event(ptr noundef, i32 noundef signext) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern C, from SEAL seal::util::dot_product_mod: all paths need the frame,
; but only the default case of the switch needs many callee-saved registers.
; NEW saves them in the blocks that use them only.
define dso_local i64 @dot(ptr noundef %a, ptr noundef %b, i64 noundef %n) local_unnamed_addr #0 {
; OLD-LABEL: dot:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -80
; OLD-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s4, 32(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s5, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s6, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s7, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s8, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    ld s3, 0(a0)
; OLD-NEXT:    li a3, 2
; OLD-NEXT:    beq a2, a3, .LBB4_3
; OLD-NEXT:  # %bb.1: # %entry
; OLD-NEXT:    li a3, 1
; OLD-NEXT:    bne a2, a3, .LBB4_5
; OLD-NEXT:  # %bb.2: # %sw.bb
; OLD-NEXT:    ld a0, 0(a1)
; OLD-NEXT:    mul a0, a0, s3
; OLD-NEXT:    j .LBB4_4
; OLD-NEXT:  .LBB4_3: # %sw.bb2
; OLD-NEXT:    ld a2, 0(a1)
; OLD-NEXT:    mul a2, a2, s3
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    mv a0, a2
; OLD-NEXT:    mv s1, a1
; OLD-NEXT:    call reduce
; OLD-NEXT:    ld a1, 8(s0)
; OLD-NEXT:    ld a2, 8(s1)
; OLD-NEXT:    mul a1, a2, a1
; OLD-NEXT:    add a0, a1, a0
; OLD-NEXT:  .LBB4_4: # %return
; OLD-NEXT:    call reduce
; OLD-NEXT:    addi a0, a0, 1
; OLD-NEXT:    j .LBB4_6
; OLD-NEXT:  .LBB4_5: # %sw.default
; OLD-NEXT:    ld s4, 8(a0)
; OLD-NEXT:    ld s5, 16(a0)
; OLD-NEXT:    ld s6, 24(a0)
; OLD-NEXT:    ld s7, 32(a0)
; OLD-NEXT:    ld s8, 40(a0)
; OLD-NEXT:    call big
; OLD-NEXT:    mul a1, s4, s3
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    call reduce
; OLD-NEXT:    mul a1, s6, s5
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    call reduce
; OLD-NEXT:    mul a1, s8, s7
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    call reduce
; OLD-NEXT:    add s3, s4, s3
; OLD-NEXT:    add s5, s5, s6
; OLD-NEXT:    add s7, s7, s8
; OLD-NEXT:    add s3, s3, s5
; OLD-NEXT:    add s0, s7, s0
; OLD-NEXT:    add s0, s3, s0
; OLD-NEXT:    add s0, s0, s1
; OLD-NEXT:    add a0, s2, a0
; OLD-NEXT:    add a0, s0, a0
; OLD-NEXT:  .LBB4_6: # %return
; OLD-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s4, 32(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s5, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s6, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s7, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s8, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 80
; OLD-NEXT:    ret
;
; NEW-LABEL: dot:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -80
; NEW-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld s3, 0(a0)
; NEW-NEXT:    li a3, 2
; NEW-NEXT:    beq a2, a3, .LBB4_3
; NEW-NEXT:  # %bb.1: # %entry
; NEW-NEXT:    li a3, 1
; NEW-NEXT:    bne a2, a3, .LBB4_4
; NEW-NEXT:  # %bb.2: # %sw.bb
; NEW-NEXT:    ld a0, 0(a1)
; NEW-NEXT:    mul a0, a0, s3
; NEW-NEXT:    call reduce
; NEW-NEXT:    addi a0, a0, 1
; NEW-NEXT:    j .LBB4_5
; NEW-NEXT:  .LBB4_3: # %sw.bb2
; NEW-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld a2, 0(a1)
; NEW-NEXT:    mul a2, a2, s3
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    mv a0, a2
; NEW-NEXT:    mv s1, a1
; NEW-NEXT:    call reduce
; NEW-NEXT:    ld a1, 8(s0)
; NEW-NEXT:    ld a2, 8(s1)
; NEW-NEXT:    mul a1, a2, a1
; NEW-NEXT:    add a0, a1, a0
; NEW-NEXT:    call reduce
; NEW-NEXT:    addi a0, a0, 1
; NEW-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-NEXT:    j .LBB4_5
; NEW-NEXT:  .LBB4_4: # %sw.default
; NEW-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s4, 32(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s5, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s6, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s7, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s8, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld s4, 8(a0)
; NEW-NEXT:    ld s5, 16(a0)
; NEW-NEXT:    ld s6, 24(a0)
; NEW-NEXT:    ld s7, 32(a0)
; NEW-NEXT:    ld s8, 40(a0)
; NEW-NEXT:    call big
; NEW-NEXT:    mul a1, s4, s3
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    call reduce
; NEW-NEXT:    mul a1, s6, s5
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    call reduce
; NEW-NEXT:    mul a1, s8, s7
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    call reduce
; NEW-NEXT:    add s3, s4, s3
; NEW-NEXT:    add s5, s5, s6
; NEW-NEXT:    add s7, s7, s8
; NEW-NEXT:    add s3, s3, s5
; NEW-NEXT:    add s0, s7, s0
; NEW-NEXT:    add s0, s3, s0
; NEW-NEXT:    add s0, s0, s1
; NEW-NEXT:    add a0, s2, a0
; NEW-NEXT:    add a0, s0, a0
; NEW-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s4, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s5, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s6, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s7, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s8, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:  .LBB4_5: # %return
; NEW-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 80
; NEW-NEXT:    ret
;
; NEW-RA-LABEL: dot:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    addi sp, sp, -80
; NEW-RA-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld s0, 0(a0)
; NEW-RA-NEXT:    li a3, 2
; NEW-RA-NEXT:    beq a2, a3, .LBB4_3
; NEW-RA-NEXT:  # %bb.1: # %entry
; NEW-RA-NEXT:    li a3, 1
; NEW-RA-NEXT:    bne a2, a3, .LBB4_4
; NEW-RA-NEXT:  # %bb.2: # %sw.bb
; NEW-RA-NEXT:    ld a0, 0(a1)
; NEW-RA-NEXT:    mul a0, a0, s0
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    addi a0, a0, 1
; NEW-RA-NEXT:    j .LBB4_5
; NEW-RA-NEXT:  .LBB4_3: # %sw.bb2
; NEW-RA-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a2, 0(a1)
; NEW-RA-NEXT:    mul a2, a2, s0
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    mv a0, a2
; NEW-RA-NEXT:    mv s1, a1
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    ld a1, 8(s0)
; NEW-RA-NEXT:    ld a2, 8(s1)
; NEW-RA-NEXT:    mul a1, a2, a1
; NEW-RA-NEXT:    add a0, a1, a0
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    addi a0, a0, 1
; NEW-RA-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    j .LBB4_5
; NEW-RA-NEXT:  .LBB4_4: # %sw.default
; NEW-RA-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s4, 32(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s5, 24(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s6, 16(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s7, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s8, 0(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld s3, 8(a0)
; NEW-RA-NEXT:    ld s4, 16(a0)
; NEW-RA-NEXT:    ld s5, 24(a0)
; NEW-RA-NEXT:    ld s6, 32(a0)
; NEW-RA-NEXT:    ld s7, 40(a0)
; NEW-RA-NEXT:    call big
; NEW-RA-NEXT:    mul a1, s3, s0
; NEW-RA-NEXT:    mv s8, s0
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    mv a0, a1
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    mul a1, s5, s4
; NEW-RA-NEXT:    mv s1, a0
; NEW-RA-NEXT:    mv a0, a1
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    mul a1, s7, s6
; NEW-RA-NEXT:    mv s2, a0
; NEW-RA-NEXT:    mv a0, a1
; NEW-RA-NEXT:    call reduce
; NEW-RA-NEXT:    add s3, s3, s8
; NEW-RA-NEXT:    add s4, s4, s5
; NEW-RA-NEXT:    add s6, s6, s7
; NEW-RA-NEXT:    add s3, s3, s4
; NEW-RA-NEXT:    add s0, s6, s0
; NEW-RA-NEXT:    add s0, s3, s0
; NEW-RA-NEXT:    add s0, s0, s1
; NEW-RA-NEXT:    add a0, s2, a0
; NEW-RA-NEXT:    add a0, s0, a0
; NEW-RA-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s4, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s5, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s6, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s7, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s8, 0(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:  .LBB4_5: # %return
; NEW-RA-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 80
; NEW-RA-NEXT:    ret
entry:
  %0 = load i64, ptr %a, align 8
  switch i64 %n, label %sw.default [
    i64 1, label %sw.bb
    i64 2, label %sw.bb2
  ]

sw.bb:                                            ; preds = %entry
  %1 = load i64, ptr %b, align 8
  %mul = mul i64 %1, %0
  %call = tail call i64 @reduce(i64 noundef %mul) #7
  %add = add i64 %call, 1
  br label %return

sw.bb2:                                           ; preds = %entry
  %2 = load i64, ptr %b, align 8
  %mul5 = mul i64 %2, %0
  %call6 = tail call i64 @reduce(i64 noundef %mul5) #7
  %arrayidx7 = getelementptr inbounds nuw i8, ptr %a, i64 8
  %3 = load i64, ptr %arrayidx7, align 8
  %arrayidx8 = getelementptr inbounds nuw i8, ptr %b, i64 8
  %4 = load i64, ptr %arrayidx8, align 8
  %mul9 = mul i64 %4, %3
  %add10 = add i64 %mul9, %call6
  %call11 = tail call i64 @reduce(i64 noundef %add10) #7
  %add12 = add i64 %call11, 1
  br label %return

sw.default:                                       ; preds = %entry
  %arrayidx14 = getelementptr inbounds nuw i8, ptr %a, i64 8
  %5 = load i64, ptr %arrayidx14, align 8
  %arrayidx15 = getelementptr inbounds nuw i8, ptr %a, i64 16
  %6 = load i64, ptr %arrayidx15, align 8
  %arrayidx16 = getelementptr inbounds nuw i8, ptr %a, i64 24
  %7 = load i64, ptr %arrayidx16, align 8
  %arrayidx17 = getelementptr inbounds nuw i8, ptr %a, i64 32
  %8 = load i64, ptr %arrayidx17, align 8
  %arrayidx18 = getelementptr inbounds nuw i8, ptr %a, i64 40
  %9 = load i64, ptr %arrayidx18, align 8
  %call19 = tail call i64 @big(ptr noundef nonnull %a, ptr noundef %b, i64 noundef %n) #7
  %mul20 = mul i64 %5, %0
  %call21 = tail call i64 @reduce(i64 noundef %mul20) #7
  %mul23 = mul i64 %7, %6
  %call24 = tail call i64 @reduce(i64 noundef %mul23) #7
  %mul26 = mul i64 %9, %8
  %call27 = tail call i64 @reduce(i64 noundef %mul26) #7
  %add22 = add i64 %5, %0
  %add25 = add i64 %add22, %6
  %add28 = add i64 %add25, %7
  %add29 = add i64 %add28, %8
  %add30 = add i64 %add29, %9
  %add31 = add i64 %add30, %call19
  %add32 = add i64 %add31, %call21
  %add33 = add i64 %add32, %call24
  %add34 = add i64 %add33, %call27
  br label %return

return:                                           ; preds = %sw.default, %sw.bb2, %sw.bb
  %retval.0 = phi i64 [ %add34, %sw.default ], [ %add, %sw.bb ], [ %add12, %sw.bb2 ]
  ret i64 %retval.0
}

declare dso_local i64 @reduce(i64 noundef) local_unnamed_addr

declare dso_local i64 @big(ptr noundef, ptr noundef, i64 noundef) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern C, from Stockfish Position::legal: the rare move types (castling,
; en passant) need more callee-saved registers than normal moves. NEW saves
; them in the blocks of the rare move types only.
define dso_local signext range(i32 0, 2) i32 @legal(ptr noundef %p, i32 noundef signext %m) local_unnamed_addr #0 {
; OLD-LABEL: legal:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -64
; OLD-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 40(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 32(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s3, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s4, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s5, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s6, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    lui a2, 12
; OLD-NEXT:    slli s1, a1, 52
; OLD-NEXT:    and a0, a1, a2
; OLD-NEXT:    srli s1, s1, 58
; OLD-NEXT:    andi a1, a1, 63
; OLD-NEXT:    beq a0, a2, .LBB5_3
; OLD-NEXT:  # %bb.1: # %entry
; OLD-NEXT:    lui a2, 8
; OLD-NEXT:    bne a0, a2, .LBB5_5
; OLD-NEXT:  # %bb.2: # %if.then
; OLD-NEXT:    ld s3, 0(s0)
; OLD-NEXT:    ld s4, 8(s0)
; OLD-NEXT:    ld s5, 16(s0)
; OLD-NEXT:    ld s6, 24(s0)
; OLD-NEXT:    xor a2, s4, s3
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    mv s2, a1
; OLD-NEXT:    mv a1, s1
; OLD-NEXT:    call attackers
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    xor a2, s6, s5
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    mv a1, s2
; OLD-NEXT:    call attackers
; OLD-NEXT:    or a1, s4, s3
; OLD-NEXT:    or a2, s5, s6
; OLD-NEXT:    or a0, a0, s1
; OLD-NEXT:    or a1, a1, a2
; OLD-NEXT:    and a0, a0, a1
; OLD-NEXT:    j .LBB5_7
; OLD-NEXT:  .LBB5_3: # %if.then16
; OLD-NEXT:    lw a0, 64(s0)
; OLD-NEXT:    slli a0, a0, 3
; OLD-NEXT:    add a0, s0, a0
; OLD-NEXT:    ld a2, 0(a0)
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call attackers
; OLD-NEXT:    beqz a0, .LBB5_6
; OLD-NEXT:  # %bb.4:
; OLD-NEXT:    li a0, 0
; OLD-NEXT:    j .LBB5_8
; OLD-NEXT:  .LBB5_5: # %if.end27
; OLD-NEXT:    ld a2, 40(s0)
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call attackers
; OLD-NEXT:    lw a1, 64(s0)
; OLD-NEXT:    slli a1, a1, 3
; OLD-NEXT:    add a1, s0, a1
; OLD-NEXT:    ld a1, 0(a1)
; OLD-NEXT:    and a0, a1, a0
; OLD-NEXT:    j .LBB5_7
; OLD-NEXT:  .LBB5_6: # %land.rhs
; OLD-NEXT:    ld a2, 32(s0)
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    mv a1, s1
; OLD-NEXT:    call attackers
; OLD-NEXT:  .LBB5_7: # %cleanup
; OLD-NEXT:    seqz a0, a0
; OLD-NEXT:  .LBB5_8: # %cleanup
; OLD-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s3, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s4, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s5, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s6, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 64
; OLD-NEXT:    ret
;
; NEW-LABEL: legal:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -64
; NEW-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 40(sp) # 8-byte Folded Spill
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    lui a2, 12
; NEW-NEXT:    slli s1, a1, 52
; NEW-NEXT:    and a0, a1, a2
; NEW-NEXT:    srli s1, s1, 58
; NEW-NEXT:    andi a1, a1, 63
; NEW-NEXT:    beq a0, a2, .LBB5_3
; NEW-NEXT:  # %bb.1: # %entry
; NEW-NEXT:    lui a2, 8
; NEW-NEXT:    bne a0, a2, .LBB5_5
; NEW-NEXT:  # %bb.2: # %if.then
; NEW-NEXT:    sd s2, 32(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s3, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s4, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s5, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s6, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld s3, 0(s0)
; NEW-NEXT:    ld s4, 8(s0)
; NEW-NEXT:    ld s5, 16(s0)
; NEW-NEXT:    ld s6, 24(s0)
; NEW-NEXT:    xor a2, s4, s3
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    mv s2, a1
; NEW-NEXT:    mv a1, s1
; NEW-NEXT:    call attackers
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    xor a2, s6, s5
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    mv a1, s2
; NEW-NEXT:    call attackers
; NEW-NEXT:    or a1, s4, s3
; NEW-NEXT:    or a2, s5, s6
; NEW-NEXT:    or a0, a0, s1
; NEW-NEXT:    or a1, a1, a2
; NEW-NEXT:    and a0, a0, a1
; NEW-NEXT:    seqz a0, a0
; NEW-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s3, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s4, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s5, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s6, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    j .LBB5_8
; NEW-NEXT:  .LBB5_3: # %if.then16
; NEW-NEXT:    lw a0, 64(s0)
; NEW-NEXT:    slli a0, a0, 3
; NEW-NEXT:    add a0, s0, a0
; NEW-NEXT:    ld a2, 0(a0)
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call attackers
; NEW-NEXT:    beqz a0, .LBB5_6
; NEW-NEXT:  # %bb.4:
; NEW-NEXT:    li a0, 0
; NEW-NEXT:    j .LBB5_8
; NEW-NEXT:  .LBB5_5: # %if.end27
; NEW-NEXT:    ld a2, 40(s0)
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call attackers
; NEW-NEXT:    lw a1, 64(s0)
; NEW-NEXT:    slli a1, a1, 3
; NEW-NEXT:    add a1, s0, a1
; NEW-NEXT:    ld a1, 0(a1)
; NEW-NEXT:    and a0, a1, a0
; NEW-NEXT:    j .LBB5_7
; NEW-NEXT:  .LBB5_6: # %land.rhs
; NEW-NEXT:    ld a2, 32(s0)
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    mv a1, s1
; NEW-NEXT:    call attackers
; NEW-NEXT:  .LBB5_7: # %cleanup
; NEW-NEXT:    seqz a0, a0
; NEW-NEXT:  .LBB5_8: # %cleanup
; NEW-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 64
; NEW-NEXT:    ret
;
; NEW-RA-LABEL: legal:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    addi sp, sp, -80
; NEW-RA-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    lui a4, 12
; NEW-RA-NEXT:    slli a3, a1, 52
; NEW-RA-NEXT:    and a2, a1, a4
; NEW-RA-NEXT:    srli a3, a3, 58
; NEW-RA-NEXT:    andi a1, a1, 63
; NEW-RA-NEXT:    beq a2, a4, .LBB5_3
; NEW-RA-NEXT:  # %bb.1: # %entry
; NEW-RA-NEXT:    lui a4, 8
; NEW-RA-NEXT:    bne a2, a4, .LBB5_5
; NEW-RA-NEXT:  # %bb.2: # %if.then
; NEW-RA-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s4, 32(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s5, 24(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s6, 16(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld s3, 0(a0)
; NEW-RA-NEXT:    ld s4, 8(a0)
; NEW-RA-NEXT:    ld s5, 16(a0)
; NEW-RA-NEXT:    ld s6, 24(a0)
; NEW-RA-NEXT:    xor a2, s4, s3
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    mv s1, a1
; NEW-RA-NEXT:    mv a1, a3
; NEW-RA-NEXT:    call attackers
; NEW-RA-NEXT:    mv s2, a0
; NEW-RA-NEXT:    xor a2, s6, s5
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    mv a1, s1
; NEW-RA-NEXT:    call attackers
; NEW-RA-NEXT:    or a1, s4, s3
; NEW-RA-NEXT:    or a2, s5, s6
; NEW-RA-NEXT:    or a0, a0, s2
; NEW-RA-NEXT:    or a1, a1, a2
; NEW-RA-NEXT:    and a0, a0, a1
; NEW-RA-NEXT:    seqz a0, a0
; NEW-RA-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s4, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s5, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s6, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    j .LBB5_8
; NEW-RA-NEXT:  .LBB5_3: # %if.then16
; NEW-RA-NEXT:    sd a3, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    lw a2, 64(a0)
; NEW-RA-NEXT:    slli a2, a2, 3
; NEW-RA-NEXT:    add a2, a0, a2
; NEW-RA-NEXT:    ld a2, 0(a2)
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    call attackers
; NEW-RA-NEXT:    beqz a0, .LBB5_6
; NEW-RA-NEXT:  # %bb.4:
; NEW-RA-NEXT:    li a0, 0
; NEW-RA-NEXT:    j .LBB5_8
; NEW-RA-NEXT:  .LBB5_5: # %if.end27
; NEW-RA-NEXT:    ld a2, 40(a0)
; NEW-RA-NEXT:    mv s0, a0
; NEW-RA-NEXT:    call attackers
; NEW-RA-NEXT:    lw a1, 64(s0)
; NEW-RA-NEXT:    slli a1, a1, 3
; NEW-RA-NEXT:    add a1, s0, a1
; NEW-RA-NEXT:    ld a1, 0(a1)
; NEW-RA-NEXT:    and a0, a1, a0
; NEW-RA-NEXT:    j .LBB5_7
; NEW-RA-NEXT:  .LBB5_6: # %land.rhs
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    ld a2, 32(s0)
; NEW-RA-NEXT:    ld a1, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    call attackers
; NEW-RA-NEXT:  .LBB5_7: # %cleanup
; NEW-RA-NEXT:    seqz a0, a0
; NEW-RA-NEXT:  .LBB5_8: # %cleanup
; NEW-RA-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 80
; NEW-RA-NEXT:    ret
entry:
  %shr = lshr i32 %m, 6
  %and1 = and i32 %shr, 63
  %and2 = and i32 %m, 63
  %0 = trunc i32 %m to i16
  %trunc = and i16 %0, -16384
  switch i16 %trunc, label %if.end27 [
    i16 -32768, label %if.then
    i16 -16384, label %if.then16
  ]

if.then:                                          ; preds = %entry
  %1 = load i64, ptr %p, align 8
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %p, i64 8
  %2 = load i64, ptr %arrayidx4, align 8
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %p, i64 16
  %3 = load i64, ptr %arrayidx6, align 8
  %arrayidx8 = getelementptr inbounds nuw i8, ptr %p, i64 24
  %4 = load i64, ptr %arrayidx8, align 8
  %xor = xor i64 %2, %1
  %call = tail call i64 @attackers(ptr noundef nonnull %p, i32 noundef signext %and1, i64 noundef %xor) #7
  %xor9 = xor i64 %4, %3
  %call10 = tail call i64 @attackers(ptr noundef nonnull %p, i32 noundef signext %and2, i64 noundef %xor9) #7
  %or = or i64 %call10, %call
  %or11 = or i64 %2, %1
  %or12 = or i64 %or11, %3
  %or13 = or i64 %or12, %4
  %and14 = and i64 %or, %or13
  %tobool.not = icmp eq i64 %and14, 0
  br label %cleanup

if.then16:                                        ; preds = %entry
  %side = getelementptr inbounds nuw i8, ptr %p, i64 64
  %5 = load i32, ptr %side, align 8
  %idxprom = sext i32 %5 to i64
  %arrayidx18 = getelementptr inbounds [8 x i8], ptr %p, i64 %idxprom
  %6 = load i64, ptr %arrayidx18, align 8
  %call19 = tail call i64 @attackers(ptr noundef %p, i32 noundef signext %and2, i64 noundef %6) #7
  %tobool20.not = icmp eq i64 %call19, 0
  br i1 %tobool20.not, label %land.rhs, label %cleanup

land.rhs:                                         ; preds = %if.then16
  %arrayidx22 = getelementptr inbounds nuw i8, ptr %p, i64 32
  %7 = load i64, ptr %arrayidx22, align 8
  %call23 = tail call i64 @attackers(ptr noundef nonnull %p, i32 noundef signext %and1, i64 noundef %7) #7
  %tobool24.not = icmp eq i64 %call23, 0
  br label %cleanup

if.end27:                                         ; preds = %entry
  %arrayidx29 = getelementptr inbounds nuw i8, ptr %p, i64 40
  %8 = load i64, ptr %arrayidx29, align 8
  %call30 = tail call i64 @attackers(ptr noundef %p, i32 noundef signext %and2, i64 noundef %8) #7
  %side32 = getelementptr inbounds nuw i8, ptr %p, i64 64
  %9 = load i32, ptr %side32, align 8
  %idxprom33 = sext i32 %9 to i64
  %arrayidx34 = getelementptr inbounds [8 x i8], ptr %p, i64 %idxprom33
  %10 = load i64, ptr %arrayidx34, align 8
  %and35 = and i64 %10, %call30
  %tobool36.not = icmp eq i64 %and35, 0
  br label %cleanup

cleanup:                                          ; preds = %if.end27, %land.rhs, %if.then16, %if.then
  %retval.0.shrunk = phi i1 [ %tobool.not, %if.then ], [ %tobool36.not, %if.end27 ], [ false, %if.then16 ], [ %tobool24.not, %land.rhs ]
  %retval.0 = zext i1 %retval.0.shrunk to i32
  ret i32 %retval.0
}

declare dso_local i64 @attackers(ptr noundef, i32 noundef signext, i64 noundef) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern D, from cppcheck multiCompareImpl: a hot loop without calls, with a
; rare call. Constants and values used in the loop are kept in callee-saved
; registers set in the entry block (OLD, NEW). With NEW-RA they are not, and
; the prologue moves to the block of the rare call, so the hot loop runs
; without the frame, like GCC's code.
define dso_local signext range(i32 -1, -2147483648) i32 @multi_compare(ptr noundef %t, ptr noundef %h, i32 noundef signext %varid) local_unnamed_addr #0 {
; OLD-LABEL: multi_compare:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -64
; OLD-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 40(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 32(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s3, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s4, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s5, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s6, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    ld s3, 0(a0)
; OLD-NEXT:    li s4, 37
; OLD-NEXT:    li s5, 32
; OLD-NEXT:    li s6, 124
; OLD-NEXT:    lbu a3, 0(a1)
; OLD-NEXT:    bne a3, s4, .LBB6_5
; OLD-NEXT:  .LBB6_1: # %if.then
; OLD-NEXT:    lbu a3, 1(a1)
; OLD-NEXT:    beqz a3, .LBB6_5
; OLD-NEXT:  # %bb.2: # %if.then
; OLD-NEXT:    beq a3, s5, .LBB6_5
; OLD-NEXT:  # %bb.3: # %if.then
; OLD-NEXT:    beq a3, s6, .LBB6_5
; OLD-NEXT:  # %bb.4: # %land.rhs
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    mv s1, a1
; OLD-NEXT:    mv s2, a2
; OLD-NEXT:    call match_class
; OLD-NEXT:    mv a1, s1
; OLD-NEXT:    mv a2, s2
; OLD-NEXT:    mv a3, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    bgez a3, .LBB6_22
; OLD-NEXT:  .LBB6_5: # %while.cond.preheader
; OLD-NEXT:    # =>This Loop Header: Depth=1
; OLD-NEXT:    # Child Loop BB6_6 Depth 2
; OLD-NEXT:    # Child Loop BB6_15 Depth 2
; OLD-NEXT:    addi a3, a1, 1
; OLD-NEXT:    mv a5, s3
; OLD-NEXT:  .LBB6_6: # %while.cond
; OLD-NEXT:    # Parent Loop BB6_5 Depth=1
; OLD-NEXT:    # => This Inner Loop Header: Depth=2
; OLD-NEXT:    lbu a4, 0(a1)
; OLD-NEXT:    lbu a6, 0(a5)
; OLD-NEXT:    beqz a4, .LBB6_13
; OLD-NEXT:  # %bb.7: # %while.cond
; OLD-NEXT:    # in Loop: Header=BB6_6 Depth=2
; OLD-NEXT:    beq a4, s5, .LBB6_13
; OLD-NEXT:  # %bb.8: # %while.cond
; OLD-NEXT:    # in Loop: Header=BB6_6 Depth=2
; OLD-NEXT:    beq a4, s6, .LBB6_13
; OLD-NEXT:  # %bb.9: # %land.rhs30
; OLD-NEXT:    # in Loop: Header=BB6_6 Depth=2
; OLD-NEXT:    bne a4, a6, .LBB6_11
; OLD-NEXT:  # %bb.10: # %while.body
; OLD-NEXT:    # in Loop: Header=BB6_6 Depth=2
; OLD-NEXT:    addi a1, a1, 1
; OLD-NEXT:    addi a5, a5, 1
; OLD-NEXT:    addi a3, a3, 1
; OLD-NEXT:    j .LBB6_6
; OLD-NEXT:  .LBB6_11: # %while.end
; OLD-NEXT:    # in Loop: Header=BB6_5 Depth=1
; OLD-NEXT:    beq a4, s6, .LBB6_13
; OLD-NEXT:  # %bb.12: # %while.end
; OLD-NEXT:    # in Loop: Header=BB6_5 Depth=1
; OLD-NEXT:    bnez a4, .LBB6_14
; OLD-NEXT:  .LBB6_13: # %land.lhs.true48
; OLD-NEXT:    # in Loop: Header=BB6_5 Depth=1
; OLD-NEXT:    beqz a6, .LBB6_21
; OLD-NEXT:  .LBB6_14: # %while.cond54
; OLD-NEXT:    # in Loop: Header=BB6_5 Depth=1
; OLD-NEXT:    beqz a4, .LBB6_19
; OLD-NEXT:  .LBB6_15: # %while.cond54
; OLD-NEXT:    # Parent Loop BB6_5 Depth=1
; OLD-NEXT:    # => This Inner Loop Header: Depth=2
; OLD-NEXT:    beq a4, s5, .LBB6_19
; OLD-NEXT:  # %bb.16: # %while.cond54
; OLD-NEXT:    # in Loop: Header=BB6_15 Depth=2
; OLD-NEXT:    beq a4, s6, .LBB6_18
; OLD-NEXT:  # %bb.17: # %while.body67
; OLD-NEXT:    # in Loop: Header=BB6_15 Depth=2
; OLD-NEXT:    lbu a4, 0(a3)
; OLD-NEXT:    addi a3, a3, 1
; OLD-NEXT:    bnez a4, .LBB6_15
; OLD-NEXT:    j .LBB6_19
; OLD-NEXT:  .LBB6_18: # in Loop: Header=BB6_5 Depth=1
; OLD-NEXT:    mv a1, a3
; OLD-NEXT:    lbu a3, 0(a3)
; OLD-NEXT:    beq a3, s4, .LBB6_1
; OLD-NEXT:    j .LBB6_5
; OLD-NEXT:  .LBB6_19: # %cleanup79.loopexit
; OLD-NEXT:    li a0, -1
; OLD-NEXT:  .LBB6_20: # %cleanup79
; OLD-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s3, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s4, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s5, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s6, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 64
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB6_21:
; OLD-NEXT:    li a0, 1
; OLD-NEXT:    j .LBB6_20
; OLD-NEXT:  .LBB6_22:
; OLD-NEXT:    mv a0, a3
; OLD-NEXT:    j .LBB6_20
;
; NEW-LABEL: multi_compare:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -64
; NEW-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s3, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s4, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s5, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s6, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    ld s3, 0(a0)
; NEW-NEXT:    li s4, 37
; NEW-NEXT:    li s5, 32
; NEW-NEXT:    li s6, 124
; NEW-NEXT:    lbu a3, 0(a1)
; NEW-NEXT:    bne a3, s4, .LBB6_6
; NEW-NEXT:  .LBB6_1: # %if.then
; NEW-NEXT:    lbu a3, 1(a1)
; NEW-NEXT:    beqz a3, .LBB6_6
; NEW-NEXT:  # %bb.2: # %if.then
; NEW-NEXT:    beq a3, s5, .LBB6_6
; NEW-NEXT:  # %bb.3: # %if.then
; NEW-NEXT:    beq a3, s6, .LBB6_6
; NEW-NEXT:  # %bb.4: # %land.rhs
; NEW-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 40(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 32(sp) # 8-byte Folded Spill
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    mv s1, a1
; NEW-NEXT:    mv s2, a2
; NEW-NEXT:    call match_class
; NEW-NEXT:    mv a1, s1
; NEW-NEXT:    mv a2, s2
; NEW-NEXT:    mv a3, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    bgez a3, .LBB6_23
; NEW-NEXT:  # %bb.5:
; NEW-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:  .LBB6_6: # %while.cond.preheader
; NEW-NEXT:    # =>This Loop Header: Depth=1
; NEW-NEXT:    # Child Loop BB6_7 Depth 2
; NEW-NEXT:    # Child Loop BB6_16 Depth 2
; NEW-NEXT:    addi a3, a1, 1
; NEW-NEXT:    mv a5, s3
; NEW-NEXT:  .LBB6_7: # %while.cond
; NEW-NEXT:    # Parent Loop BB6_6 Depth=1
; NEW-NEXT:    # => This Inner Loop Header: Depth=2
; NEW-NEXT:    lbu a4, 0(a1)
; NEW-NEXT:    lbu a6, 0(a5)
; NEW-NEXT:    beqz a4, .LBB6_14
; NEW-NEXT:  # %bb.8: # %while.cond
; NEW-NEXT:    # in Loop: Header=BB6_7 Depth=2
; NEW-NEXT:    beq a4, s5, .LBB6_14
; NEW-NEXT:  # %bb.9: # %while.cond
; NEW-NEXT:    # in Loop: Header=BB6_7 Depth=2
; NEW-NEXT:    beq a4, s6, .LBB6_14
; NEW-NEXT:  # %bb.10: # %land.rhs30
; NEW-NEXT:    # in Loop: Header=BB6_7 Depth=2
; NEW-NEXT:    bne a4, a6, .LBB6_12
; NEW-NEXT:  # %bb.11: # %while.body
; NEW-NEXT:    # in Loop: Header=BB6_7 Depth=2
; NEW-NEXT:    addi a1, a1, 1
; NEW-NEXT:    addi a5, a5, 1
; NEW-NEXT:    addi a3, a3, 1
; NEW-NEXT:    j .LBB6_7
; NEW-NEXT:  .LBB6_12: # %while.end
; NEW-NEXT:    # in Loop: Header=BB6_6 Depth=1
; NEW-NEXT:    beq a4, s6, .LBB6_14
; NEW-NEXT:  # %bb.13: # %while.end
; NEW-NEXT:    # in Loop: Header=BB6_6 Depth=1
; NEW-NEXT:    bnez a4, .LBB6_15
; NEW-NEXT:  .LBB6_14: # %land.lhs.true48
; NEW-NEXT:    # in Loop: Header=BB6_6 Depth=1
; NEW-NEXT:    beqz a6, .LBB6_22
; NEW-NEXT:  .LBB6_15: # %while.cond54
; NEW-NEXT:    # in Loop: Header=BB6_6 Depth=1
; NEW-NEXT:    beqz a4, .LBB6_20
; NEW-NEXT:  .LBB6_16: # %while.cond54
; NEW-NEXT:    # Parent Loop BB6_6 Depth=1
; NEW-NEXT:    # => This Inner Loop Header: Depth=2
; NEW-NEXT:    beq a4, s5, .LBB6_20
; NEW-NEXT:  # %bb.17: # %while.cond54
; NEW-NEXT:    # in Loop: Header=BB6_16 Depth=2
; NEW-NEXT:    beq a4, s6, .LBB6_19
; NEW-NEXT:  # %bb.18: # %while.body67
; NEW-NEXT:    # in Loop: Header=BB6_16 Depth=2
; NEW-NEXT:    lbu a4, 0(a3)
; NEW-NEXT:    addi a3, a3, 1
; NEW-NEXT:    bnez a4, .LBB6_16
; NEW-NEXT:    j .LBB6_20
; NEW-NEXT:  .LBB6_19: # in Loop: Header=BB6_6 Depth=1
; NEW-NEXT:    mv a1, a3
; NEW-NEXT:    lbu a3, 0(a3)
; NEW-NEXT:    beq a3, s4, .LBB6_1
; NEW-NEXT:    j .LBB6_6
; NEW-NEXT:  .LBB6_20: # %cleanup79.loopexit
; NEW-NEXT:    li a0, -1
; NEW-NEXT:  .LBB6_21: # %cleanup79
; NEW-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s3, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s4, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s5, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s6, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 64
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB6_22:
; NEW-NEXT:    li a0, 1
; NEW-NEXT:    j .LBB6_21
; NEW-NEXT:  .LBB6_23:
; NEW-NEXT:    mv a0, a3
; NEW-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:    j .LBB6_21
;
; NEW-RA-LABEL: multi_compare:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    ld a4, 0(a0)
; NEW-RA-NEXT:    li a5, 37
; NEW-RA-NEXT:    li a6, 32
; NEW-RA-NEXT:    li a7, 124
; NEW-RA-NEXT:    lbu a3, 0(a1)
; NEW-RA-NEXT:    bne a3, a5, .LBB6_4
; NEW-RA-NEXT:  .LBB6_1: # %if.then
; NEW-RA-NEXT:    lbu a3, 1(a1)
; NEW-RA-NEXT:    beqz a3, .LBB6_4
; NEW-RA-NEXT:  # %bb.2: # %if.then
; NEW-RA-NEXT:    beq a3, a6, .LBB6_4
; NEW-RA-NEXT:  # %bb.3: # %if.then
; NEW-RA-NEXT:    bne a3, a7, .LBB6_19
; NEW-RA-NEXT:  .LBB6_4: # %while.cond.preheader
; NEW-RA-NEXT:    # =>This Loop Header: Depth=1
; NEW-RA-NEXT:    # Child Loop BB6_5 Depth 2
; NEW-RA-NEXT:    # Child Loop BB6_14 Depth 2
; NEW-RA-NEXT:    addi a3, a1, 1
; NEW-RA-NEXT:    mv t1, a4
; NEW-RA-NEXT:  .LBB6_5: # %while.cond
; NEW-RA-NEXT:    # Parent Loop BB6_4 Depth=1
; NEW-RA-NEXT:    # => This Inner Loop Header: Depth=2
; NEW-RA-NEXT:    lbu t0, 0(a1)
; NEW-RA-NEXT:    lbu t2, 0(t1)
; NEW-RA-NEXT:    beqz t0, .LBB6_12
; NEW-RA-NEXT:  # %bb.6: # %while.cond
; NEW-RA-NEXT:    # in Loop: Header=BB6_5 Depth=2
; NEW-RA-NEXT:    beq t0, a6, .LBB6_12
; NEW-RA-NEXT:  # %bb.7: # %while.cond
; NEW-RA-NEXT:    # in Loop: Header=BB6_5 Depth=2
; NEW-RA-NEXT:    beq t0, a7, .LBB6_12
; NEW-RA-NEXT:  # %bb.8: # %land.rhs30
; NEW-RA-NEXT:    # in Loop: Header=BB6_5 Depth=2
; NEW-RA-NEXT:    bne t0, t2, .LBB6_10
; NEW-RA-NEXT:  # %bb.9: # %while.body
; NEW-RA-NEXT:    # in Loop: Header=BB6_5 Depth=2
; NEW-RA-NEXT:    addi a1, a1, 1
; NEW-RA-NEXT:    addi t1, t1, 1
; NEW-RA-NEXT:    addi a3, a3, 1
; NEW-RA-NEXT:    j .LBB6_5
; NEW-RA-NEXT:  .LBB6_10: # %while.end
; NEW-RA-NEXT:    # in Loop: Header=BB6_4 Depth=1
; NEW-RA-NEXT:    beq t0, a7, .LBB6_12
; NEW-RA-NEXT:  # %bb.11: # %while.end
; NEW-RA-NEXT:    # in Loop: Header=BB6_4 Depth=1
; NEW-RA-NEXT:    bnez t0, .LBB6_13
; NEW-RA-NEXT:  .LBB6_12: # %land.lhs.true48
; NEW-RA-NEXT:    # in Loop: Header=BB6_4 Depth=1
; NEW-RA-NEXT:    beqz t2, .LBB6_41
; NEW-RA-NEXT:  .LBB6_13: # %while.cond54
; NEW-RA-NEXT:    # in Loop: Header=BB6_4 Depth=1
; NEW-RA-NEXT:    beqz t0, .LBB6_18
; NEW-RA-NEXT:  .LBB6_14: # %while.cond54
; NEW-RA-NEXT:    # Parent Loop BB6_4 Depth=1
; NEW-RA-NEXT:    # => This Inner Loop Header: Depth=2
; NEW-RA-NEXT:    beq t0, a6, .LBB6_18
; NEW-RA-NEXT:  # %bb.15: # %while.cond54
; NEW-RA-NEXT:    # in Loop: Header=BB6_14 Depth=2
; NEW-RA-NEXT:    beq t0, a7, .LBB6_17
; NEW-RA-NEXT:  # %bb.16: # %while.body67
; NEW-RA-NEXT:    # in Loop: Header=BB6_14 Depth=2
; NEW-RA-NEXT:    lbu t0, 0(a3)
; NEW-RA-NEXT:    addi a3, a3, 1
; NEW-RA-NEXT:    bnez t0, .LBB6_14
; NEW-RA-NEXT:    j .LBB6_18
; NEW-RA-NEXT:  .LBB6_17: # in Loop: Header=BB6_4 Depth=1
; NEW-RA-NEXT:    mv a1, a3
; NEW-RA-NEXT:    lbu a3, 0(a3)
; NEW-RA-NEXT:    beq a3, a5, .LBB6_1
; NEW-RA-NEXT:    j .LBB6_4
; NEW-RA-NEXT:  .LBB6_18: # %cleanup79.loopexit
; NEW-RA-NEXT:    li a0, -1
; NEW-RA-NEXT:    ret
; NEW-RA-NEXT:  .LBB6_19: # %land.rhs
; NEW-RA-NEXT:    addi sp, sp, -48
; NEW-RA-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:  .LBB6_20: # %land.rhs
; NEW-RA-NEXT:    # =>This Loop Header: Depth=1
; NEW-RA-NEXT:    # Child Loop BB6_21 Depth 2
; NEW-RA-NEXT:    # Child Loop BB6_22 Depth 3
; NEW-RA-NEXT:    # Child Loop BB6_31 Depth 3
; NEW-RA-NEXT:    sd a0, 32(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    sd a1, 24(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a1, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    sd a2, 16(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld a2, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    sd a4, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    call match_class
; NEW-RA-NEXT:    li a7, 124
; NEW-RA-NEXT:    li a6, 32
; NEW-RA-NEXT:    li a5, 37
; NEW-RA-NEXT:    ld a4, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld a1, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld a2, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    mv a3, a0
; NEW-RA-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    bgez a3, .LBB6_43
; NEW-RA-NEXT:  .LBB6_21: # %while.cond.preheader
; NEW-RA-NEXT:    # Parent Loop BB6_20 Depth=1
; NEW-RA-NEXT:    # => This Loop Header: Depth=2
; NEW-RA-NEXT:    # Child Loop BB6_22 Depth 3
; NEW-RA-NEXT:    # Child Loop BB6_31 Depth 3
; NEW-RA-NEXT:    addi a3, a1, 1
; NEW-RA-NEXT:    mv t1, a4
; NEW-RA-NEXT:  .LBB6_22: # %while.cond
; NEW-RA-NEXT:    # Parent Loop BB6_20 Depth=1
; NEW-RA-NEXT:    # Parent Loop BB6_21 Depth=2
; NEW-RA-NEXT:    # => This Inner Loop Header: Depth=3
; NEW-RA-NEXT:    lbu t0, 0(a1)
; NEW-RA-NEXT:    lbu t2, 0(t1)
; NEW-RA-NEXT:    beqz t0, .LBB6_29
; NEW-RA-NEXT:  # %bb.23: # %while.cond
; NEW-RA-NEXT:    # in Loop: Header=BB6_22 Depth=3
; NEW-RA-NEXT:    beq t0, a6, .LBB6_29
; NEW-RA-NEXT:  # %bb.24: # %while.cond
; NEW-RA-NEXT:    # in Loop: Header=BB6_22 Depth=3
; NEW-RA-NEXT:    beq t0, a7, .LBB6_29
; NEW-RA-NEXT:  # %bb.25: # %land.rhs30
; NEW-RA-NEXT:    # in Loop: Header=BB6_22 Depth=3
; NEW-RA-NEXT:    bne t0, t2, .LBB6_27
; NEW-RA-NEXT:  # %bb.26: # %while.body
; NEW-RA-NEXT:    # in Loop: Header=BB6_22 Depth=3
; NEW-RA-NEXT:    addi a1, a1, 1
; NEW-RA-NEXT:    addi t1, t1, 1
; NEW-RA-NEXT:    addi a3, a3, 1
; NEW-RA-NEXT:    j .LBB6_22
; NEW-RA-NEXT:  .LBB6_27: # %while.end
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    beq t0, a7, .LBB6_29
; NEW-RA-NEXT:  # %bb.28: # %while.end
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    bnez t0, .LBB6_30
; NEW-RA-NEXT:  .LBB6_29: # %land.lhs.true48
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    beqz t2, .LBB6_42
; NEW-RA-NEXT:  .LBB6_30: # %while.cond54
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    beqz t0, .LBB6_39
; NEW-RA-NEXT:  .LBB6_31: # %while.cond54
; NEW-RA-NEXT:    # Parent Loop BB6_20 Depth=1
; NEW-RA-NEXT:    # Parent Loop BB6_21 Depth=2
; NEW-RA-NEXT:    # => This Inner Loop Header: Depth=3
; NEW-RA-NEXT:    beq t0, a6, .LBB6_39
; NEW-RA-NEXT:  # %bb.32: # %while.cond54
; NEW-RA-NEXT:    # in Loop: Header=BB6_31 Depth=3
; NEW-RA-NEXT:    beq t0, a7, .LBB6_34
; NEW-RA-NEXT:  # %bb.33: # %while.body67
; NEW-RA-NEXT:    # in Loop: Header=BB6_31 Depth=3
; NEW-RA-NEXT:    lbu t0, 0(a3)
; NEW-RA-NEXT:    addi a3, a3, 1
; NEW-RA-NEXT:    bnez t0, .LBB6_31
; NEW-RA-NEXT:    j .LBB6_39
; NEW-RA-NEXT:  .LBB6_34: # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    mv a1, a3
; NEW-RA-NEXT:  # %bb.35: # %for.cond
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    lbu a3, 0(a1)
; NEW-RA-NEXT:    bne a3, a5, .LBB6_21
; NEW-RA-NEXT:  # %bb.36: # %if.then
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    lbu a3, 1(a1)
; NEW-RA-NEXT:    beqz a3, .LBB6_21
; NEW-RA-NEXT:  # %bb.37: # %if.then
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    beq a3, a6, .LBB6_21
; NEW-RA-NEXT:  # %bb.38: # %if.then
; NEW-RA-NEXT:    # in Loop: Header=BB6_21 Depth=2
; NEW-RA-NEXT:    beq a3, a7, .LBB6_21
; NEW-RA-NEXT:    j .LBB6_20
; NEW-RA-NEXT:  .LBB6_39: # %cleanup79.loopexit
; NEW-RA-NEXT:    li a0, -1
; NEW-RA-NEXT:  .LBB6_40: # %cleanup79
; NEW-RA-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 48
; NEW-RA-NEXT:    ret
; NEW-RA-NEXT:  .LBB6_41:
; NEW-RA-NEXT:    li a0, 1
; NEW-RA-NEXT:    ret
; NEW-RA-NEXT:  .LBB6_42:
; NEW-RA-NEXT:    li a0, 1
; NEW-RA-NEXT:    j .LBB6_40
; NEW-RA-NEXT:  .LBB6_43:
; NEW-RA-NEXT:    mv a0, a3
; NEW-RA-NEXT:    j .LBB6_40
entry:
  %0 = load ptr, ptr %t, align 8
  br label %for.cond

for.cond:                                         ; preds = %cleanup76, %entry
  %h.addr.0 = phi ptr [ %h, %entry ], [ %incdec.ptr75, %cleanup76 ]
  %1 = load i8, ptr %h.addr.0, align 1
  %cmp = icmp eq i8 %1, 37
  br i1 %cmp, label %if.then, label %while.cond.preheader

if.then:                                          ; preds = %for.cond
  %arrayidx = getelementptr inbounds nuw i8, ptr %h.addr.0, i64 1
  %2 = load i8, ptr %arrayidx, align 1
  switch i8 %2, label %land.rhs [
    i8 32, label %while.cond.preheader
    i8 124, label %while.cond.preheader
    i8 0, label %while.cond.preheader
  ]

land.rhs:                                         ; preds = %if.then
  %call = tail call signext i32 @match_class(ptr noundef nonnull %t, ptr noundef nonnull %h.addr.0, i32 noundef signext %varid) #7
  %cmp15 = icmp slt i32 %call, 0
  br i1 %cmp15, label %while.cond.preheader, label %cleanup79

while.cond.preheader:                             ; preds = %land.rhs, %if.then, %if.then, %if.then, %for.cond
  br label %while.cond

while.cond:                                       ; preds = %while.body, %while.cond.preheader
  %h.addr.1 = phi ptr [ %incdec.ptr, %while.body ], [ %h.addr.0, %while.cond.preheader ]
  %p.0 = phi ptr [ %incdec.ptr37, %while.body ], [ %0, %while.cond.preheader ]
  %3 = load i8, ptr %h.addr.1, align 1
  %4 = load i8, ptr %p.0, align 1
  switch i8 %3, label %land.rhs30 [
    i8 0, label %land.lhs.true48
    i8 124, label %land.lhs.true48
    i8 32, label %land.lhs.true48
  ]

land.rhs30:                                       ; preds = %while.cond
  %cmp33 = icmp eq i8 %3, %4
  br i1 %cmp33, label %while.body, label %while.end

while.body:                                       ; preds = %land.rhs30
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %h.addr.1, i64 1
  %incdec.ptr37 = getelementptr inbounds nuw i8, ptr %p.0, i64 1
  br label %while.cond

while.end:                                        ; preds = %land.rhs30
  switch i8 %3, label %while.cond54.preheader [
    i8 0, label %land.lhs.true48
    i8 124, label %land.lhs.true48
  ]

land.lhs.true48:                                  ; preds = %while.end, %while.end, %while.cond, %while.cond, %while.cond
  %cmp50 = icmp eq i8 %4, 0
  br i1 %cmp50, label %cleanup79, label %while.cond54.preheader

while.cond54.preheader:                           ; preds = %land.lhs.true48, %while.end
  br label %while.cond54

while.cond54:                                     ; preds = %while.body67, %while.cond54.preheader
  %5 = phi i8 [ %.pre123, %while.body67 ], [ %3, %while.cond54.preheader ]
  %h.addr.2 = phi ptr [ %incdec.ptr68, %while.body67 ], [ %h.addr.1, %while.cond54.preheader ]
  switch i8 %5, label %while.body67 [
    i8 124, label %cleanup76
    i8 0, label %cleanup79
    i8 32, label %cleanup79
  ]

while.body67:                                     ; preds = %while.cond54
  %incdec.ptr68 = getelementptr inbounds nuw i8, ptr %h.addr.2, i64 1
  %.pre123 = load i8, ptr %incdec.ptr68, align 1
  br label %while.cond54

cleanup76:                                        ; preds = %while.cond54
  %incdec.ptr75 = getelementptr inbounds nuw i8, ptr %h.addr.2, i64 1
  br label %for.cond

cleanup79:                                        ; preds = %while.cond54, %while.cond54, %land.lhs.true48, %land.rhs
  %retval.4 = phi i32 [ -1, %while.cond54 ], [ -1, %while.cond54 ], [ 1, %land.lhs.true48 ], [ %call, %land.rhs ]
  ret i32 %retval.4
}

declare dso_local signext i32 @match_class(ptr noundef, ptr noundef, i32 noundef signext) local_unnamed_addr

; Function Attrs: noinline nounwind
; Pattern E, from omnetpp StaticStringPool::get: the early exits return
; constants and join the return block of the path with calls.
; FIXME: The return value phi is assigned to s2, so the early exits write s2
; and need the frame. GCC returns them in a0 without a frame. NEW only wraps
; the other callee-saved registers separately.
define dso_local noundef ptr @pool_get(ptr noundef %p, ptr noundef %s) local_unnamed_addr #0 {
; OLD-LABEL: pool_get:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -48
; OLD-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s3, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    beqz a1, .LBB7_7
; OLD-NEXT:  # %bb.1: # %if.end
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    lbu a1, 0(a1)
; OLD-NEXT:    beqz a1, .LBB7_8
; OLD-NEXT:  # %bb.2: # %for.body.preheader
; OLD-NEXT:    lui a2, 1
; OLD-NEXT:    addi a3, s0, 1
; OLD-NEXT:    addi a2, a2, 1285
; OLD-NEXT:  .LBB7_3: # %for.body
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    add a4, a2, a1
; OLD-NEXT:    lbu a1, 0(a3)
; OLD-NEXT:    slli a2, a2, 5
; OLD-NEXT:    add a2, a2, a4
; OLD-NEXT:    addi a3, a3, 1
; OLD-NEXT:    bnez a1, .LBB7_3
; OLD-NEXT:  # %bb.4: # %for.cond.cleanup
; OLD-NEXT:    ld a1, 8(a0)
; OLD-NEXT:    remu a1, a2, a1
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    ld s3, 0(a0)
; OLD-NEXT:    slli a1, a1, 3
; OLD-NEXT:    add s3, s3, a1
; OLD-NEXT:  .LBB7_5: # %for.cond6
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    ld s3, 0(s3)
; OLD-NEXT:    beqz s3, .LBB7_9
; OLD-NEXT:  # %bb.6: # %for.body9
; OLD-NEXT:    # in Loop: Header=BB7_5 Depth=1
; OLD-NEXT:    ld s2, 8(s3)
; OLD-NEXT:    mv a0, s2
; OLD-NEXT:    mv a1, s0
; OLD-NEXT:    call strcmp
; OLD-NEXT:    bnez a0, .LBB7_5
; OLD-NEXT:    j .LBB7_10
; OLD-NEXT:  .LBB7_7:
; OLD-NEXT:    li s2, 0
; OLD-NEXT:    j .LBB7_10
; OLD-NEXT:  .LBB7_8:
; OLD-NEXT:    lui s2, %hi(.L.str.2)
; OLD-NEXT:    addi s2, s2, %lo(.L.str.2)
; OLD-NEXT:    j .LBB7_10
; OLD-NEXT:  .LBB7_9: # %for.end16
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call strdup_new
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    mv a1, s2
; OLD-NEXT:    call insert
; OLD-NEXT:  .LBB7_10: # %return
; OLD-NEXT:    mv a0, s2
; OLD-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s3, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    addi sp, sp, 48
; OLD-NEXT:    ret
;
; NEW-LABEL: pool_get:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -48
; NEW-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    beqz a1, .LBB7_7
; NEW-NEXT:  # %bb.1: # %if.end
; NEW-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    lbu a1, 0(a1)
; NEW-NEXT:    beqz a1, .LBB7_8
; NEW-NEXT:  # %bb.2: # %for.body.preheader
; NEW-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s3, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    lui a2, 1
; NEW-NEXT:    addi a3, s0, 1
; NEW-NEXT:    addi a2, a2, 1285
; NEW-NEXT:  .LBB7_3: # %for.body
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    add a4, a2, a1
; NEW-NEXT:    lbu a1, 0(a3)
; NEW-NEXT:    slli a2, a2, 5
; NEW-NEXT:    add a2, a2, a4
; NEW-NEXT:    addi a3, a3, 1
; NEW-NEXT:    bnez a1, .LBB7_3
; NEW-NEXT:  # %bb.4: # %for.cond.cleanup
; NEW-NEXT:    ld a1, 8(a0)
; NEW-NEXT:    remu a1, a2, a1
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    ld s3, 0(a0)
; NEW-NEXT:    slli a1, a1, 3
; NEW-NEXT:    add s3, s3, a1
; NEW-NEXT:  .LBB7_5: # %for.cond6
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    ld s3, 0(s3)
; NEW-NEXT:    beqz s3, .LBB7_9
; NEW-NEXT:  # %bb.6: # %for.body9
; NEW-NEXT:    # in Loop: Header=BB7_5 Depth=1
; NEW-NEXT:    ld s2, 8(s3)
; NEW-NEXT:    mv a0, s2
; NEW-NEXT:    mv a1, s0
; NEW-NEXT:    call strcmp
; NEW-NEXT:    bnez a0, .LBB7_5
; NEW-NEXT:    j .LBB7_10
; NEW-NEXT:  .LBB7_7:
; NEW-NEXT:    li s2, 0
; NEW-NEXT:    j .LBB7_11
; NEW-NEXT:  .LBB7_8:
; NEW-NEXT:    lui s2, %hi(.L.str.2)
; NEW-NEXT:    addi s2, s2, %lo(.L.str.2)
; NEW-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:    j .LBB7_11
; NEW-NEXT:  .LBB7_9: # %for.end16
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call strdup_new
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    mv a1, s2
; NEW-NEXT:    call insert
; NEW-NEXT:  .LBB7_10: # %return
; NEW-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s3, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:  .LBB7_11: # %return
; NEW-NEXT:    mv a0, s2
; NEW-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    addi sp, sp, 48
; NEW-NEXT:    ret
;
; NEW-RA-LABEL: pool_get:
; NEW-RA:       # %bb.0: # %entry
; NEW-RA-NEXT:    addi sp, sp, -48
; NEW-RA-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    beqz a1, .LBB7_7
; NEW-RA-NEXT:  # %bb.1: # %if.end
; NEW-RA-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    mv s0, a1
; NEW-RA-NEXT:    lbu a1, 0(a1)
; NEW-RA-NEXT:    beqz a1, .LBB7_8
; NEW-RA-NEXT:  # %bb.2: # %for.body.preheader
; NEW-RA-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    lui a2, 1
; NEW-RA-NEXT:    addi a3, s0, 1
; NEW-RA-NEXT:    addi a2, a2, 1285
; NEW-RA-NEXT:  .LBB7_3: # %for.body
; NEW-RA-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-RA-NEXT:    add a4, a2, a1
; NEW-RA-NEXT:    lbu a1, 0(a3)
; NEW-RA-NEXT:    slli a2, a2, 5
; NEW-RA-NEXT:    add a2, a2, a4
; NEW-RA-NEXT:    addi a3, a3, 1
; NEW-RA-NEXT:    bnez a1, .LBB7_3
; NEW-RA-NEXT:  # %bb.4: # %for.cond.cleanup
; NEW-RA-NEXT:    ld a1, 8(a0)
; NEW-RA-NEXT:    remu a1, a2, a1
; NEW-RA-NEXT:    sd a0, 8(sp) # 8-byte Folded Spill
; NEW-RA-NEXT:    ld s2, 0(a0)
; NEW-RA-NEXT:    slli a1, a1, 3
; NEW-RA-NEXT:    add s2, s2, a1
; NEW-RA-NEXT:  .LBB7_5: # %for.cond6
; NEW-RA-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-RA-NEXT:    ld s2, 0(s2)
; NEW-RA-NEXT:    beqz s2, .LBB7_9
; NEW-RA-NEXT:  # %bb.6: # %for.body9
; NEW-RA-NEXT:    # in Loop: Header=BB7_5 Depth=1
; NEW-RA-NEXT:    ld s1, 8(s2)
; NEW-RA-NEXT:    mv a0, s1
; NEW-RA-NEXT:    mv a1, s0
; NEW-RA-NEXT:    call strcmp
; NEW-RA-NEXT:    bnez a0, .LBB7_5
; NEW-RA-NEXT:    j .LBB7_10
; NEW-RA-NEXT:  .LBB7_7:
; NEW-RA-NEXT:    li s1, 0
; NEW-RA-NEXT:    j .LBB7_11
; NEW-RA-NEXT:  .LBB7_8:
; NEW-RA-NEXT:    lui s1, %hi(.L.str.2)
; NEW-RA-NEXT:    addi s1, s1, %lo(.L.str.2)
; NEW-RA-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    j .LBB7_11
; NEW-RA-NEXT:  .LBB7_9: # %for.end16
; NEW-RA-NEXT:    mv a0, s0
; NEW-RA-NEXT:    call strdup_new
; NEW-RA-NEXT:    mv s1, a0
; NEW-RA-NEXT:    ld a0, 8(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    mv a1, s1
; NEW-RA-NEXT:    call insert
; NEW-RA-NEXT:  .LBB7_10: # %return
; NEW-RA-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:  .LBB7_11: # %return
; NEW-RA-NEXT:    mv a0, s1
; NEW-RA-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; NEW-RA-NEXT:    addi sp, sp, 48
; NEW-RA-NEXT:    ret
entry:
  %tobool.not = icmp eq ptr %s, null
  br i1 %tobool.not, label %return, label %if.end

if.end:                                           ; preds = %entry
  %0 = load i8, ptr %s, align 1
  %tobool1.not = icmp eq i8 %0, 0
  br i1 %tobool1.not, label %return, label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  %1 = load ptr, ptr %p, align 8
  %n5 = getelementptr inbounds nuw i8, ptr %p, i64 8
  %2 = load i64, ptr %n5, align 8
  %rem = urem i64 %add, %2
  %arrayidx = getelementptr inbounds nuw [8 x i8], ptr %1, i64 %rem
  br label %for.cond6

for.body:                                         ; preds = %for.body, %if.end
  %c.035 = phi ptr [ %incdec.ptr, %for.body ], [ %s, %if.end ]
  %h.034 = phi i64 [ %add, %for.body ], [ 5381, %if.end ]
  %3 = phi i8 [ %.pr, %for.body ], [ %0, %if.end ]
  %mul = mul i64 %h.034, 33
  %conv = zext i8 %3 to i64
  %add = add i64 %mul, %conv
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %c.035, i64 1
  %.pr = load i8, ptr %incdec.ptr, align 1
  %tobool4.not = icmp eq i8 %.pr, 0
  br i1 %tobool4.not, label %for.cond.cleanup, label %for.body

for.cond6:                                        ; preds = %for.body9, %for.cond.cleanup
  %n.0.in = phi ptr [ %arrayidx, %for.cond.cleanup ], [ %n.0, %for.body9 ]
  %n.0 = load ptr, ptr %n.0.in, align 8
  %tobool7.not = icmp eq ptr %n.0, null
  br i1 %tobool7.not, label %for.end16, label %for.body9

for.body9:                                        ; preds = %for.cond6
  %s10 = getelementptr inbounds nuw i8, ptr %n.0, i64 8
  %4 = load ptr, ptr %s10, align 8
  %call = tail call signext i32 @strcmp(ptr noundef nonnull dereferenceable(1) %4, ptr noundef nonnull dereferenceable(1) %s) #7
  %cmp = icmp eq i32 %call, 0
  br i1 %cmp, label %return, label %for.cond6

for.end16:                                        ; preds = %for.cond6
  %call17 = tail call ptr @strdup_new(ptr noundef nonnull %s) #7
  tail call void @insert(ptr noundef nonnull %p, ptr noundef %call17) #7
  br label %return

return:                                           ; preds = %for.end16, %for.body9, %if.end, %entry
  %retval.2 = phi ptr [ @.str.2, %if.end ], [ null, %entry ], [ %call17, %for.end16 ], [ %4, %for.body9 ]
  ret ptr %retval.2
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(argmem: read)
declare dso_local signext i32 @strcmp(ptr noundef captures(none), ptr noundef captures(none)) local_unnamed_addr #6

declare dso_local ptr @strdup_new(ptr noundef) local_unnamed_addr

declare dso_local void @insert(ptr noundef, ptr noundef) local_unnamed_addr

attributes #0 = { noinline nounwind }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { noreturn }
attributes #3 = { mustprogress noinline }
attributes #4 = { cold noreturn }
attributes #5 = { nobuiltin nounwind }
attributes #6 = { mustprogress nofree nosync nounwind willreturn memory(argmem: read) }
attributes #7 = { nounwind }
attributes #8 = { noreturn nounwind }

!0 = !{!"branch_weights", !"expected", i32 2000, i32 1}
