; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=OLD
; RUN: llc -mtriple=riscv64 -enable-new-shrink-wrap -verify-machineinstrs \
; RUN:   -verify-cfiinstrs < %s | FileCheck %s --check-prefix=NEW

; Tests for the GCC-style NewShrinkWrap pass, compared to ShrinkWrap.

declare i32 @f(i32)
declare void @g()
declare void @abort() noreturn nounwind

; Early exit: both passes shrink-wrap.
define i32 @early_exit(i32 %x) {
; OLD-LABEL: early_exit:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB0_2
; OLD-NEXT:  # %bb.1: # %work
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    call f
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB0_2:
; OLD-NEXT:    li a0, 0
; OLD-NEXT:    ret
;
; NEW-LABEL: early_exit:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB0_2
; NEW-NEXT:  # %bb.1: # %work
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB0_2:
; NEW-NEXT:    li a0, 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %ret, label %work
work:
  %r = call i32 @f(i32 %x)
  br label %ret
ret:
  %p = phi i32 [0, %entry], [%r, %work]
  ret i32 %p
}

; GCC's loop example: the loop header needs no frame and has an exit. The new
; pass duplicates the header and the exit block, so that the path leaving the
; loop on the first iteration runs without the frame.
define void @loop_exit() {
; OLD-LABEL: loop_exit:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    lw a0, 16(zero)
; OLD-NEXT:    beqz a0, .LBB1_2
; OLD-NEXT:  .LBB1_1: # %body
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    call g
; OLD-NEXT:    lw a0, 16(zero)
; OLD-NEXT:    bnez a0, .LBB1_1
; OLD-NEXT:  .LBB1_2: # %exit
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: loop_exit:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    beqz a0, .LBB1_4
; NEW-NEXT:  # %bb.1: # %body
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call g
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    beqz a0, .LBB1_3
; NEW-NEXT:  .LBB1_2: # %body
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    call g
; NEW-NEXT:    lw a0, 16(zero)
; NEW-NEXT:    bnez a0, .LBB1_2
; NEW-NEXT:  .LBB1_3: # %exit
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:  .LBB1_4: # %exit
; NEW-NEXT:    ret
entry:
  br label %header
header:
  %v = load volatile i32, ptr inttoptr (i64 16 to ptr)
  %c = icmp eq i32 %v, 0
  br i1 %c, label %exit, label %body
body:
  call void @g()
  br label %header
exit:
  ret void
}

; All paths need the frame, but s0/s1/s2 are only used on one path. Separate
; shrink-wrapping saves and restores them only there.
define i32 @separate(i32 %x, i32 %y) {
; OLD-LABEL: separate:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB2_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    mv s2, a0
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call f
; OLD-NEXT:    add s0, s2, s0
; OLD-NEXT:    addw a0, s0, a0
; OLD-NEXT:    j .LBB2_3
; OLD-NEXT:  .LBB2_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB2_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB2_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    mv s2, a0
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call f
; NEW-NEXT:    add s0, s2, s0
; NEW-NEXT:    addw a0, s0, a0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    j .LBB2_3
; NEW-NEXT:  .LBB2_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:  .LBB2_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %r4 = call i32 @f(i32 %r2)
  %s = add i32 %r3, %r4
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; The registers used in the loop are saved before it, not in it.
define i32 @separate_loop(i32 %n, i32 %x) {
; OLD-LABEL: separate_loop:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    sext.w a1, a1
; OLD-NEXT:    beqz a1, .LBB3_4
; OLD-NEXT:  # %bb.1: # %preheader
; OLD-NEXT:    li s1, 0
; OLD-NEXT:    li s0, 0
; OLD-NEXT:    sext.w s2, a0
; OLD-NEXT:  .LBB3_2: # %loop
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call f
; OLD-NEXT:    addiw s1, s1, 1
; OLD-NEXT:    addw s0, s0, a0
; OLD-NEXT:    bne s2, s1, .LBB3_2
; OLD-NEXT:  # %bb.3: # %exit
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    j .LBB3_5
; OLD-NEXT:  .LBB3_4: # %fast
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB3_5: # %exit
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_loop:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a1, a1
; NEW-NEXT:    beqz a1, .LBB3_4
; NEW-NEXT:  # %bb.1: # %preheader
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    li s1, 0
; NEW-NEXT:    li s0, 0
; NEW-NEXT:    sext.w s2, a0
; NEW-NEXT:  .LBB3_2: # %loop
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call f
; NEW-NEXT:    addiw s1, s1, 1
; NEW-NEXT:    addw s0, s0, a0
; NEW-NEXT:    bne s2, s1, .LBB3_2
; NEW-NEXT:  # %bb.3: # %exit
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB3_4: # %fast
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %fast, label %preheader
fast:
  %r0 = call i32 @f(i32 %n)
  ret i32 %r0
preheader:
  br label %loop
loop:
  %i = phi i32 [0, %preheader], [%inc, %loop]
  %acc = phi i32 [0, %preheader], [%acc2, %loop]
  %r = call i32 @f(i32 %i)
  %acc2 = add i32 %acc, %r
  %inc = add i32 %i, 1
  %done = icmp eq i32 %inc, %n
  br i1 %done, label %exit, label %loop
exit:
  ret i32 %acc2
}

; Blocks without successors that are not returns need all registers saved.
define i32 @separate_noreturn(i32 %x, i32 %y) {
; OLD-LABEL: separate_noreturn:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_remember_state
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB4_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    add a0, s1, a0
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB4_3
; OLD-NEXT:  .LBB4_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB4_4
; OLD-NEXT:  .LBB4_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB4_4: # %fail
; OLD-NEXT:    .cfi_restore_state
; OLD-NEXT:    call abort
;
; NEW-LABEL: separate_noreturn:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB4_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    add a0, s1, a0
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    j .LBB4_3
; NEW-NEXT:  .LBB4_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB4_4
; NEW-NEXT:  .LBB4_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB4_4: # %fail
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    call abort
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  %c2 = icmp eq i32 %r1, 0
  br i1 %c2, label %fail, label %ret
fail:
  call void @abort()
  unreachable
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %s = add i32 %r2, %r3
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; s0 is restored on the edge p -> s1, which is split: s1 is also reached
; without s0 saved, and s2 needs s0.
define i32 @separate_split_edge(i32 %x, i32 %y) {
; OLD-LABEL: separate_split_edge:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    beqz a2, .LBB5_3
; OLD-NEXT:  # %bb.1: # %p
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    call f
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB5_3
; OLD-NEXT:  # %bb.2: # %s2
; OLD-NEXT:    call f
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB5_4
; OLD-NEXT:  .LBB5_3: # %s1
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB5_4: # %s1
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_split_edge:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    beqz a2, .LBB5_4
; NEW-NEXT:  # %bb.1: # %p
; NEW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    call f
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB5_3
; NEW-NEXT:  # %bb.2: # %s2
; NEW-NEXT:    call f
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB5_3:
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:  .LBB5_4: # %s1
; NEW-NEXT:    call f
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %s1, label %p
p:
  %r = call i32 @f(i32 %x)
  %c2 = icmp eq i32 %r, 0
  br i1 %c2, label %s1, label %s2
s1:
  %v = phi i32 [%x, %entry], [%r, %p]
  %r1 = call i32 @f(i32 %v)
  ret i32 %r1
s2:
  %r2 = call i32 @f(i32 %r)
  %s = add i32 %r2, %y
  ret i32 %s
}

; Floating-point callee-saved registers are wrapped separately too.
declare double @fd(double)
define double @separate_fpr(i32 %x, double %y) "target-features"="+d" {
; OLD-LABEL: separate_fpr:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -16
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    fsd fs0, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset fs0, -16
; OLD-NEXT:    sext.w a0, a0
; OLD-NEXT:    beqz a0, .LBB6_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    fmv.d fs0, fa0
; OLD-NEXT:    call fd
; OLD-NEXT:    call fd
; OLD-NEXT:    fadd.d fa0, fa0, fs0
; OLD-NEXT:    j .LBB6_3
; OLD-NEXT:  .LBB6_2: # %a
; OLD-NEXT:    call fd
; OLD-NEXT:  .LBB6_3: # %a
; OLD-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    fld fs0, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore fs0
; OLD-NEXT:    addi sp, sp, 16
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_fpr:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -16
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    sext.w a0, a0
; NEW-NEXT:    beqz a0, .LBB6_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    fsd fs0, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset fs0, -16
; NEW-NEXT:    fmv.d fs0, fa0
; NEW-NEXT:    call fd
; NEW-NEXT:    call fd
; NEW-NEXT:    fadd.d fa0, fa0, fs0
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    fld fs0, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore fs0
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB6_2: # %a
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    call fd
; NEW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    addi sp, sp, 16
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call double @fd(double %y)
  ret double %r1
b:
  %r2 = call double @fd(double %y)
  %r3 = call double @fd(double %r2)
  %s = fadd double %r3, %y
  ret double %s
}

; No separate shrink-wrapping when optimizing for size.
define i32 @separate_optsize(i32 %x, i32 %y) optsize {
; OLD-LABEL: separate_optsize:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    sext.w a2, a0
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    beqz a2, .LBB7_2
; OLD-NEXT:  # %bb.1: # %b
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    add a0, s1, a0
; OLD-NEXT:    addw a0, a0, s0
; OLD-NEXT:    j .LBB7_3
; OLD-NEXT:  .LBB7_2: # %a
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:  .LBB7_3: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_optsize:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sext.w a2, a0
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    beqz a2, .LBB7_2
; NEW-NEXT:  # %bb.1: # %b
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    add a0, s1, a0
; NEW-NEXT:    addw a0, a0, s0
; NEW-NEXT:    j .LBB7_3
; NEW-NEXT:  .LBB7_2: # %a
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:  .LBB7_3: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %s = add i32 %r2, %r3
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; The frame is needed on a path that returns and on a path that calls a
; no-return function. The blocks needing the frame have no common
; post-dominator, but the epilogue only goes on the path that returns: the
; early exit runs without the frame.
define void @mixed_exits(ptr %p, ptr %out, i64 %n) {
; OLD-LABEL: mixed_exits:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_remember_state
; OLD-NEXT:    lbu a0, 0(a0)
; OLD-NEXT:    beqz a0, .LBB8_4
; OLD-NEXT:  # %bb.1: # %work
; OLD-NEXT:    mv s0, a2
; OLD-NEXT:    mv s1, a1
; OLD-NEXT:    li a0, 56
; OLD-NEXT:    call f
; OLD-NEXT:    sw a0, 0(s1)
; OLD-NEXT:    bnez s0, .LBB8_4
; OLD-NEXT:  # %bb.2: # %check
; OLD-NEXT:    li a0, 101
; OLD-NEXT:    bgeu s0, a0, .LBB8_5
; OLD-NEXT:  # %bb.3: # %grow
; OLD-NEXT:    call g
; OLD-NEXT:  .LBB8_4: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB8_5: # %fail
; OLD-NEXT:    .cfi_restore_state
; OLD-NEXT:    call abort
;
; NEW-LABEL: mixed_exits:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    lbu a0, 0(a0)
; NEW-NEXT:    beqz a0, .LBB8_5
; NEW-NEXT:  # %bb.1: # %work
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_remember_state
; NEW-NEXT:    mv s0, a2
; NEW-NEXT:    mv s1, a1
; NEW-NEXT:    li a0, 56
; NEW-NEXT:    call f
; NEW-NEXT:    sw a0, 0(s1)
; NEW-NEXT:    bnez s0, .LBB8_4
; NEW-NEXT:  # %bb.2: # %check
; NEW-NEXT:    li a0, 101
; NEW-NEXT:    bgeu s0, a0, .LBB8_6
; NEW-NEXT:  # %bb.3: # %grow
; NEW-NEXT:    call g
; NEW-NEXT:  .LBB8_4: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:  .LBB8_5: # %ret
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB8_6: # %fail
; NEW-NEXT:    .cfi_restore_state
; NEW-NEXT:    call abort
entry:
  %flag = load i8, ptr %p
  %c = icmp eq i8 %flag, 0
  br i1 %c, label %ret, label %work
work:
  %r = call i32 @f(i32 56)
  store i32 %r, ptr %out
  %full = icmp eq i64 %n, 0
  br i1 %full, label %check, label %ret
check:
  %big = icmp ugt i64 %n, 100
  br i1 %big, label %fail, label %grow
fail:
  call void @abort()
  unreachable
grow:
  call void @g()
  br label %ret
ret:
  ret void
}

; Like mixed_exits, but the no-return path needing the frame starts after the
; join of the paths that return. The epilogue cannot go in the join block,
; which the no-return path is reached from; it goes in the return block.
define void @mixed_exits_after_join(ptr %p, i32 %x, i32 %y) {
; OLD-LABEL: mixed_exits_after_join:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_remember_state
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    lbu a0, 0(a0)
; OLD-NEXT:    beqz a0, .LBB9_4
; OLD-NEXT:  # %bb.1: # %work
; OLD-NEXT:    mv s0, a2
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    call f
; OLD-NEXT:    sext.w a1, a0
; OLD-NEXT:    beqz a1, .LBB9_3
; OLD-NEXT:  # %bb.2: # %other
; OLD-NEXT:    sw a0, 0(s1)
; OLD-NEXT:  .LBB9_3: # %join
; OLD-NEXT:    sext.w s0, s0
; OLD-NEXT:    beqz s0, .LBB9_5
; OLD-NEXT:  .LBB9_4: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
; OLD-NEXT:  .LBB9_5: # %fail
; OLD-NEXT:    .cfi_restore_state
; OLD-NEXT:    call abort
;
; NEW-LABEL: mixed_exits_after_join:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    mv a3, a0
; NEW-NEXT:    lbu a0, 0(a0)
; NEW-NEXT:    beqz a0, .LBB9_5
; NEW-NEXT:  # %bb.1: # %work
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_remember_state
; NEW-NEXT:    mv s1, a3
; NEW-NEXT:    mv s0, a2
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    call f
; NEW-NEXT:    sext.w a1, a0
; NEW-NEXT:    beqz a1, .LBB9_3
; NEW-NEXT:  # %bb.2: # %other
; NEW-NEXT:    sw a0, 0(s1)
; NEW-NEXT:  .LBB9_3: # %join
; NEW-NEXT:    sext.w s0, s0
; NEW-NEXT:    beqz s0, .LBB9_6
; NEW-NEXT:  # %bb.4: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:  .LBB9_5: # %ret
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB9_6: # %fail
; NEW-NEXT:    .cfi_restore_state
; NEW-NEXT:    call abort
entry:
  %flag = load i8, ptr %p
  %c = icmp eq i8 %flag, 0
  br i1 %c, label %ret, label %work
work:
  %r = call i32 @f(i32 %x)
  %c1 = icmp eq i32 %r, 0
  br i1 %c1, label %join, label %other
other:
  store i32 %r, ptr %p
  br label %join
join:
  %c2 = icmp eq i32 %y, 0
  br i1 %c2, label %fail, label %ret
fail:
  call void @abort()
  unreachable
ret:
  ret void
}

; The load in %join uses an address that is not known to be outside the
; stack, and %join is reached after %cold passes the address of %list to a
; call. The load needs the frame only on the paths through %cold, as no
; stack address exists on the other paths. So %join does not keep the
; prologue in the entry block: it is duplicated, and the hot path through
; %entry and %join runs without the frame (Stockfish's Position::is_draw).
declare ptr @gen(ptr, ptr)
define i32 @stack_use_join(ptr %pos, i32 %ply) {
; OLD-LABEL: stack_use_join:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -2032
; OLD-NEXT:    .cfi_def_cfa_offset 2032
; OLD-NEXT:    sd ra, 2024(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 2016(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 2008(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 2000(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    addi sp, sp, -64
; OLD-NEXT:    .cfi_def_cfa_offset 2096
; OLD-NEXT:    ld a2, 0(a0)
; OLD-NEXT:    lw a3, 0(a2)
; OLD-NEXT:    li a4, 100
; OLD-NEXT:    blt a3, a4, .LBB10_4
; OLD-NEXT:  # %bb.1: # %cold
; OLD-NEXT:    mv s0, a1
; OLD-NEXT:    addi a1, sp, 16
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    addi s2, sp, 16
; OLD-NEXT:    call gen
; OLD-NEXT:    beq a0, s2, .LBB10_3
; OLD-NEXT:  # %bb.2:
; OLD-NEXT:    li a0, 1
; OLD-NEXT:    j .LBB10_5
; OLD-NEXT:  .LBB10_3: # %reload
; OLD-NEXT:    ld a2, 0(s1)
; OLD-NEXT:    mv a1, s0
; OLD-NEXT:  .LBB10_4: # %join
; OLD-NEXT:    lw a0, 164(a2)
; OLD-NEXT:    sext.w a1, a1
; OLD-NEXT:    slt a1, a0, a1
; OLD-NEXT:    snez a0, a0
; OLD-NEXT:    and a0, a1, a0
; OLD-NEXT:  .LBB10_5: # %ret
; OLD-NEXT:    addi sp, sp, 64
; OLD-NEXT:    .cfi_def_cfa_offset 2032
; OLD-NEXT:    ld ra, 2024(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 2016(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 2008(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 2000(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 2032
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: stack_use_join:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    ld a2, 0(a0)
; NEW-NEXT:    lw a3, 0(a2)
; NEW-NEXT:    li a4, 100
; NEW-NEXT:    blt a3, a4, .LBB10_3
; NEW-NEXT:  # %bb.1: # %cold
; NEW-NEXT:    addi sp, sp, -2032
; NEW-NEXT:    .cfi_def_cfa_offset 2032
; NEW-NEXT:    sd ra, 2024(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 2016(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s1, 2008(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s2, 2000(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    addi sp, sp, -64
; NEW-NEXT:    .cfi_def_cfa_offset 2096
; NEW-NEXT:    .cfi_remember_state
; NEW-NEXT:    mv s0, a1
; NEW-NEXT:    addi a1, sp, 16
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    addi s2, sp, 16
; NEW-NEXT:    call gen
; NEW-NEXT:    beq a0, s2, .LBB10_4
; NEW-NEXT:  # %bb.2:
; NEW-NEXT:    li a0, 1
; NEW-NEXT:    j .LBB10_5
; NEW-NEXT:  .LBB10_3: # %join
; NEW-NEXT:    lw a0, 164(a2)
; NEW-NEXT:    sext.w a1, a1
; NEW-NEXT:    slt a1, a0, a1
; NEW-NEXT:    snez a0, a0
; NEW-NEXT:    and a0, a1, a0
; NEW-NEXT:    ret
; NEW-NEXT:  .LBB10_4: # %reload
; NEW-NEXT:    .cfi_restore_state
; NEW-NEXT:    ld a2, 0(s1)
; NEW-NEXT:    lw a0, 164(a2)
; NEW-NEXT:    sext.w a1, s0
; NEW-NEXT:    slt a1, a0, a1
; NEW-NEXT:    snez a0, a0
; NEW-NEXT:    and a0, a1, a0
; NEW-NEXT:  .LBB10_5: # %ret
; NEW-NEXT:    addi sp, sp, 64
; NEW-NEXT:    .cfi_def_cfa_offset 2032
; NEW-NEXT:    ld ra, 2024(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 2016(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s1, 2008(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s2, 2000(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    addi sp, sp, 2032
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  %list = alloca [256 x i64]
  %st = load ptr, ptr %pos
  %r50 = load i32, ptr %st
  %big = icmp sgt i32 %r50, 99
  br i1 %big, label %cold, label %join
cold:
  %last = call ptr @gen(ptr %pos, ptr %list)
  %empty = icmp eq ptr %last, %list
  br i1 %empty, label %reload, label %ret
reload:
  %st2 = load ptr, ptr %pos
  br label %join
join:
  %s = phi ptr [%st, %entry], [%st2, %reload]
  %rep.p = getelementptr i8, ptr %s, i64 164
  %rep = load i32, ptr %rep.p
  %lt = icmp slt i32 %rep, %ply
  %nz = icmp ne i32 %rep, 0
  %a = and i1 %lt, %nz
  %z = zext i1 %a to i32
  br label %ret
ret:
  %r = phi i32 [1, %cold], [%z, %join]
  ret i32 %r
}

; %big is reached from the jump table, without s1/s2, and from %other, with
; them. Their saves go on the edge from the jump table, which is split by
; replacing %big in the jump table (SEAL's dot_product_mod).
define i32 @separate_jump_table(i32 %n, i32 %x, i32 %y) {
; OLD-LABEL: separate_jump_table:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    addi sp, sp, -32
; OLD-NEXT:    .cfi_def_cfa_offset 32
; OLD-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; OLD-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; OLD-NEXT:    .cfi_offset ra, -8
; OLD-NEXT:    .cfi_offset s0, -16
; OLD-NEXT:    .cfi_offset s1, -24
; OLD-NEXT:    .cfi_offset s2, -32
; OLD-NEXT:    mv s0, a2
; OLD-NEXT:    sext.w a0, a0
; OLD-NEXT:    li a2, 4
; OLD-NEXT:    bltu a2, a0, .LBB11_6
; OLD-NEXT:  # %bb.1: # %entry
; OLD-NEXT:    slli a0, a0, 2
; OLD-NEXT:    lui a2, %hi(.LJTI11_0)
; OLD-NEXT:    addi a2, a2, %lo(.LJTI11_0)
; OLD-NEXT:    add a0, a2, a0
; OLD-NEXT:    lw a0, 0(a0)
; OLD-NEXT:    jr a0
; OLD-NEXT:  .LBB11_2: # %a
; OLD-NEXT:    addiw a0, a1, 1
; OLD-NEXT:    j .LBB11_8
; OLD-NEXT:  .LBB11_3: # %d
; OLD-NEXT:    xor a0, a1, s0
; OLD-NEXT:    j .LBB11_8
; OLD-NEXT:  .LBB11_4: # %b
; OLD-NEXT:    or a0, a1, s0
; OLD-NEXT:    j .LBB11_8
; OLD-NEXT:  .LBB11_5: # %c
; OLD-NEXT:    subw a0, a1, s0
; OLD-NEXT:    j .LBB11_8
; OLD-NEXT:  .LBB11_6: # %other
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    call f
; OLD-NEXT:    addw a1, a0, s0
; OLD-NEXT:  .LBB11_7: # %big
; OLD-NEXT:    mv a0, a1
; OLD-NEXT:    mv s2, a1
; OLD-NEXT:    call f
; OLD-NEXT:    mv s1, a0
; OLD-NEXT:    mv a0, s0
; OLD-NEXT:    call f
; OLD-NEXT:    mv s0, a0
; OLD-NEXT:    mv a0, s1
; OLD-NEXT:    call f
; OLD-NEXT:    add s0, s0, s2
; OLD-NEXT:    addw a0, s0, a0
; OLD-NEXT:  .LBB11_8: # %ret
; OLD-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; OLD-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; OLD-NEXT:    .cfi_restore ra
; OLD-NEXT:    .cfi_restore s0
; OLD-NEXT:    .cfi_restore s1
; OLD-NEXT:    .cfi_restore s2
; OLD-NEXT:    addi sp, sp, 32
; OLD-NEXT:    .cfi_def_cfa_offset 0
; OLD-NEXT:    ret
;
; NEW-LABEL: separate_jump_table:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    addi sp, sp, -32
; NEW-NEXT:    .cfi_def_cfa_offset 32
; NEW-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; NEW-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset ra, -8
; NEW-NEXT:    .cfi_offset s0, -16
; NEW-NEXT:    mv s0, a2
; NEW-NEXT:    sext.w a0, a0
; NEW-NEXT:    li a2, 4
; NEW-NEXT:    bltu a2, a0, .LBB11_7
; NEW-NEXT:  # %bb.1: # %entry
; NEW-NEXT:    slli a0, a0, 2
; NEW-NEXT:    lui a2, %hi(.LJTI11_0)
; NEW-NEXT:    addi a2, a2, %lo(.LJTI11_0)
; NEW-NEXT:    add a0, a2, a0
; NEW-NEXT:    lw a0, 0(a0)
; NEW-NEXT:    jr a0
; NEW-NEXT:  .LBB11_2: # %a
; NEW-NEXT:    addiw a0, a1, 1
; NEW-NEXT:    j .LBB11_9
; NEW-NEXT:  .LBB11_3:
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    j .LBB11_8
; NEW-NEXT:  .LBB11_4: # %c
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:    subw a0, a1, s0
; NEW-NEXT:    j .LBB11_9
; NEW-NEXT:  .LBB11_5: # %d
; NEW-NEXT:    xor a0, a1, s0
; NEW-NEXT:    j .LBB11_9
; NEW-NEXT:  .LBB11_6: # %b
; NEW-NEXT:    or a0, a1, s0
; NEW-NEXT:    j .LBB11_9
; NEW-NEXT:  .LBB11_7: # %other
; NEW-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s1, -24
; NEW-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; NEW-NEXT:    .cfi_offset s2, -32
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    call f
; NEW-NEXT:    addw a1, a0, s0
; NEW-NEXT:  .LBB11_8: # %big
; NEW-NEXT:    mv a0, a1
; NEW-NEXT:    mv s2, a1
; NEW-NEXT:    call f
; NEW-NEXT:    mv s1, a0
; NEW-NEXT:    mv a0, s0
; NEW-NEXT:    call f
; NEW-NEXT:    mv s0, a0
; NEW-NEXT:    mv a0, s1
; NEW-NEXT:    call f
; NEW-NEXT:    add s0, s0, s2
; NEW-NEXT:    addw a0, s0, a0
; NEW-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s1
; NEW-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore s2
; NEW-NEXT:  .LBB11_9: # %ret
; NEW-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; NEW-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; NEW-NEXT:    .cfi_restore ra
; NEW-NEXT:    .cfi_restore s0
; NEW-NEXT:    addi sp, sp, 32
; NEW-NEXT:    .cfi_def_cfa_offset 0
; NEW-NEXT:    ret
entry:
  switch i32 %n, label %other [
    i32 0, label %a
    i32 1, label %b
    i32 2, label %c
    i32 3, label %d
    i32 4, label %big
  ]
a:
  %ra = add i32 %x, 1
  br label %ret
b:
  %rb = or i32 %x, %y
  br label %ret
c:
  %rc = sub i32 %x, %y
  br label %ret
d:
  %rd = xor i32 %x, %y
  br label %ret
other:
  %o1 = call i32 @f(i32 %x)
  %o2 = add i32 %o1, %y
  br label %big
big:
  %v = phi i32 [ %x, %entry ], [ %o2, %other ]
  %b1 = call i32 @f(i32 %v)
  %b2 = call i32 @f(i32 %y)
  %b3 = call i32 @f(i32 %b1)
  %s1 = add i32 %b2, %b3
  %s2 = add i32 %s1, %v
  br label %ret
ret:
  %r = phi i32 [ %ra, %a ], [ %rb, %b ], [ %rc, %c ], [ %rd, %d ], [ %s2, %big ]
  ret i32 %r
}
