; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -enable-new-shrink-wrap \
; RUN:   -verify-machineinstrs -verify-cfiinstrs < %s | FileCheck %s

; Separate shrink-wrapping of callee-saved registers with the V extension.

declare i32 @f(i32)

; The function has no scalable stack objects, so s0/s1/s2 are saved and
; restored only on the path that uses them, like without the V extension.
define i32 @separate(i32 %x, i32 %y) {
; CHECK-LABEL: separate:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    sext.w a2, a0
; CHECK-NEXT:    mv s0, a1
; CHECK-NEXT:    beqz a2, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %b
; CHECK-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s1, -24
; CHECK-NEXT:    .cfi_offset s2, -32
; CHECK-NEXT:    call f
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    mv a0, s0
; CHECK-NEXT:    call f
; CHECK-NEXT:    mv s2, a0
; CHECK-NEXT:    mv a0, s1
; CHECK-NEXT:    call f
; CHECK-NEXT:    add s0, s2, s0
; CHECK-NEXT:    addw a0, s0, a0
; CHECK-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_2: # %a
; CHECK-NEXT:    mv a0, s0
; CHECK-NEXT:    call f
; CHECK-NEXT:  .LBB0_3: # %ret
; CHECK-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %r4 = call i32 @f(i32 %r2)
  %s = add i32 %r3, %r4
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  ret i32 %p
}

; A scalable vector is spilled across the calls, so the offsets of the spill
; slots of s0/s1/s2 are scalable: they are saved in the prologue.
define <vscale x 2 x i64> @separate_rvv_spill(i32 %x, i32 %y, <vscale x 2 x i64> %v) {
; CHECK-LABEL: separate_rvv_spill:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    .cfi_offset s1, -24
; CHECK-NEXT:    .cfi_offset s2, -32
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a2, a2, 1
; CHECK-NEXT:    sub sp, sp, a2
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x30, 0x22, 0x11, 0x02, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 48 + 2 * vlenb
; CHECK-NEXT:    addi a2, sp, 16
; CHECK-NEXT:    vs2r.v v8, (a2) # vscale x 16-byte Folded Spill
; CHECK-NEXT:    sext.w a2, a0
; CHECK-NEXT:    mv s0, a1
; CHECK-NEXT:    beqz a2, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %b
; CHECK-NEXT:    call f
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    mv a0, s0
; CHECK-NEXT:    call f
; CHECK-NEXT:    mv s2, a0
; CHECK-NEXT:    mv a0, s1
; CHECK-NEXT:    call f
; CHECK-NEXT:    add s0, s2, s0
; CHECK-NEXT:    add a0, s0, a0
; CHECK-NEXT:    j .LBB1_3
; CHECK-NEXT:  .LBB1_2: # %a
; CHECK-NEXT:    mv a0, s0
; CHECK-NEXT:    call f
; CHECK-NEXT:  .LBB1_3: # %ret
; CHECK-NEXT:    sext.w a0, a0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl2r.v v8, (a1) # vscale x 16-byte Folded Reload
; CHECK-NEXT:    vsetvli a1, zero, e64, m2, ta, ma
; CHECK-NEXT:    vadd.vx v8, v8, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 1
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 48
; CHECK-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    addi sp, sp, 48
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  %r1 = call i32 @f(i32 %y)
  br label %ret
b:
  %r2 = call i32 @f(i32 %x)
  %r3 = call i32 @f(i32 %y)
  %r4 = call i32 @f(i32 %r2)
  %s = add i32 %r3, %r4
  %s2 = add i32 %s, %y
  br label %ret
ret:
  %p = phi i32 [%r1, %a], [%s2, %b]
  %e = sext i32 %p to i64
  %ins = insertelement <vscale x 2 x i64> poison, i64 %e, i64 0
  %splat = shufflevector <vscale x 2 x i64> %ins, <vscale x 2 x i64> poison,
                         <vscale x 2 x i32> zeroinitializer
  %r = add <vscale x 2 x i64> %v, %splat
  ret <vscale x 2 x i64> %r
}
