; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -O2 -regalloc-csr-first-time-cost=32768 < %s | FileCheck %s

; x is live across calls only on a path that ends in a no-return call. Its
; spill on that path costs less than the first use of a CSR, which would save
; and restore the CSR on every call of the function.

define dso_local i64 @spill_cold(i64 noundef %x, i64 noundef %y, ptr nofree noundef readonly captures(none) %p) local_unnamed_addr {
; CHECK-LABEL: spill_cold:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a1, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %if.end
; CHECK-NEXT:    ld a1, 0(a2)
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2: # %if.then
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    sd a0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    li a1, 2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    call cold_use
; CHECK-NEXT:    li a1, 4
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    ld a0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    call cold_use
; CHECK-NEXT:    ld a0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    call fail
entry:
  %cmp = icmp eq i64 %y, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @cold_use(i64 noundef 1, i64 noundef 2, i64 noundef 3)
  tail call void @cold_use(i64 noundef %x, i64 noundef 4, i64 noundef 5)
  tail call void @fail(i64 noundef %x)
  unreachable

if.end:                                           ; preds = %entry
  %0 = load i64, ptr %p, align 8
  %add = add nsw i64 %0, %x
  ret i64 %add
}
declare void @cold_use(i64 noundef, i64 noundef, i64 noundef) local_unnamed_addr
declare void @fail(i64 noundef) local_unnamed_addr
