; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -O3 -regalloc-csr-first-time-cost=32768 \
; RUN:   -regalloc-csr-split-loop-factor=1 < %s | FileCheck %s --check-prefix=FACTOR1
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -O3 -regalloc-csr-first-time-cost=32768 \
; RUN:   < %s | FileCheck %s --check-prefix=DEFAULT

; Reduced from sqlite3VdbeRecordCompareWithSkip (SPEC 708.sqlite_r). The loop
; values are live across a call in the loop, which the static frequencies say
; is cold. With factor 1, each value is pre-split around the call, and the
; pieces across the call get CSRs anyway, so the copies gain nothing. The
; default factor keeps the values in CSRs.

define fastcc signext i32 @split_around_call_in_loop(i32 signext %nKey1, ptr %pKey1, ptr %pPKey2, i1 %tobool.not.i, i8 %retval.0.i, i8 %narrow, i8 %0, i1 %cmp24, i64 %indvars.iv.next, i32 %add306, i32 %1, i32 %add309, i32 %idx1.1, i1 %cmp35, i1 %cmp.i137, i1 %cmp4.i, i32 %conv9) {
; FACTOR1-LABEL: split_around_call_in_loop:
; FACTOR1:       # %bb.0: # %entry
; FACTOR1-NEXT:    addi sp, sp, -128
; FACTOR1-NEXT:    .cfi_def_cfa_offset 128
; FACTOR1-NEXT:    sd ra, 120(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s0, 112(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s1, 104(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s2, 96(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s3, 88(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s4, 80(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s5, 72(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s6, 64(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd s7, 56(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    .cfi_offset ra, -8
; FACTOR1-NEXT:    .cfi_offset s0, -16
; FACTOR1-NEXT:    .cfi_offset s1, -24
; FACTOR1-NEXT:    .cfi_offset s2, -32
; FACTOR1-NEXT:    .cfi_offset s3, -40
; FACTOR1-NEXT:    .cfi_offset s4, -48
; FACTOR1-NEXT:    .cfi_offset s5, -56
; FACTOR1-NEXT:    .cfi_offset s6, -64
; FACTOR1-NEXT:    .cfi_offset s7, -72
; FACTOR1-NEXT:    andi a5, a3, 1
; FACTOR1-NEXT:    bnez a5, .LBB0_2
; FACTOR1-NEXT:  # %bb.1: # %if.end.i
; FACTOR1-NEXT:    li a3, 0
; FACTOR1-NEXT:    mv s0, a0
; FACTOR1-NEXT:    li a0, 0
; FACTOR1-NEXT:    mv s1, a1
; FACTOR1-NEXT:    li a1, 0
; FACTOR1-NEXT:    mv s2, t5
; FACTOR1-NEXT:    mv s5, t4
; FACTOR1-NEXT:    mv s3, a2
; FACTOR1-NEXT:    mv s6, a4
; FACTOR1-NEXT:    mv s4, a7
; FACTOR1-NEXT:    mv s7, a5
; FACTOR1-NEXT:    jalr a3
; FACTOR1-NEXT:    mv a5, s7
; FACTOR1-NEXT:    mv a7, s4
; FACTOR1-NEXT:    mv a4, s6
; FACTOR1-NEXT:    mv a0, s0
; FACTOR1-NEXT:    mv a1, s1
; FACTOR1-NEXT:    mv a2, s3
; FACTOR1-NEXT:    mv t4, s5
; FACTOR1-NEXT:    mv t5, s2
; FACTOR1-NEXT:  .LBB0_2: # %cond.end
; FACTOR1-NEXT:    beqz a5, .LBB0_4
; FACTOR1-NEXT:  .LBB0_3: # %if.then26
; FACTOR1-NEXT:    li a0, 0
; FACTOR1-NEXT:    j .LBB0_22
; FACTOR1-NEXT:  .LBB0_4: # %do.body.preheader
; FACTOR1-NEXT:    ld s1, 136(sp)
; FACTOR1-NEXT:    lw s5, 128(sp)
; FACTOR1-NEXT:    ld s0, 152(sp)
; FACTOR1-NEXT:    ld t2, 144(sp)
; FACTOR1-NEXT:    zext.b t3, a4
; FACTOR1-NEXT:    li a3, 0
; FACTOR1-NEXT:    andi s6, a7, 1
; FACTOR1-NEXT:    sext.w s2, t4
; FACTOR1-NEXT:    lw a6, 160(sp)
; FACTOR1-NEXT:    li t6, 7
; FACTOR1-NEXT:    li s7, 1
; FACTOR1-NEXT:    andi a4, s1, 1
; FACTOR1-NEXT:    andi t2, t2, 1
; FACTOR1-NEXT:    andi s4, s0, 1
; FACTOR1-NEXT:    sd a4, 48(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    li a4, 0
; FACTOR1-NEXT:  .LBB0_5: # %do.body
; FACTOR1-NEXT:    # =>This Inner Loop Header: Depth=1
; FACTOR1-NEXT:    bnez a3, .LBB0_12
; FACTOR1-NEXT:  # %bb.6: # %if.then32
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez a5, .LBB0_21
; FACTOR1-NEXT:  # %bb.7: # %if.else38
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bne t3, t6, .LBB0_20
; FACTOR1-NEXT:  # %bb.8: # %if.then45
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    sh s7, 0(zero)
; FACTOR1-NEXT:    bnez t2, .LBB0_21
; FACTOR1-NEXT:  # %bb.9: # %if.end.i138
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez s4, .LBB0_21
; FACTOR1-NEXT:  # %bb.10: # %if.end7.i
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez s6, .LBB0_21
; FACTOR1-NEXT:  # %bb.11: # %if.end11.i
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    beqz a5, .LBB0_18
; FACTOR1-NEXT:    j .LBB0_21
; FACTOR1-NEXT:  .LBB0_12: # %if.else68
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez a5, .LBB0_18
; FACTOR1-NEXT:  # %bb.13: # %if.then116
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    ld a6, 48(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    bnez a6, .LBB0_21
; FACTOR1-NEXT:  # %bb.14: # %if.else130
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez s6, .LBB0_21
; FACTOR1-NEXT:  # %bb.15: # %if.else134
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bnez a5, .LBB0_3
; FACTOR1-NEXT:  # %bb.16: # %lor.lhs.false
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    beqz a5, .LBB0_3
; FACTOR1-NEXT:  # %bb.17: # %if.else148
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    add.uw a4, a4, a1
; FACTOR1-NEXT:    sd a0, 32(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd a1, 24(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd a2, 16(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    sd t5, 8(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    mv a0, a4
; FACTOR1-NEXT:    mv a1, a2
; FACTOR1-NEXT:    mv a2, a3
; FACTOR1-NEXT:    sd t3, 40(sp) # 8-byte Folded Spill
; FACTOR1-NEXT:    mv s3, t4
; FACTOR1-NEXT:    mv s1, a3
; FACTOR1-NEXT:    mv s0, a5
; FACTOR1-NEXT:    mv s7, t2
; FACTOR1-NEXT:    jalr a3
; FACTOR1-NEXT:    ld t3, 40(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    lw a6, 160(sp)
; FACTOR1-NEXT:    mv t2, s7
; FACTOR1-NEXT:    li s7, 1
; FACTOR1-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld a1, 24(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld a2, 16(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld t5, 8(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    li t6, 7
; FACTOR1-NEXT:    mv a5, s0
; FACTOR1-NEXT:    mv a3, s1
; FACTOR1-NEXT:    mv t4, s3
; FACTOR1-NEXT:  .LBB0_18: # %if.end270
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    bgeu a6, s5, .LBB0_3
; FACTOR1-NEXT:  # %bb.19: # %if.end270
; FACTOR1-NEXT:    # in Loop: Header=BB0_5 Depth=1
; FACTOR1-NEXT:    mv a4, t4
; FACTOR1-NEXT:    bgeu a0, s2, .LBB0_5
; FACTOR1-NEXT:    j .LBB0_3
; FACTOR1-NEXT:  .LBB0_20: # %if.else38
; FACTOR1-NEXT:    bnez t3, .LBB0_3
; FACTOR1-NEXT:  .LBB0_21: # %if.then273.loopexit372
; FACTOR1-NEXT:    sext.w a0, t5
; FACTOR1-NEXT:  .LBB0_22: # %if.then26
; FACTOR1-NEXT:    ld ra, 120(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s0, 112(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s1, 104(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s2, 96(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s3, 88(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s4, 80(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s5, 72(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s6, 64(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    ld s7, 56(sp) # 8-byte Folded Reload
; FACTOR1-NEXT:    .cfi_restore ra
; FACTOR1-NEXT:    .cfi_restore s0
; FACTOR1-NEXT:    .cfi_restore s1
; FACTOR1-NEXT:    .cfi_restore s2
; FACTOR1-NEXT:    .cfi_restore s3
; FACTOR1-NEXT:    .cfi_restore s4
; FACTOR1-NEXT:    .cfi_restore s5
; FACTOR1-NEXT:    .cfi_restore s6
; FACTOR1-NEXT:    .cfi_restore s7
; FACTOR1-NEXT:    addi sp, sp, 128
; FACTOR1-NEXT:    .cfi_def_cfa_offset 0
; FACTOR1-NEXT:    ret
;
; DEFAULT-LABEL: split_around_call_in_loop:
; DEFAULT:       # %bb.0: # %entry
; DEFAULT-NEXT:    addi sp, sp, -128
; DEFAULT-NEXT:    .cfi_def_cfa_offset 128
; DEFAULT-NEXT:    sd ra, 120(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s0, 112(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s1, 104(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s2, 96(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s3, 88(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s4, 80(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s5, 72(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s6, 64(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s7, 56(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s8, 48(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s9, 40(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd s10, 32(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    .cfi_offset ra, -8
; DEFAULT-NEXT:    .cfi_offset s0, -16
; DEFAULT-NEXT:    .cfi_offset s1, -24
; DEFAULT-NEXT:    .cfi_offset s2, -32
; DEFAULT-NEXT:    .cfi_offset s3, -40
; DEFAULT-NEXT:    .cfi_offset s4, -48
; DEFAULT-NEXT:    .cfi_offset s5, -56
; DEFAULT-NEXT:    .cfi_offset s6, -64
; DEFAULT-NEXT:    .cfi_offset s7, -72
; DEFAULT-NEXT:    .cfi_offset s8, -80
; DEFAULT-NEXT:    .cfi_offset s9, -88
; DEFAULT-NEXT:    .cfi_offset s10, -96
; DEFAULT-NEXT:    mv s0, t4
; DEFAULT-NEXT:    mv s1, a0
; DEFAULT-NEXT:    andi s3, a3, 1
; DEFAULT-NEXT:    sd t5, 8(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd a2, 24(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    sd a1, 16(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    bnez s3, .LBB0_2
; DEFAULT-NEXT:  # %bb.1: # %if.end.i
; DEFAULT-NEXT:    li a0, 0
; DEFAULT-NEXT:    li a1, 0
; DEFAULT-NEXT:    mv s2, a4
; DEFAULT-NEXT:    mv s4, a7
; DEFAULT-NEXT:    jalr a0
; DEFAULT-NEXT:    mv a7, s4
; DEFAULT-NEXT:    mv a4, s2
; DEFAULT-NEXT:  .LBB0_2: # %cond.end
; DEFAULT-NEXT:    beqz s3, .LBB0_4
; DEFAULT-NEXT:  .LBB0_3: # %if.then26
; DEFAULT-NEXT:    li a0, 0
; DEFAULT-NEXT:    j .LBB0_22
; DEFAULT-NEXT:  .LBB0_4: # %do.body.preheader
; DEFAULT-NEXT:    ld a0, 136(sp)
; DEFAULT-NEXT:    lw s5, 128(sp)
; DEFAULT-NEXT:    ld a1, 152(sp)
; DEFAULT-NEXT:    ld a2, 144(sp)
; DEFAULT-NEXT:    li s2, 0
; DEFAULT-NEXT:    andi s6, a7, 1
; DEFAULT-NEXT:    sext.w s8, s0
; DEFAULT-NEXT:    zext.b s7, a4
; DEFAULT-NEXT:    lw s4, 160(sp)
; DEFAULT-NEXT:    andi a0, a0, 1
; DEFAULT-NEXT:    andi s9, a2, 1
; DEFAULT-NEXT:    andi s10, a1, 1
; DEFAULT-NEXT:    sd a0, 0(sp) # 8-byte Folded Spill
; DEFAULT-NEXT:    li a0, 0
; DEFAULT-NEXT:  .LBB0_5: # %do.body
; DEFAULT-NEXT:    # =>This Inner Loop Header: Depth=1
; DEFAULT-NEXT:    bnez s2, .LBB0_12
; DEFAULT-NEXT:  # %bb.6: # %if.then32
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s3, .LBB0_21
; DEFAULT-NEXT:  # %bb.7: # %if.else38
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    li a0, 7
; DEFAULT-NEXT:    bne s7, a0, .LBB0_20
; DEFAULT-NEXT:  # %bb.8: # %if.then45
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    li a0, 1
; DEFAULT-NEXT:    sh a0, 0(zero)
; DEFAULT-NEXT:    bnez s9, .LBB0_21
; DEFAULT-NEXT:  # %bb.9: # %if.end.i138
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s10, .LBB0_21
; DEFAULT-NEXT:  # %bb.10: # %if.end7.i
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s6, .LBB0_21
; DEFAULT-NEXT:  # %bb.11: # %if.end11.i
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    beqz s3, .LBB0_18
; DEFAULT-NEXT:    j .LBB0_21
; DEFAULT-NEXT:  .LBB0_12: # %if.else68
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s3, .LBB0_18
; DEFAULT-NEXT:  # %bb.13: # %if.then116
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    ld a1, 0(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    bnez a1, .LBB0_21
; DEFAULT-NEXT:  # %bb.14: # %if.else130
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s6, .LBB0_21
; DEFAULT-NEXT:  # %bb.15: # %if.else134
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bnez s3, .LBB0_3
; DEFAULT-NEXT:  # %bb.16: # %lor.lhs.false
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    beqz s3, .LBB0_3
; DEFAULT-NEXT:  # %bb.17: # %if.else148
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    ld a1, 16(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    mv a2, s2
; DEFAULT-NEXT:    add.uw a0, a0, a1
; DEFAULT-NEXT:    ld a1, 24(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    jalr s2
; DEFAULT-NEXT:  .LBB0_18: # %if.end270
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    bgeu s4, s5, .LBB0_3
; DEFAULT-NEXT:  # %bb.19: # %if.end270
; DEFAULT-NEXT:    # in Loop: Header=BB0_5 Depth=1
; DEFAULT-NEXT:    mv a0, s0
; DEFAULT-NEXT:    bgeu s1, s8, .LBB0_5
; DEFAULT-NEXT:    j .LBB0_3
; DEFAULT-NEXT:  .LBB0_20: # %if.else38
; DEFAULT-NEXT:    bnez s7, .LBB0_3
; DEFAULT-NEXT:  .LBB0_21: # %if.then273.loopexit372
; DEFAULT-NEXT:    lw a0, 8(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:  .LBB0_22: # %if.then26
; DEFAULT-NEXT:    ld ra, 120(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s0, 112(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s1, 104(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s2, 96(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s3, 88(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s4, 80(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s5, 72(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s6, 64(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s7, 56(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s8, 48(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s9, 40(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    ld s10, 32(sp) # 8-byte Folded Reload
; DEFAULT-NEXT:    .cfi_restore ra
; DEFAULT-NEXT:    .cfi_restore s0
; DEFAULT-NEXT:    .cfi_restore s1
; DEFAULT-NEXT:    .cfi_restore s2
; DEFAULT-NEXT:    .cfi_restore s3
; DEFAULT-NEXT:    .cfi_restore s4
; DEFAULT-NEXT:    .cfi_restore s5
; DEFAULT-NEXT:    .cfi_restore s6
; DEFAULT-NEXT:    .cfi_restore s7
; DEFAULT-NEXT:    .cfi_restore s8
; DEFAULT-NEXT:    .cfi_restore s9
; DEFAULT-NEXT:    .cfi_restore s10
; DEFAULT-NEXT:    addi sp, sp, 128
; DEFAULT-NEXT:    .cfi_def_cfa_offset 0
; DEFAULT-NEXT:    ret
entry:
  br i1 %tobool.not.i, label %if.then.i, label %if.end.i

if.then.i:                                        ; preds = %entry
  br label %cond.end

if.end.i:                                         ; preds = %entry
  %call.i = call fastcc i8 null(ptr null, ptr null)
  br label %cond.end

cond.end:                                         ; preds = %if.end.i, %if.then.i
  br i1 %tobool.not.i, label %if.then26, label %do.body

if.then26:                                        ; preds = %cond.end
  ret i32 0

do.body:                                          ; preds = %if.end270, %cond.end
  %d1.1 = phi i32 [ %add306, %if.end270 ], [ 0, %cond.end ]
  %tobool31.not = icmp eq i32 1, 0
  br i1 %tobool31.not, label %if.else68, label %if.then32

if.then32:                                        ; preds = %do.body
  br i1 %tobool.not.i, label %if.then273.loopexit372, label %if.else38

if.else38:                                        ; preds = %if.then32
  switch i8 %retval.0.i, label %if.else51 [
    i8 0, label %if.then273.loopexit372
    i8 7, label %if.then45
  ]

if.then45:                                        ; preds = %if.else38
  store i16 1, ptr null, align 8
  br i1 %cmp.i137, label %if.then273.loopexit372, label %if.end.i138

if.end.i138:                                      ; preds = %if.then45
  br i1 %cmp4.i, label %if.then273.loopexit372, label %if.end7.i

if.end7.i:                                        ; preds = %if.end.i138
  br i1 %cmp24, label %if.then273.loopexit372, label %if.end11.i

if.end11.i:                                       ; preds = %if.end7.i
  br i1 %tobool.not.i, label %if.then273.loopexit372, label %if.end270

if.else51:                                        ; preds = %if.else38
  ret i32 0

if.else68:                                        ; preds = %do.body
  br i1 %tobool.not.i, label %if.end270, label %if.then116

if.then116:                                       ; preds = %if.else68
  br i1 %cmp35, label %if.then273.loopexit372, label %if.else130

if.else130:                                       ; preds = %if.then116
  br i1 %cmp24, label %if.then273.loopexit372, label %if.else134

if.else134:                                       ; preds = %if.else130
  br i1 %tobool.not.i, label %if.then144, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %if.else134
  br i1 %tobool.not.i, label %if.else148, label %if.then144

if.then144:                                       ; preds = %lor.lhs.false, %if.else134
  ret i32 0

if.else148:                                       ; preds = %lor.lhs.false
  %idxprom174 = zext i32 %d1.1 to i64
  %arrayidx175 = getelementptr i8, ptr %pKey1, i64 %idxprom174
  %call178 = tail call i32 null(ptr %arrayidx175, ptr %pPKey2, i64 0)
  br label %if.end270

if.end270:                                        ; preds = %if.else148, %if.else68, %if.end11.i
  %add30624 = add i32 0, %nKey1
  %cmp313 = icmp ult i32 %conv9, %idx1.1
  %cmp315 = icmp ule i32 %add306, %nKey1
  %2 = select i1 %cmp313, i1 %cmp315, i1 false
  br i1 %2, label %do.body, label %do.end

if.then273.loopexit372:                           ; preds = %if.else130, %if.then116, %if.end11.i, %if.end7.i, %if.end.i138, %if.then45, %if.else38, %if.then32
  ret i32 %1

do.end:                                           ; preds = %if.end270
  ret i32 0
}
