; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=OLD
; RUN: llc -mtriple=x86_64-linux -enable-new-shrink-wrap -verify-machineinstrs \
; RUN:   < %s | FileCheck %s --check-prefix=NEW

; The block duplication of NewShrinkWrap is target independent. Here the loop
; header needs no frame and has an exit: the new pass duplicates the header and
; the exit block, so that leaving the loop on the first iteration does not set
; up the frame.

declare void @g()

define void @loop_exit() {
; OLD-LABEL: loop_exit:
; OLD:       # %bb.0: # %entry
; OLD-NEXT:    pushq %rax
; OLD-NEXT:    .cfi_def_cfa_offset 16
; OLD-NEXT:    cmpl $0, 16
; OLD-NEXT:    je .LBB0_3
; OLD-NEXT:    .p2align 4
; OLD-NEXT:  .LBB0_2: # %body
; OLD-NEXT:    # =>This Inner Loop Header: Depth=1
; OLD-NEXT:    callq g@PLT
; OLD-NEXT:    cmpl $0, 16
; OLD-NEXT:    jne .LBB0_2
; OLD-NEXT:  .LBB0_3: # %exit
; OLD-NEXT:    popq %rax
; OLD-NEXT:    .cfi_def_cfa_offset 8
; OLD-NEXT:    retq
;
; NEW-LABEL: loop_exit:
; NEW:       # %bb.0: # %entry
; NEW-NEXT:    cmpl $0, 16
; NEW-NEXT:    je .LBB0_4
; NEW-NEXT:  # %bb.1: # %body
; NEW-NEXT:    pushq %rax
; NEW-NEXT:    .cfi_def_cfa_offset 16
; NEW-NEXT:    callq g@PLT
; NEW-NEXT:    cmpl $0, 16
; NEW-NEXT:    je .LBB0_3
; NEW-NEXT:    .p2align 4
; NEW-NEXT:  .LBB0_2: # %body
; NEW-NEXT:    # =>This Inner Loop Header: Depth=1
; NEW-NEXT:    callq g@PLT
; NEW-NEXT:    cmpl $0, 16
; NEW-NEXT:    jne .LBB0_2
; NEW-NEXT:  .LBB0_3: # %exit
; NEW-NEXT:    popq %rax
; NEW-NEXT:    .cfi_def_cfa_offset 8
; NEW-NEXT:  .LBB0_4: # %exit
; NEW-NEXT:    retq
entry:
  br label %header
header:
  %v = load volatile i32, ptr inttoptr (i64 16 to ptr)
  %c = icmp eq i32 %v, 0
  br i1 %c, label %exit, label %body
body:
  call void @g()
  br label %header
exit:
  ret void
}
