; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc < %s -mtriple=riscv32 -mattr=+v,+zvfh -verify-machineinstrs | FileCheck %s -check-prefixes=CHECK,RV32
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zvfh -verify-machineinstrs | FileCheck %s -check-prefixes=CHECK,RV64

define <vscale x 16 x i1> @match_nxv16i8_v1i8(<vscale x 16 x i8> %op1, <1 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v1i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v10, v8, v12
; CHECK-NEXT:    vmand.mm v0, v10, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <1 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <vscale x 16 x i1> @match_nxv16i8_v2i8(<vscale x 16 x i8> %op1, <2 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v2i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v10, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v14
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <2 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <vscale x 16 x i1> @match_nxv16i8_v4i8(<vscale x 16 x i8> %op1, <4 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmor.mm v10, v15, v14
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v16
; CHECK-NEXT:    vmor.mm v8, v8, v11
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <4 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <vscale x 16 x i1> @match_nxv16i8_v8i8(<vscale x 16 x i8> %op1, <8 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmseq.vv v17, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 4
; CHECK-NEXT:    vmseq.vv v18, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 5
; CHECK-NEXT:    vmor.mm v11, v15, v14
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vmor.mm v15, v11, v16
; CHECK-NEXT:    vrgather.vi v12, v10, 6
; CHECK-NEXT:    vmor.mm v11, v15, v17
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v16, v11, v18
; CHECK-NEXT:    vrgather.vi v12, v10, 7
; CHECK-NEXT:    vmor.mm v10, v16, v14
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v15
; CHECK-NEXT:    vmor.mm v8, v8, v11
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <8 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <vscale x 16 x i1> @match_nxv16i8_v16i8(<vscale x 16 x i8> %op1, <16 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmseq.vv v17, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 4
; CHECK-NEXT:    vmseq.vv v18, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 5
; CHECK-NEXT:    vmseq.vv v19, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 6
; CHECK-NEXT:    vmseq.vv v20, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 7
; CHECK-NEXT:    vmseq.vv v21, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 8
; CHECK-NEXT:    vmseq.vv v22, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 9
; CHECK-NEXT:    vmor.mm v11, v15, v14
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vmor.mm v15, v11, v16
; CHECK-NEXT:    vrgather.vi v12, v10, 10
; CHECK-NEXT:    vmor.mm v11, v15, v17
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v16, v11, v18
; CHECK-NEXT:    vrgather.vi v12, v10, 11
; CHECK-NEXT:    vmor.mm v11, v16, v19
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vmor.mm v17, v11, v20
; CHECK-NEXT:    vrgather.vi v12, v10, 12
; CHECK-NEXT:    vmor.mm v11, v17, v21
; CHECK-NEXT:    vmseq.vv v17, v8, v12
; CHECK-NEXT:    vmor.mm v18, v11, v22
; CHECK-NEXT:    vrgather.vi v12, v10, 13
; CHECK-NEXT:    vmor.mm v11, v18, v14
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vmor.mm v15, v11, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 14
; CHECK-NEXT:    vmor.mm v11, v15, v16
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v16, v11, v17
; CHECK-NEXT:    vrgather.vi v12, v10, 15
; CHECK-NEXT:    vmor.mm v10, v16, v14
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v15
; CHECK-NEXT:    vmor.mm v8, v8, v11
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <16 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <16 x i1> @match_v16i8_v1i8(<16 x i8> %op1, <1 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v1i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vrgather.vi v10, v9, 0
; CHECK-NEXT:    vmseq.vv v0, v8, v10, v0.t
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <1 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <16 x i1> @match_v16i8_v2i8(<16 x i8> %op1, <2 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v2i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vmseq.vv v9, v8, v10
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v8, v9
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <2 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <16 x i1> @match_v16i8_v4i8(<16 x i8> %op1, <4 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vmor.mm v9, v10, v12
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <4 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <16 x i1> @match_v16i8_v8i8(<16 x i8> %op1, <8 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vrgather.vi v13, v9, 4
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 5
; CHECK-NEXT:    vrgather.vi v13, v9, 6
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 7
; CHECK-NEXT:    vmor.mm v9, v10, v12
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <8 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <16 x i1> @match_v16i8_v16i8(<16 x i8> %op1, <16 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vrgather.vi v13, v9, 4
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 5
; CHECK-NEXT:    vrgather.vi v13, v9, 6
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 7
; CHECK-NEXT:    vrgather.vi v13, v9, 8
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 9
; CHECK-NEXT:    vrgather.vi v13, v9, 10
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 11
; CHECK-NEXT:    vrgather.vi v13, v9, 12
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 13
; CHECK-NEXT:    vrgather.vi v13, v9, 14
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 15
; CHECK-NEXT:    vmor.mm v9, v10, v12
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <16 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <8 x i1> @match_v8i8_v8i8(<8 x i8> %op1, <8 x i8> %op2, <8 x i1> %mask) {
; CHECK-LABEL: match_v8i8_v8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 4
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 5
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 6
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 7
; CHECK-NEXT:    vmor.mm v9, v10, v11
; CHECK-NEXT:    vmseq.vv v8, v8, v12
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <8 x i1> @llvm.experimental.vector.match(<8 x i8> %op1, <8 x i8> %op2, <8 x i1> %mask)
  ret <8 x i1> %r
}

define <vscale x 8 x i1> @match_nxv8i16_v8i16(<vscale x 8 x i16> %op1, <8 x i16> %op2, <vscale x 8 x i1> %mask) {
; CHECK-LABEL: match_nxv8i16_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmseq.vv v17, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 4
; CHECK-NEXT:    vmseq.vv v18, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 5
; CHECK-NEXT:    vmor.mm v11, v15, v14
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vmor.mm v15, v11, v16
; CHECK-NEXT:    vrgather.vi v12, v10, 6
; CHECK-NEXT:    vmor.mm v11, v15, v17
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v16, v11, v18
; CHECK-NEXT:    vrgather.vi v12, v10, 7
; CHECK-NEXT:    vmor.mm v10, v16, v14
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v15
; CHECK-NEXT:    vmor.mm v8, v8, v11
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 8 x i1> @llvm.experimental.vector.match(<vscale x 8 x i16> %op1, <8 x i16> %op2, <vscale x 8 x i1> %mask)
  ret <vscale x 8 x i1> %r
}

define <8 x i1> @match_v8i16(<8 x i16> %op1, <8 x i16> %op2, <8 x i1> %mask) {
; CHECK-LABEL: match_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vrgather.vi v13, v9, 4
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 5
; CHECK-NEXT:    vrgather.vi v13, v9, 6
; CHECK-NEXT:    vmor.mm v10, v10, v12
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v13
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vrgather.vi v11, v9, 7
; CHECK-NEXT:    vmor.mm v9, v10, v12
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <8 x i1> @llvm.experimental.vector.match(<8 x i16> %op1, <8 x i16> %op2, <8 x i1> %mask)
  ret <8 x i1> %r
}

; Cases where op2 has more elements than op1.

define <8 x i1> @match_v8i8_v16i8(<8 x i8> %op1, <16 x i8> %op2, <8 x i1> %mask) {
; CHECK-LABEL: match_v8i8_v16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v9, 8
; CHECK-NEXT:    vmv.x.s a0, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 9
; CHECK-NEXT:    vmv.x.s a1, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 10
; CHECK-NEXT:    vmv.x.s a2, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 11
; CHECK-NEXT:    vmv.x.s a3, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 12
; CHECK-NEXT:    vmv.x.s a4, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 13
; CHECK-NEXT:    vmv.x.s a5, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 14
; CHECK-NEXT:    vmv.x.s a6, v10
; CHECK-NEXT:    vslidedown.vi v10, v9, 15
; CHECK-NEXT:    vmv.x.s a7, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 3
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 4
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 5
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 6
; CHECK-NEXT:    vmor.mm v10, v10, v11
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v9, 7
; CHECK-NEXT:    vmor.mm v9, v10, v11
; CHECK-NEXT:    vmseq.vv v10, v8, v12
; CHECK-NEXT:    vmseq.vx v11, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v10
; CHECK-NEXT:    vmseq.vx v10, v8, a1
; CHECK-NEXT:    vmor.mm v9, v9, v11
; CHECK-NEXT:    vmseq.vx v11, v8, a2
; CHECK-NEXT:    vmor.mm v9, v9, v10
; CHECK-NEXT:    vmseq.vx v10, v8, a3
; CHECK-NEXT:    vmor.mm v9, v9, v11
; CHECK-NEXT:    vmseq.vx v11, v8, a4
; CHECK-NEXT:    vmor.mm v9, v9, v10
; CHECK-NEXT:    vmseq.vx v10, v8, a5
; CHECK-NEXT:    vmor.mm v9, v9, v11
; CHECK-NEXT:    vmseq.vx v11, v8, a6
; CHECK-NEXT:    vmor.mm v9, v9, v10
; CHECK-NEXT:    vmor.mm v9, v9, v11
; CHECK-NEXT:    vmseq.vx v8, v8, a7
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <8 x i1> @llvm.experimental.vector.match(<8 x i8> %op1, <16 x i8> %op2, <8 x i1> %mask)
  ret <8 x i1> %r
}

define <vscale x 16 x i1> @match_nxv16i8_v32i8(<vscale x 16 x i8> %op1, <32 x i8> %op2, <vscale x 16 x i1> %mask) {
; CHECK-LABEL: match_nxv16i8_v32i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v15, v14
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 4
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 5
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 6
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 7
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 8
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 9
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 10
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 11
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 12
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 13
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 14
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vrgather.vi v12, v10, 15
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vmor.mm v14, v14, v15
; CHECK-NEXT:    vslidedown.vi v12, v10, 16
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 17
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 18
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 19
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 20
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 21
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 22
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 23
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 24
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 25
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 26
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 27
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 28
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 29
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v14, v14, v12
; CHECK-NEXT:    vslidedown.vi v12, v10, 30
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v12, v14, v12
; CHECK-NEXT:    vslidedown.vi v10, v10, 31
; CHECK-NEXT:    vmv.x.s a0, v10
; CHECK-NEXT:    vmseq.vx v10, v8, a0
; CHECK-NEXT:    vmor.mm v8, v12, v10
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 16 x i1> @llvm.experimental.vector.match(<vscale x 16 x i8> %op1, <32 x i8> %op2, <vscale x 16 x i1> %mask)
  ret <vscale x 16 x i1> %r
}

define <16 x i1> @match_v16i8_v32i8(<16 x i8> %op1, <32 x i8> %op2, <16 x i1> %mask) {
; CHECK-LABEL: match_v16i8_v32i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v9, v10, 1
; CHECK-NEXT:    vmseq.vv v9, v8, v9
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v12, v9
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 4
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 5
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 6
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 7
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 8
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 9
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 10
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 12
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 13
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 14
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 15
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 16
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 17
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 18
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 19
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 20
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 21
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 22
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 23
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 24
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 25
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 26
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 27
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 28
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 29
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v10, 30
; CHECK-NEXT:    vmv.x.s a0, v12
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v12, v8, a0
; CHECK-NEXT:    vmor.mm v9, v9, v12
; CHECK-NEXT:    vsetivli zero, 1, e8, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 31
; CHECK-NEXT:    vmv.x.s a0, v10
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmseq.vx v8, v8, a0
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <16 x i1> @llvm.experimental.vector.match(<16 x i8> %op1, <32 x i8> %op2, <16 x i1> %mask)
  ret <16 x i1> %r
}

define <vscale x 4 x i1> @match_nxv4xi32_v4i32(<vscale x 4 x i32> %op1, <4 x i32> %op2, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: match_nxv4xi32_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v15, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 2
; CHECK-NEXT:    vmseq.vv v16, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 3
; CHECK-NEXT:    vmor.mm v10, v15, v14
; CHECK-NEXT:    vmseq.vv v11, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v16
; CHECK-NEXT:    vmor.mm v8, v8, v11
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 4 x i1> @llvm.experimental.vector.match(<vscale x 4 x i32> %op1, <4 x i32> %op2, <vscale x 4 x i1> %mask)
  ret <vscale x 4 x i1> %r
}

define <vscale x 2 x i1> @match_nxv2xi64_v2i64(<vscale x 2 x i64> %op1, <2 x i64> %op2, <vscale x 2 x i1> %mask) {
; CHECK-LABEL: match_nxv2xi64_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; CHECK-NEXT:    vrgather.vi v12, v10, 1
; CHECK-NEXT:    vmseq.vv v14, v8, v12
; CHECK-NEXT:    vrgather.vi v12, v10, 0
; CHECK-NEXT:    vmseq.vv v10, v8, v12
; CHECK-NEXT:    vmor.mm v8, v10, v14
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <vscale x 2 x i1> @llvm.experimental.vector.match(<vscale x 2 x i64> %op1, <2 x i64> %op2, <vscale x 2 x i1> %mask)
  ret <vscale x 2 x i1> %r
}

define <4 x i1> @match_v4xi32_v4i32(<4 x i32> %op1, <4 x i32> %op2, <4 x i1> %mask) {
; CHECK-LABEL: match_v4xi32_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vrgather.vi v12, v9, 2
; CHECK-NEXT:    vmseq.vv v10, v8, v10
; CHECK-NEXT:    vmseq.vv v11, v8, v11
; CHECK-NEXT:    vmseq.vv v12, v8, v12
; CHECK-NEXT:    vmor.mm v10, v11, v10
; CHECK-NEXT:    vrgather.vi v11, v9, 3
; CHECK-NEXT:    vmor.mm v9, v10, v12
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v9, v8
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <4 x i1> @llvm.experimental.vector.match(<4 x i32> %op1, <4 x i32> %op2, <4 x i1> %mask)
  ret <4 x i1> %r
}

define <2 x i1> @match_v2xi64_v2i64(<2 x i64> %op1, <2 x i64> %op2, <2 x i1> %mask) {
; CHECK-LABEL: match_v2xi64_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vrgather.vi v10, v9, 1
; CHECK-NEXT:    vrgather.vi v11, v9, 0
; CHECK-NEXT:    vmseq.vv v9, v8, v10
; CHECK-NEXT:    vmseq.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v8, v8, v9
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
  %r = tail call <2 x i1> @llvm.experimental.vector.match(<2 x i64> %op1, <2 x i64> %op2, <2 x i1> %mask)
  ret <2 x i1> %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
; RV64: {{.*}}
